// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/webhook/v1/webhook.proto

package webhookv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookEvent int32

const (
	WebhookEvent_WEBHOOK_EVENT_UNSPECIFIED WebhookEvent = 0
	WebhookEvent_WEBHOOK_EVENT_CREATED     WebhookEvent = 1
	WebhookEvent_WEBHOOK_EVENT_UPDATED     WebhookEvent = 2
	WebhookEvent_WEBHOOK_EVENT_DELETED     WebhookEvent = 3
)

// Enum value maps for WebhookEvent.
var (
	WebhookEvent_name = map[int32]string{
		0: "WEBHOOK_EVENT_UNSPECIFIED",
		1: "WEBHOOK_EVENT_CREATED",
		2: "WEBHOOK_EVENT_UPDATED",
		3: "WEBHOOK_EVENT_DELETED",
	}
	WebhookEvent_value = map[string]int32{
		"WEBHOOK_EVENT_UNSPECIFIED": 0,
		"WEBHOOK_EVENT_CREATED":     1,
		"WEBHOOK_EVENT_UPDATED":     2,
		"WEBHOOK_EVENT_DELETED":     3,
	}
)

func (x WebhookEvent) Enum() *WebhookEvent {
	p := new(WebhookEvent)
	*p = x
	return p
}

func (x WebhookEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebhookEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_elara_webhook_v1_webhook_proto_enumTypes[0].Descriptor()
}

func (WebhookEvent) Type() protoreflect.EnumType {
	return &file_elara_webhook_v1_webhook_proto_enumTypes[0]
}

func (x WebhookEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebhookEvent.Descriptor instead.
func (WebhookEvent) EnumDescriptor() ([]byte, []int) {
	return file_elara_webhook_v1_webhook_proto_rawDescGZIP(), []int{0}
}

type Webhook struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url             string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	NamespaceFilter string                 `protobuf:"bytes,3,opt,name=namespace_filter,json=namespaceFilter,proto3" json:"namespace_filter,omitempty"`
	PathPrefix      string                 `protobuf:"bytes,4,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Events          []WebhookEvent         `protobuf:"varint,5,rep,packed,name=events,proto3,enum=elara.webhook.v1.WebhookEvent" json:"events,omitempty"`
	Enabled         bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_elara_webhook_v1_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_elara_webhook_v1_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook.ProtoReflect.Descriptor instead.
func (*Webhook) Descriptor() ([]byte, []int) {
	return file_elara_webhook_v1_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *Webhook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Webhook) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Webhook) GetNamespaceFilter() string {
	if x != nil {
		return x.NamespaceFilter
	}
	return ""
}

func (x *Webhook) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Webhook) GetEvents() []WebhookEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Webhook) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Webhook) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Webhook) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeliveryAttempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptNumber int32                  `protobuf:"varint,1,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAttempt) Reset() {
	*x = DeliveryAttempt{}
	mi := &file_elara_webhook_v1_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAttempt) ProtoMessage() {}

func (x *DeliveryAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_elara_webhook_v1_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAttempt.ProtoReflect.Descriptor instead.
func (*DeliveryAttempt) Descriptor() ([]byte, []int) {
	return file_elara_webhook_v1_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryAttempt) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *DeliveryAttempt) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeliveryAttempt) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *DeliveryAttempt) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeliveryAttempt) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeliveryAttempt) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_elara_webhook_v1_webhook_proto protoreflect.FileDescriptor

const file_elara_webhook_v1_webhook_proto_rawDesc = "" +
	"\n" +
	"\x1eelara/webhook/v1/webhook.proto\x12\x10elara.webhook.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x02\n" +
	"\aWebhook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12)\n" +
	"\x10namespace_filter\x18\x03 \x01(\tR\x0fnamespaceFilter\x12\x1f\n" +
	"\vpath_prefix\x18\x04 \x01(\tR\n" +
	"pathPrefix\x126\n" +
	"\x06events\x18\x05 \x03(\x0e2\x1e.elara.webhook.v1.WebhookEventR\x06events\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe2\x01\n" +
	"\x0fDeliveryAttempt\x12%\n" +
	"\x0eattempt_number\x18\x01 \x01(\x05R\rattemptNumber\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*~\n" +
	"\fWebhookEvent\x12\x1d\n" +
	"\x19WEBHOOK_EVENT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15WEBHOOK_EVENT_CREATED\x10\x01\x12\x19\n" +
	"\x15WEBHOOK_EVENT_UPDATED\x10\x02\x12\x19\n" +
	"\x15WEBHOOK_EVENT_DELETED\x10\x03B\xd2\x01\n" +
	"\x14com.elara.webhook.v1B\fWebhookProtoP\x01ZJgithub.com/sergeyslonimsky/elara/internal/proto/elara/webhook/v1;webhookv1\xa2\x02\x03EWX\xaa\x02\x10Elara.Webhook.V1\xca\x02\x10Elara\\Webhook\\V1\xe2\x02\x1cElara\\Webhook\\V1\\GPBMetadata\xea\x02\x12Elara::Webhook::V1b\x06proto3"

var (
	file_elara_webhook_v1_webhook_proto_rawDescOnce sync.Once
	file_elara_webhook_v1_webhook_proto_rawDescData []byte
)

func file_elara_webhook_v1_webhook_proto_rawDescGZIP() []byte {
	file_elara_webhook_v1_webhook_proto_rawDescOnce.Do(func() {
		file_elara_webhook_v1_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_webhook_v1_webhook_proto_rawDesc), len(file_elara_webhook_v1_webhook_proto_rawDesc)))
	})
	return file_elara_webhook_v1_webhook_proto_rawDescData
}

var file_elara_webhook_v1_webhook_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_elara_webhook_v1_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_elara_webhook_v1_webhook_proto_goTypes = []any{
	(WebhookEvent)(0),             // 0: elara.webhook.v1.WebhookEvent
	(*Webhook)(nil),               // 1: elara.webhook.v1.Webhook
	(*DeliveryAttempt)(nil),       // 2: elara.webhook.v1.DeliveryAttempt
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_elara_webhook_v1_webhook_proto_depIdxs = []int32{
	0, // 0: elara.webhook.v1.Webhook.events:type_name -> elara.webhook.v1.WebhookEvent
	3, // 1: elara.webhook.v1.Webhook.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: elara.webhook.v1.Webhook.updated_at:type_name -> google.protobuf.Timestamp
	3, // 3: elara.webhook.v1.DeliveryAttempt.timestamp:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_elara_webhook_v1_webhook_proto_init() }
func file_elara_webhook_v1_webhook_proto_init() {
	if File_elara_webhook_v1_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_webhook_v1_webhook_proto_rawDesc), len(file_elara_webhook_v1_webhook_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_elara_webhook_v1_webhook_proto_goTypes,
		DependencyIndexes: file_elara_webhook_v1_webhook_proto_depIdxs,
		EnumInfos:         file_elara_webhook_v1_webhook_proto_enumTypes,
		MessageInfos:      file_elara_webhook_v1_webhook_proto_msgTypes,
	}.Build()
	File_elara_webhook_v1_webhook_proto = out.File
	file_elara_webhook_v1_webhook_proto_goTypes = nil
	file_elara_webhook_v1_webhook_proto_depIdxs = nil
}
