syntax = "proto3";

package elara.auth.v1;

import "elara/auth/v1/auth.proto";

service AuthService {
  rpc GetAuthInfo(GetAuthInfoRequest) returns (GetAuthInfoResponse);
  rpc OIDCLogin(OIDCLoginRequest) returns (OIDCLoginResponse);
  rpc OIDCCallback(OIDCCallbackRequest) returns (OIDCCallbackResponse);
  rpc BasicLogin(BasicLoginRequest) returns (BasicLoginResponse);
}

message GetAuthInfoRequest {}

message GetAuthInfoResponse {
  AuthType auth_type = 1;
}

message OIDCLoginRequest {}

message OIDCLoginResponse {
  string redirect_url = 1;
}

message OIDCCallbackRequest {
  string code = 1;
  string state = 2;
}

message OIDCCallbackResponse {}

message BasicLoginRequest {
  string email = 1;
  string password = 2;
}

message BasicLoginResponse {
  bool password_change_required = 1;
}
