version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/*"
      grpc:
        patterns:
          - "google.golang.org/grpc*"
          - "connectrpc.com/*"

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      dev:
        dependency-type: "development"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
