// Code generated by MockGen. DO NOT EDIT.
// Source: access.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_access.go -package=mock_auth -source=access.go
//

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccessEnforcer is a mock of AccessEnforcer interface.
type MockAccessEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockAccessEnforcerMockRecorder
	isgomock struct{}
}

// MockAccessEnforcerMockRecorder is the mock recorder for MockAccessEnforcer.
type MockAccessEnforcerMockRecorder struct {
	mock *MockAccessEnforcer
}

// NewMockAccessEnforcer creates a new mock instance.
func NewMockAccessEnforcer(ctrl *gomock.Controller) *MockAccessEnforcer {
	mock := &MockAccessEnforcer{ctrl: ctrl}
	mock.recorder = &MockAccessEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessEnforcer) EXPECT() *MockAccessEnforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockAccessEnforcer) Enforce(subject, domain, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, domain, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockAccessEnforcerMockRecorder) Enforce(subject, domain, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockAccessEnforcer)(nil).Enforce), subject, domain, object, action)
}
