coverage:
  status:
    patch:
      default:
        target: 80%
        threshold: 2%
        only_pulls: true

ignore:
  - "**/mocks/**"
  - "internal/proto/**"
  - "web/src/gen/**"
  - "internal/di/**"
  - "cmd/**"
  - "examples/**"
  - "test/**"
  - "internal/handler/ui/**"
  - "web/src/components/ui/sidebar.tsx"
  - "web/src/components/ui/chart.tsx"
