sonar.projectKey=sergeyslonimsky_elara
sonar.organization=sergeyslonimsky

sonar.exclusions=\
  internal/proto/**/*.pb.go,\
  internal/proto/**/*.connect.go,\
  web/src/gen/**/*.ts,\
  vendor/**/*

sonar.coverage.exclusions=\
  internal/proto/**/*.pb.go,\
  internal/proto/**/*.connect.go,\
  web/src/gen/**/*.ts,\
  vendor/**/*
