sonar.projectKey=sergeyslonimsky_elara
sonar.organization=sergeyslonimsky

sonar.sources=.
sonar.exclusions=**/*.pb.go,**/*.connect.go,internal/proto/**/*,**/gen/**/*.ts,vendor/**/*,**/mocks/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go,**/*.test.ts,**/*.test.tsx,**/src/test/**

sonar.coverage.exclusions=**/*.pb.go,**/*.connect.go,internal/proto/**/*,**/gen/**/*.ts,vendor/**/*,internal/di/**/*,**/*_test.go,**/mocks/**,**/*.test.ts,**/*.test.tsx,**/src/test/**

sonar.go.coverage.reportPaths=coverage.txt
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info
