sonar.projectKey=sergeyslonimsky_elara
sonar.organization=sergeyslonimsky

sonar.sources=.
sonar.exclusions=**/*.pb.go,**/*.connect.go,**/gen/**/*.ts,vendor/**/*

sonar.coverage.exclusions=**/*.pb.go,**/*.connect.go,**/gen/**/*.ts,vendor/**/*

sonar.go.coverage.reportPaths=coverage.txt
