// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: elara/auth/v1/access_service.proto

package authv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sergeyslonimsky/elara/internal/proto/elara/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccessServiceName is the fully-qualified name of the AccessService service.
	AccessServiceName = "elara.auth.v1.AccessService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccessServiceAssignRoleProcedure is the fully-qualified name of the AccessService's AssignRole
	// RPC.
	AccessServiceAssignRoleProcedure = "/elara.auth.v1.AccessService/AssignRole"
	// AccessServiceRevokeRoleProcedure is the fully-qualified name of the AccessService's RevokeRole
	// RPC.
	AccessServiceRevokeRoleProcedure = "/elara.auth.v1.AccessService/RevokeRole"
	// AccessServiceListPoliciesProcedure is the fully-qualified name of the AccessService's
	// ListPolicies RPC.
	AccessServiceListPoliciesProcedure = "/elara.auth.v1.AccessService/ListPolicies"
)

// AccessServiceClient is a client for the elara.auth.v1.AccessService service.
type AccessServiceClient interface {
	AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error)
	RevokeRole(context.Context, *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error)
	ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error)
}

// NewAccessServiceClient constructs a client for the elara.auth.v1.AccessService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccessServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccessServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	accessServiceMethods := v1.File_elara_auth_v1_access_service_proto.Services().ByName("AccessService").Methods()
	return &accessServiceClient{
		assignRole: connect.NewClient[v1.AssignRoleRequest, v1.AssignRoleResponse](
			httpClient,
			baseURL+AccessServiceAssignRoleProcedure,
			connect.WithSchema(accessServiceMethods.ByName("AssignRole")),
			connect.WithClientOptions(opts...),
		),
		revokeRole: connect.NewClient[v1.RevokeRoleRequest, v1.RevokeRoleResponse](
			httpClient,
			baseURL+AccessServiceRevokeRoleProcedure,
			connect.WithSchema(accessServiceMethods.ByName("RevokeRole")),
			connect.WithClientOptions(opts...),
		),
		listPolicies: connect.NewClient[v1.ListPoliciesRequest, v1.ListPoliciesResponse](
			httpClient,
			baseURL+AccessServiceListPoliciesProcedure,
			connect.WithSchema(accessServiceMethods.ByName("ListPolicies")),
			connect.WithClientOptions(opts...),
		),
	}
}

// accessServiceClient implements AccessServiceClient.
type accessServiceClient struct {
	assignRole   *connect.Client[v1.AssignRoleRequest, v1.AssignRoleResponse]
	revokeRole   *connect.Client[v1.RevokeRoleRequest, v1.RevokeRoleResponse]
	listPolicies *connect.Client[v1.ListPoliciesRequest, v1.ListPoliciesResponse]
}

// AssignRole calls elara.auth.v1.AccessService.AssignRole.
func (c *accessServiceClient) AssignRole(ctx context.Context, req *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error) {
	return c.assignRole.CallUnary(ctx, req)
}

// RevokeRole calls elara.auth.v1.AccessService.RevokeRole.
func (c *accessServiceClient) RevokeRole(ctx context.Context, req *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error) {
	return c.revokeRole.CallUnary(ctx, req)
}

// ListPolicies calls elara.auth.v1.AccessService.ListPolicies.
func (c *accessServiceClient) ListPolicies(ctx context.Context, req *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error) {
	return c.listPolicies.CallUnary(ctx, req)
}

// AccessServiceHandler is an implementation of the elara.auth.v1.AccessService service.
type AccessServiceHandler interface {
	AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error)
	RevokeRole(context.Context, *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error)
	ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error)
}

// NewAccessServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccessServiceHandler(svc AccessServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accessServiceMethods := v1.File_elara_auth_v1_access_service_proto.Services().ByName("AccessService").Methods()
	accessServiceAssignRoleHandler := connect.NewUnaryHandler(
		AccessServiceAssignRoleProcedure,
		svc.AssignRole,
		connect.WithSchema(accessServiceMethods.ByName("AssignRole")),
		connect.WithHandlerOptions(opts...),
	)
	accessServiceRevokeRoleHandler := connect.NewUnaryHandler(
		AccessServiceRevokeRoleProcedure,
		svc.RevokeRole,
		connect.WithSchema(accessServiceMethods.ByName("RevokeRole")),
		connect.WithHandlerOptions(opts...),
	)
	accessServiceListPoliciesHandler := connect.NewUnaryHandler(
		AccessServiceListPoliciesProcedure,
		svc.ListPolicies,
		connect.WithSchema(accessServiceMethods.ByName("ListPolicies")),
		connect.WithHandlerOptions(opts...),
	)
	return "/elara.auth.v1.AccessService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccessServiceAssignRoleProcedure:
			accessServiceAssignRoleHandler.ServeHTTP(w, r)
		case AccessServiceRevokeRoleProcedure:
			accessServiceRevokeRoleHandler.ServeHTTP(w, r)
		case AccessServiceListPoliciesProcedure:
			accessServiceListPoliciesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccessServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccessServiceHandler struct{}

func (UnimplementedAccessServiceHandler) AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.auth.v1.AccessService.AssignRole is not implemented"))
}

func (UnimplementedAccessServiceHandler) RevokeRole(context.Context, *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.auth.v1.AccessService.RevokeRole is not implemented"))
}

func (UnimplementedAccessServiceHandler) ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.auth.v1.AccessService.ListPolicies is not implemented"))
}
