// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: elara/auth/v1/group_service.proto

package authv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sergeyslonimsky/elara/internal/proto/elara/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GroupServiceName is the fully-qualified name of the GroupService service.
	GroupServiceName = "elara.auth.v1.GroupService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GroupServiceCreateGroupProcedure is the fully-qualified name of the GroupService's CreateGroup
	// RPC.
	GroupServiceCreateGroupProcedure = "/elara.auth.v1.GroupService/CreateGroup"
	// GroupServiceGetGroupProcedure is the fully-qualified name of the GroupService's GetGroup RPC.
	GroupServiceGetGroupProcedure = "/elara.auth.v1.GroupService/GetGroup"
	// GroupServiceUpdateGroupProcedure is the fully-qualified name of the GroupService's UpdateGroup
	// RPC.
	GroupServiceUpdateGroupProcedure = "/elara.auth.v1.GroupService/UpdateGroup"
	// GroupServiceDeleteGroupProcedure is the fully-qualified name of the GroupService's DeleteGroup
	// RPC.
	GroupServiceDeleteGroupProcedure = "/elara.auth.v1.GroupService/DeleteGroup"
	// GroupServiceListGroupsProcedure is the fully-qualified name of the GroupService's ListGroups RPC.
	GroupServiceListGroupsProcedure = "/elara.auth.v1.GroupService/ListGroups"
	// GroupServiceAddMemberProcedure is the fully-qualified name of the GroupService's AddMember RPC.
	GroupServiceAddMemberProcedure = "/elara.auth.v1.GroupService/AddMember"
	// GroupServiceRemoveMemberProcedure is the fully-qualified name of the GroupService's RemoveMember
	// RPC.
	GroupServiceRemoveMemberProcedure = "/elara.auth.v1.GroupService/RemoveMember"
)

// GroupServiceClient is a client for the elara.auth.v1.GroupService service.
type GroupServiceClient interface {
	CreateGroup(context.Context, *connect.Request[v1.CreateGroupRequest]) (*connect.Response[v1.CreateGroupResponse], error)
	GetGroup(context.Context, *connect.Request[v1.GetGroupRequest]) (*connect.Response[v1.GetGroupResponse], error)
	UpdateGroup(context.Context, *connect.Request[v1.UpdateGroupRequest]) (*connect.Response[v1.UpdateGroupResponse], error)
	DeleteGroup(context.Context, *connect.Request[v1.DeleteGroupRequest]) (*connect.Response[v1.DeleteGroupResponse], error)
	ListGroups(context.Context, *connect.Request[v1.ListGroupsRequest]) (*connect.Response[v1.ListGroupsResponse], error)
	AddMember(context.Context, *connect.Request[v1.AddMemberRequest]) (*connect.Response[v1.AddMemberResponse], error)
	RemoveMember(context.Context, *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error)
}

// NewGroupServiceClient constructs a client for the elara.auth.v1.GroupService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGroupServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GroupServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	groupServiceMethods := v1.File_elara_auth_v1_group_service_proto.Services().ByName("GroupService").Methods()
	return &groupServiceClient{
		createGroup: connect.NewClient[v1.CreateGroupRequest, v1.CreateGroupResponse](
			httpClient,
			baseURL+GroupServiceCreateGroupProcedure,
			connect.WithSchema(groupServiceMethods.ByName("CreateGroup")),
			connect.WithClientOptions(opts...),
		),
		getGroup: connect.NewClient[v1.GetGroupRequest, v1.GetGroupResponse](
			httpClient,
			baseURL+GroupServiceGetGroupProcedure,
			connect.WithSchema(groupServiceMethods.ByName("GetGroup")),
			connect.WithClientOptions(opts...),
		),
		updateGroup: connect.NewClient[v1.UpdateGroupRequest, v1.UpdateGroupResponse](
			httpClient,
			baseURL+GroupServiceUpdateGroupProcedure,
			connect.WithSchema(groupServiceMethods.ByName("UpdateGroup")),
			connect.WithClientOptions(opts...),
		),
		deleteGroup: connect.NewClient[v1.DeleteGroupRequest, v1.DeleteGroupResponse](
			httpClient,
			baseURL+GroupServiceDeleteGroupProcedure,
			connect.WithSchema(groupServiceMethods.ByName("DeleteGroup")),
			connect.WithClientOptions(opts...),
		),
		listGroups: connect.NewClient[v1.ListGroupsRequest, v1.ListGroupsResponse](
			httpClient,
			baseURL+GroupServiceListGroupsProcedure,
			connect.WithSchema(groupServiceMethods.ByName("ListGroups")),
			connect.WithClientOptions(opts...),
		),
		addMember: connect.NewClient[v1.AddMemberRequest, v1.AddMemberResponse](
			httpClient,
			baseURL+GroupServiceAddMemberProcedure,
			connect.WithSchema(groupServiceMethods.ByName("AddMember")),
			connect.WithClientOptions(opts...),
		),
		removeMember: connect.NewClient[v1.RemoveMemberRequest, v1.RemoveMemberResponse](
			httpClient,
			baseURL+GroupServiceRemoveMemberProcedure,
			connect.WithSchema(groupServiceMethods.ByName("RemoveMember")),
			connect.WithClientOptions(opts...),
		),
	}
}

// groupServiceClient implements GroupServiceClient.
type groupServiceClient struct {
	createGroup  *connect.Client[v1.CreateGroupRequest, v1.CreateGroupResponse]
	getGroup     *connect.Client[v1.GetGroupRequest, v1.GetGroupResponse]
	updateGroup  *connect.Client[v1.UpdateGroupRequest, v1.UpdateGroupResponse]
	deleteGroup  *connect.Client[v1.DeleteGroupRequest, v1.DeleteGroupResponse]
	listGroups   *connect.Client[v1.ListGroupsRequest, v1.ListGroupsResponse]
	addMember    *connect.Client[v1.AddMemberRequest, v1.AddMemberResponse]
	removeMember *connect.Client[v1.RemoveMemberRequest, v1.RemoveMemberResponse]
}

// CreateGroup calls elara.auth.v1.GroupService.CreateGroup.
func (c *groupServiceClient) CreateGroup(ctx context.Context, req *connect.Request[v1.CreateGroupRequest]) (*connect.Response[v1.CreateGroupResponse], error) {
	return c.createGroup.CallUnary(ctx, req)
}

// GetGroup calls elara.auth.v1.GroupService.GetGroup.
func (c *groupServiceClient) GetGroup(ctx context.Context, req *connect.Request[v1.GetGroupRequest]) (*connect.Response[v1.GetGroupResponse], error) {
	return c.getGroup.CallUnary(ctx, req)
}

// UpdateGroup calls elara.auth.v1.GroupService.UpdateGroup.
func (c *groupServiceClient) UpdateGroup(ctx context.Context, req *connect.Request[v1.UpdateGroupRequest]) (*connect.Response[v1.UpdateGroupResponse], error) {
	return c.updateGroup.CallUnary(ctx, req)
}

// DeleteGroup calls elara.auth.v1.GroupService.DeleteGroup.
func (c *groupServiceClient) DeleteGroup(ctx context.Context, req *connect.Request[v1.DeleteGroupRequest]) (*connect.Response[v1.DeleteGroupResponse], error) {
	return c.deleteGroup.CallUnary(ctx, req)
}

// ListGroups calls elara.auth.v1.GroupService.ListGroups.
func (c *groupServiceClient) ListGroups(ctx context.Context, req *connect.Request[v1.ListGroupsRequest]) (*connect.Response[v1.ListGroupsResponse], error) {
	return c.listGroups.CallUnary(ctx, req)
}

// AddMember calls elara.auth.v1.GroupService.AddMember.
func (c *groupServiceClient) AddMember(ctx context.Context, req *connect.Request[v1.AddMemberRequest]) (*connect.Response[v1.AddMemberResponse], error) {
	return c.addMember.CallUnary(ctx, req)
}

// RemoveMember calls elara.auth.v1.GroupService.RemoveMember.
func (c *groupServiceClient) RemoveMember(ctx context.Context, req *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error) {
	return c.removeMember.CallUnary(ctx, req)
}

// GroupServiceHandler is an implementation of the elara.auth.v1.GroupService service.
type GroupServiceHandler interface {
	CreateGroup(context.Context, *connect.Request[v1.CreateGroupRequest]) (*connect.Response[v1.CreateGroupResponse], error)
	GetGroup(context.Context, *connect.Request[v1.GetGroupRequest]) (*connect.Response[v1.GetGroupResponse], error)
	UpdateGroup(context.Context, *connect.Request[v1.UpdateGroupRequest]) (*connect.Response[v1.UpdateGroupResponse], error)
	DeleteGroup(context.Context, *connect.Request[v1.DeleteGroupRequest]) (*connect.Response[v1.DeleteGroupResponse], error)
	ListGroups(context.Context, *connect.Request[v1.ListGroupsRequest]) (*connect.Response[v1.ListGroupsResponse], error)
	AddMember(context.Context, *connect.Request[v1.AddMemberRequest]) (*connect.Response[v1.AddMemberResponse], error)
	RemoveMember(context.Context, *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error)
}

// NewGroupServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGroupServiceHandler(svc GroupServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	groupServiceMethods := v1.File_elara_auth_v1_group_service_proto.Services().ByName("GroupService").Methods()
	groupServiceCreateGroupHandler := connect.NewUnaryHandler(
		GroupServiceCreateGroupProcedure,
		svc.CreateGroup,
		connect.WithSchema(groupServiceMethods.ByName("CreateGroup")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceGetGroupHandler := connect.NewUnaryHandler(
		GroupServiceGetGroupProcedure,
		svc.GetGroup,
		connect.WithSchema(groupServiceMethods.ByName("GetGroup")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceUpdateGroupHandler := connect.NewUnaryHandler(
		GroupServiceUpdateGroupProcedure,
		svc.UpdateGroup,
		connect.WithSchema(groupServiceMethods.ByName("UpdateGroup")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceDeleteGroupHandler := connect.NewUnaryHandler(
		GroupServiceDeleteGroupProcedure,
		svc.DeleteGroup,
		connect.WithSchema(groupServiceMethods.ByName("DeleteGroup")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceListGroupsHandler := connect.NewUnaryHandler(
		GroupServiceListGroupsProcedure,
		svc.ListGroups,
		connect.WithSchema(groupServiceMethods.ByName("ListGroups")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceAddMemberHandler := connect.NewUnaryHandler(
		GroupServiceAddMemberProcedure,
		svc.AddMember,
		connect.WithSchema(groupServiceMethods.ByName("AddMember")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceRemoveMemberHandler := connect.NewUnaryHandler(
		GroupServiceRemoveMemberProcedure,
		svc.RemoveMember,
		connect.WithSchema(groupServiceMethods.ByName("RemoveMember")),
		connect.WithHandlerOptions(opts...),
	)
	return "/elara.auth.v1.GroupService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GroupServiceCreateGroupProcedure:
			groupServiceCreateGroupHandler.ServeHTTP(w, r)
		case GroupServiceGetGroupProcedure:
			groupServiceGetGroupHandler.ServeHTTP(w, r)
		case GroupServiceUpdateGroupProcedure:
			groupServiceUpdateGroupHandler.ServeHTTP(w, r)
		case GroupServiceDeleteGroupProcedure:
			groupServiceDeleteGroupHandler.ServeHTTP(w, r)
		case GroupServiceListGroupsProcedure:
			groupServiceListGroupsHandler.ServeHTTP(w, r)
		case GroupServiceAddMemberProcedure:
			groupServiceAddMemberHandler.ServeHTTP(w, r)
		case GroupServiceRemoveMemberProcedure:
			groupServiceRemoveMemberHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGroupServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGroupServiceHandler struct{}

func (UnimplementedGroupServiceHandler) CreateGroup(context.Context, *connect.Request[v1.CreateGroupRequest]) (*connect.Response[v1.CreateGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.auth.v1.GroupService.CreateGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) GetGroup(context.Context, *connect.Request[v1.GetGroupRequest]) (*connect.Response[v1.GetGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.auth.v1.GroupService.GetGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) UpdateGroup(context.Context, *connect.Request[v1.UpdateGroupRequest]) (*connect.Response[v1.UpdateGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.auth.v1.GroupService.UpdateGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) DeleteGroup(context.Context, *connect.Request[v1.DeleteGroupRequest]) (*connect.Response[v1.DeleteGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.auth.v1.GroupService.DeleteGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) ListGroups(context.Context, *connect.Request[v1.ListGroupsRequest]) (*connect.Response[v1.ListGroupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.auth.v1.GroupService.ListGroups is not implemented"))
}

func (UnimplementedGroupServiceHandler) AddMember(context.Context, *connect.Request[v1.AddMemberRequest]) (*connect.Response[v1.AddMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.auth.v1.GroupService.AddMember is not implemented"))
}

func (UnimplementedGroupServiceHandler) RemoveMember(context.Context, *connect.Request[v1.RemoveMemberRequest]) (*connect.Response[v1.RemoveMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.auth.v1.GroupService.RemoveMember is not implemented"))
}
