// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/auth/casbin (interfaces: ContextPolicyRepo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_adapter.go -package=casbin_mock github.com/sergeyslonimsky/elara/internal/auth/casbin ContextPolicyRepo
//

// Package casbin_mock is a generated GoMock package.
package casbin_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContextPolicyRepo is a mock of ContextPolicyRepo interface.
type MockContextPolicyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockContextPolicyRepoMockRecorder
	isgomock struct{}
}

// MockContextPolicyRepoMockRecorder is the mock recorder for MockContextPolicyRepo.
type MockContextPolicyRepoMockRecorder struct {
	mock *MockContextPolicyRepo
}

// NewMockContextPolicyRepo creates a new mock instance.
func NewMockContextPolicyRepo(ctrl *gomock.Controller) *MockContextPolicyRepo {
	mock := &MockContextPolicyRepo{ctrl: ctrl}
	mock.recorder = &MockContextPolicyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextPolicyRepo) EXPECT() *MockContextPolicyRepoMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockContextPolicyRepo) Load(ctx context.Context) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockContextPolicyRepoMockRecorder) Load(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockContextPolicyRepo)(nil).Load), ctx)
}

// Save mocks base method.
func (m *MockContextPolicyRepo) Save(ctx context.Context, rules [][]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, rules)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockContextPolicyRepoMockRecorder) Save(ctx, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockContextPolicyRepo)(nil).Save), ctx, rules)
}
