// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/auth (interfaces: createUserEnforcer,userCreator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/create_user_mock.go -package=auth_mock github.com/sergeyslonimsky/elara/internal/usecase/auth createUserEnforcer,userCreator
//

// Package auth_mock is a generated GoMock package.
package auth_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockcreateUserEnforcer is a mock of createUserEnforcer interface.
type MockcreateUserEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockcreateUserEnforcerMockRecorder
	isgomock struct{}
}

// MockcreateUserEnforcerMockRecorder is the mock recorder for MockcreateUserEnforcer.
type MockcreateUserEnforcerMockRecorder struct {
	mock *MockcreateUserEnforcer
}

// NewMockcreateUserEnforcer creates a new mock instance.
func NewMockcreateUserEnforcer(ctrl *gomock.Controller) *MockcreateUserEnforcer {
	mock := &MockcreateUserEnforcer{ctrl: ctrl}
	mock.recorder = &MockcreateUserEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreateUserEnforcer) EXPECT() *MockcreateUserEnforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockcreateUserEnforcer) Enforce(subject, arg1, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, arg1, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockcreateUserEnforcerMockRecorder) Enforce(subject, arg1, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockcreateUserEnforcer)(nil).Enforce), subject, arg1, object, action)
}

// MockuserCreator is a mock of userCreator interface.
type MockuserCreator struct {
	ctrl     *gomock.Controller
	recorder *MockuserCreatorMockRecorder
	isgomock struct{}
}

// MockuserCreatorMockRecorder is the mock recorder for MockuserCreator.
type MockuserCreatorMockRecorder struct {
	mock *MockuserCreator
}

// NewMockuserCreator creates a new mock instance.
func NewMockuserCreator(ctrl *gomock.Controller) *MockuserCreator {
	mock := &MockuserCreator{ctrl: ctrl}
	mock.recorder = &MockuserCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserCreator) EXPECT() *MockuserCreatorMockRecorder {
	return m.recorder
}

// SetPassword mocks base method.
func (m *MockuserCreator) SetPassword(ctx context.Context, email, hash string, changeRequired bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPassword", ctx, email, hash, changeRequired)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPassword indicates an expected call of SetPassword.
func (mr *MockuserCreatorMockRecorder) SetPassword(ctx, email, hash, changeRequired any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPassword", reflect.TypeOf((*MockuserCreator)(nil).SetPassword), ctx, email, hash, changeRequired)
}

// Upsert mocks base method.
func (m *MockuserCreator) Upsert(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockuserCreatorMockRecorder) Upsert(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockuserCreator)(nil).Upsert), ctx, user)
}
