// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/auth (interfaces: policyEnforcer,accessPolicyLoader)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_access.go -package=auth_mock github.com/sergeyslonimsky/elara/internal/usecase/auth policyEnforcer,accessPolicyLoader
//

// Package auth_mock is a generated GoMock package.
package auth_mock

import (
	context "context"
	reflect "reflect"

	casbin "github.com/sergeyslonimsky/elara/internal/auth/casbin"
	gomock "go.uber.org/mock/gomock"
)

// MockpolicyEnforcer is a mock of policyEnforcer interface.
type MockpolicyEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockpolicyEnforcerMockRecorder
	isgomock struct{}
}

// MockpolicyEnforcerMockRecorder is the mock recorder for MockpolicyEnforcer.
type MockpolicyEnforcerMockRecorder struct {
	mock *MockpolicyEnforcer
}

// NewMockpolicyEnforcer creates a new mock instance.
func NewMockpolicyEnforcer(ctrl *gomock.Controller) *MockpolicyEnforcer {
	mock := &MockpolicyEnforcer{ctrl: ctrl}
	mock.recorder = &MockpolicyEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpolicyEnforcer) EXPECT() *MockpolicyEnforcerMockRecorder {
	return m.recorder
}

// AddRoleForUser mocks base method.
func (m *MockpolicyEnforcer) AddRoleForUser(user, role, domain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoleForUser", user, role, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRoleForUser indicates an expected call of AddRoleForUser.
func (mr *MockpolicyEnforcerMockRecorder) AddRoleForUser(user, role, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoleForUser", reflect.TypeOf((*MockpolicyEnforcer)(nil).AddRoleForUser), user, role, domain)
}

// GetGroupingPolicy mocks base method.
func (m *MockpolicyEnforcer) GetGroupingPolicy() [][]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupingPolicy")
	ret0, _ := ret[0].([][]string)
	return ret0
}

// GetGroupingPolicy indicates an expected call of GetGroupingPolicy.
func (mr *MockpolicyEnforcerMockRecorder) GetGroupingPolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupingPolicy", reflect.TypeOf((*MockpolicyEnforcer)(nil).GetGroupingPolicy))
}

// RemoveRoleForUser mocks base method.
func (m *MockpolicyEnforcer) RemoveRoleForUser(user, role, domain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRoleForUser", user, role, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRoleForUser indicates an expected call of RemoveRoleForUser.
func (mr *MockpolicyEnforcerMockRecorder) RemoveRoleForUser(user, role, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRoleForUser", reflect.TypeOf((*MockpolicyEnforcer)(nil).RemoveRoleForUser), user, role, domain)
}

// SavePolicy mocks base method.
func (m *MockpolicyEnforcer) SavePolicy(ctx context.Context, loader casbin.PolicyLoader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePolicy", ctx, loader)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePolicy indicates an expected call of SavePolicy.
func (mr *MockpolicyEnforcerMockRecorder) SavePolicy(ctx, loader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePolicy", reflect.TypeOf((*MockpolicyEnforcer)(nil).SavePolicy), ctx, loader)
}

// MockaccessPolicyLoader is a mock of accessPolicyLoader interface.
type MockaccessPolicyLoader struct {
	ctrl     *gomock.Controller
	recorder *MockaccessPolicyLoaderMockRecorder
	isgomock struct{}
}

// MockaccessPolicyLoaderMockRecorder is the mock recorder for MockaccessPolicyLoader.
type MockaccessPolicyLoaderMockRecorder struct {
	mock *MockaccessPolicyLoader
}

// NewMockaccessPolicyLoader creates a new mock instance.
func NewMockaccessPolicyLoader(ctrl *gomock.Controller) *MockaccessPolicyLoader {
	mock := &MockaccessPolicyLoader{ctrl: ctrl}
	mock.recorder = &MockaccessPolicyLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccessPolicyLoader) EXPECT() *MockaccessPolicyLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockaccessPolicyLoader) Load(ctx context.Context) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockaccessPolicyLoaderMockRecorder) Load(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockaccessPolicyLoader)(nil).Load), ctx)
}

// Save mocks base method.
func (m *MockaccessPolicyLoader) Save(ctx context.Context, rules [][]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, rules)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockaccessPolicyLoaderMockRecorder) Save(ctx, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockaccessPolicyLoader)(nil).Save), ctx, rules)
}
