// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/auth (interfaces: tokenCreator,tokenLister,tokenDeleter,tokenIDGetter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_token.go -package=auth_mock github.com/sergeyslonimsky/elara/internal/usecase/auth tokenCreator,tokenLister,tokenDeleter,tokenIDGetter
//

// Package auth_mock is a generated GoMock package.
package auth_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocktokenCreator is a mock of tokenCreator interface.
type MocktokenCreator struct {
	ctrl     *gomock.Controller
	recorder *MocktokenCreatorMockRecorder
	isgomock struct{}
}

// MocktokenCreatorMockRecorder is the mock recorder for MocktokenCreator.
type MocktokenCreatorMockRecorder struct {
	mock *MocktokenCreator
}

// NewMocktokenCreator creates a new mock instance.
func NewMocktokenCreator(ctrl *gomock.Controller) *MocktokenCreator {
	mock := &MocktokenCreator{ctrl: ctrl}
	mock.recorder = &MocktokenCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenCreator) EXPECT() *MocktokenCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocktokenCreator) Create(ctx context.Context, pat *domain.PAT) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pat)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MocktokenCreatorMockRecorder) Create(ctx, pat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocktokenCreator)(nil).Create), ctx, pat)
}

// MocktokenLister is a mock of tokenLister interface.
type MocktokenLister struct {
	ctrl     *gomock.Controller
	recorder *MocktokenListerMockRecorder
	isgomock struct{}
}

// MocktokenListerMockRecorder is the mock recorder for MocktokenLister.
type MocktokenListerMockRecorder struct {
	mock *MocktokenLister
}

// NewMocktokenLister creates a new mock instance.
func NewMocktokenLister(ctrl *gomock.Controller) *MocktokenLister {
	mock := &MocktokenLister{ctrl: ctrl}
	mock.recorder = &MocktokenListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenLister) EXPECT() *MocktokenListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MocktokenLister) List(ctx context.Context, userEmail string) ([]*domain.PAT, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userEmail)
	ret0, _ := ret[0].([]*domain.PAT)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocktokenListerMockRecorder) List(ctx, userEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocktokenLister)(nil).List), ctx, userEmail)
}

// MocktokenDeleter is a mock of tokenDeleter interface.
type MocktokenDeleter struct {
	ctrl     *gomock.Controller
	recorder *MocktokenDeleterMockRecorder
	isgomock struct{}
}

// MocktokenDeleterMockRecorder is the mock recorder for MocktokenDeleter.
type MocktokenDeleterMockRecorder struct {
	mock *MocktokenDeleter
}

// NewMocktokenDeleter creates a new mock instance.
func NewMocktokenDeleter(ctrl *gomock.Controller) *MocktokenDeleter {
	mock := &MocktokenDeleter{ctrl: ctrl}
	mock.recorder = &MocktokenDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenDeleter) EXPECT() *MocktokenDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MocktokenDeleter) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MocktokenDeleterMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocktokenDeleter)(nil).Delete), ctx, id)
}

// MocktokenIDGetter is a mock of tokenIDGetter interface.
type MocktokenIDGetter struct {
	ctrl     *gomock.Controller
	recorder *MocktokenIDGetterMockRecorder
	isgomock struct{}
}

// MocktokenIDGetterMockRecorder is the mock recorder for MocktokenIDGetter.
type MocktokenIDGetterMockRecorder struct {
	mock *MocktokenIDGetter
}

// NewMocktokenIDGetter creates a new mock instance.
func NewMocktokenIDGetter(ctrl *gomock.Controller) *MocktokenIDGetter {
	mock := &MocktokenIDGetter{ctrl: ctrl}
	mock.recorder = &MocktokenIDGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenIDGetter) EXPECT() *MocktokenIDGetterMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocktokenIDGetter) GetByID(ctx context.Context, id string) (*domain.PAT, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.PAT)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocktokenIDGetterMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocktokenIDGetter)(nil).GetByID), ctx, id)
}
