// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/auth (interfaces: groupCreator,groupGetter,groupUpdater,groupDeleter,groupLister,groupEnforcer,groupSyncEnforcer,groupByNameFinder)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_group.go -package=auth_mock github.com/sergeyslonimsky/elara/internal/usecase/auth groupCreator,groupGetter,groupUpdater,groupDeleter,groupLister,groupEnforcer,groupSyncEnforcer,groupByNameFinder
//

// Package auth_mock is a generated GoMock package.
package auth_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockgroupCreator is a mock of groupCreator interface.
type MockgroupCreator struct {
	ctrl     *gomock.Controller
	recorder *MockgroupCreatorMockRecorder
	isgomock struct{}
}

// MockgroupCreatorMockRecorder is the mock recorder for MockgroupCreator.
type MockgroupCreatorMockRecorder struct {
	mock *MockgroupCreator
}

// NewMockgroupCreator creates a new mock instance.
func NewMockgroupCreator(ctrl *gomock.Controller) *MockgroupCreator {
	mock := &MockgroupCreator{ctrl: ctrl}
	mock.recorder = &MockgroupCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgroupCreator) EXPECT() *MockgroupCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockgroupCreator) Create(ctx context.Context, group *domain.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockgroupCreatorMockRecorder) Create(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockgroupCreator)(nil).Create), ctx, group)
}

// MockgroupGetter is a mock of groupGetter interface.
type MockgroupGetter struct {
	ctrl     *gomock.Controller
	recorder *MockgroupGetterMockRecorder
	isgomock struct{}
}

// MockgroupGetterMockRecorder is the mock recorder for MockgroupGetter.
type MockgroupGetterMockRecorder struct {
	mock *MockgroupGetter
}

// NewMockgroupGetter creates a new mock instance.
func NewMockgroupGetter(ctrl *gomock.Controller) *MockgroupGetter {
	mock := &MockgroupGetter{ctrl: ctrl}
	mock.recorder = &MockgroupGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgroupGetter) EXPECT() *MockgroupGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockgroupGetter) Get(ctx context.Context, id string) (*domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockgroupGetterMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockgroupGetter)(nil).Get), ctx, id)
}

// MockgroupUpdater is a mock of groupUpdater interface.
type MockgroupUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockgroupUpdaterMockRecorder
	isgomock struct{}
}

// MockgroupUpdaterMockRecorder is the mock recorder for MockgroupUpdater.
type MockgroupUpdaterMockRecorder struct {
	mock *MockgroupUpdater
}

// NewMockgroupUpdater creates a new mock instance.
func NewMockgroupUpdater(ctrl *gomock.Controller) *MockgroupUpdater {
	mock := &MockgroupUpdater{ctrl: ctrl}
	mock.recorder = &MockgroupUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgroupUpdater) EXPECT() *MockgroupUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockgroupUpdater) Update(ctx context.Context, group *domain.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockgroupUpdaterMockRecorder) Update(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockgroupUpdater)(nil).Update), ctx, group)
}

// MockgroupDeleter is a mock of groupDeleter interface.
type MockgroupDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockgroupDeleterMockRecorder
	isgomock struct{}
}

// MockgroupDeleterMockRecorder is the mock recorder for MockgroupDeleter.
type MockgroupDeleterMockRecorder struct {
	mock *MockgroupDeleter
}

// NewMockgroupDeleter creates a new mock instance.
func NewMockgroupDeleter(ctrl *gomock.Controller) *MockgroupDeleter {
	mock := &MockgroupDeleter{ctrl: ctrl}
	mock.recorder = &MockgroupDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgroupDeleter) EXPECT() *MockgroupDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockgroupDeleter) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockgroupDeleterMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockgroupDeleter)(nil).Delete), ctx, id)
}

// MockgroupLister is a mock of groupLister interface.
type MockgroupLister struct {
	ctrl     *gomock.Controller
	recorder *MockgroupListerMockRecorder
	isgomock struct{}
}

// MockgroupListerMockRecorder is the mock recorder for MockgroupLister.
type MockgroupListerMockRecorder struct {
	mock *MockgroupLister
}

// NewMockgroupLister creates a new mock instance.
func NewMockgroupLister(ctrl *gomock.Controller) *MockgroupLister {
	mock := &MockgroupLister{ctrl: ctrl}
	mock.recorder = &MockgroupListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgroupLister) EXPECT() *MockgroupListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockgroupLister) List(ctx context.Context) ([]*domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockgroupListerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockgroupLister)(nil).List), ctx)
}

// MockgroupEnforcer is a mock of groupEnforcer interface.
type MockgroupEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockgroupEnforcerMockRecorder
	isgomock struct{}
}

// MockgroupEnforcerMockRecorder is the mock recorder for MockgroupEnforcer.
type MockgroupEnforcerMockRecorder struct {
	mock *MockgroupEnforcer
}

// NewMockgroupEnforcer creates a new mock instance.
func NewMockgroupEnforcer(ctrl *gomock.Controller) *MockgroupEnforcer {
	mock := &MockgroupEnforcer{ctrl: ctrl}
	mock.recorder = &MockgroupEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgroupEnforcer) EXPECT() *MockgroupEnforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockgroupEnforcer) Enforce(subject, arg1, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, arg1, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockgroupEnforcerMockRecorder) Enforce(subject, arg1, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockgroupEnforcer)(nil).Enforce), subject, arg1, object, action)
}

// MockgroupSyncEnforcer is a mock of groupSyncEnforcer interface.
type MockgroupSyncEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockgroupSyncEnforcerMockRecorder
	isgomock struct{}
}

// MockgroupSyncEnforcerMockRecorder is the mock recorder for MockgroupSyncEnforcer.
type MockgroupSyncEnforcerMockRecorder struct {
	mock *MockgroupSyncEnforcer
}

// NewMockgroupSyncEnforcer creates a new mock instance.
func NewMockgroupSyncEnforcer(ctrl *gomock.Controller) *MockgroupSyncEnforcer {
	mock := &MockgroupSyncEnforcer{ctrl: ctrl}
	mock.recorder = &MockgroupSyncEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgroupSyncEnforcer) EXPECT() *MockgroupSyncEnforcerMockRecorder {
	return m.recorder
}

// AddRoleForUser mocks base method.
func (m *MockgroupSyncEnforcer) AddRoleForUser(user, role, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoleForUser", user, role, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRoleForUser indicates an expected call of AddRoleForUser.
func (mr *MockgroupSyncEnforcerMockRecorder) AddRoleForUser(user, role, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoleForUser", reflect.TypeOf((*MockgroupSyncEnforcer)(nil).AddRoleForUser), user, role, arg2)
}

// GetRulesForSubject mocks base method.
func (m *MockgroupSyncEnforcer) GetRulesForSubject(subject string) [][]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRulesForSubject", subject)
	ret0, _ := ret[0].([][]string)
	return ret0
}

// GetRulesForSubject indicates an expected call of GetRulesForSubject.
func (mr *MockgroupSyncEnforcerMockRecorder) GetRulesForSubject(subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRulesForSubject", reflect.TypeOf((*MockgroupSyncEnforcer)(nil).GetRulesForSubject), subject)
}

// RemoveRoleForUser mocks base method.
func (m *MockgroupSyncEnforcer) RemoveRoleForUser(user, role, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRoleForUser", user, role, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRoleForUser indicates an expected call of RemoveRoleForUser.
func (mr *MockgroupSyncEnforcerMockRecorder) RemoveRoleForUser(user, role, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRoleForUser", reflect.TypeOf((*MockgroupSyncEnforcer)(nil).RemoveRoleForUser), user, role, arg2)
}

// MockgroupByNameFinder is a mock of groupByNameFinder interface.
type MockgroupByNameFinder struct {
	ctrl     *gomock.Controller
	recorder *MockgroupByNameFinderMockRecorder
	isgomock struct{}
}

// MockgroupByNameFinderMockRecorder is the mock recorder for MockgroupByNameFinder.
type MockgroupByNameFinderMockRecorder struct {
	mock *MockgroupByNameFinder
}

// NewMockgroupByNameFinder creates a new mock instance.
func NewMockgroupByNameFinder(ctrl *gomock.Controller) *MockgroupByNameFinder {
	mock := &MockgroupByNameFinder{ctrl: ctrl}
	mock.recorder = &MockgroupByNameFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgroupByNameFinder) EXPECT() *MockgroupByNameFinderMockRecorder {
	return m.recorder
}

// FindByName mocks base method.
func (m *MockgroupByNameFinder) FindByName(ctx context.Context, name string) (*domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockgroupByNameFinderMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockgroupByNameFinder)(nil).FindByName), ctx, name)
}
