// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/auth (interfaces: policyEnforcer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_access.go -package=auth_mock github.com/sergeyslonimsky/elara/internal/usecase/auth policyEnforcer
//

// Package auth_mock is a generated GoMock package.
package auth_mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockpolicyEnforcer is a mock of policyEnforcer interface.
type MockpolicyEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockpolicyEnforcerMockRecorder
	isgomock struct{}
}

// MockpolicyEnforcerMockRecorder is the mock recorder for MockpolicyEnforcer.
type MockpolicyEnforcerMockRecorder struct {
	mock *MockpolicyEnforcer
}

// NewMockpolicyEnforcer creates a new mock instance.
func NewMockpolicyEnforcer(ctrl *gomock.Controller) *MockpolicyEnforcer {
	mock := &MockpolicyEnforcer{ctrl: ctrl}
	mock.recorder = &MockpolicyEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpolicyEnforcer) EXPECT() *MockpolicyEnforcerMockRecorder {
	return m.recorder
}

// AddRoleForUser mocks base method.
func (m *MockpolicyEnforcer) AddRoleForUser(user, role, domain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoleForUser", user, role, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRoleForUser indicates an expected call of AddRoleForUser.
func (mr *MockpolicyEnforcerMockRecorder) AddRoleForUser(user, role, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoleForUser", reflect.TypeOf((*MockpolicyEnforcer)(nil).AddRoleForUser), user, role, domain)
}

// Enforce mocks base method.
func (m *MockpolicyEnforcer) Enforce(subject, domain, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, domain, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockpolicyEnforcerMockRecorder) Enforce(subject, domain, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockpolicyEnforcer)(nil).Enforce), subject, domain, object, action)
}

// GetGroupingPolicy mocks base method.
func (m *MockpolicyEnforcer) GetGroupingPolicy() [][]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupingPolicy")
	ret0, _ := ret[0].([][]string)
	return ret0
}

// GetGroupingPolicy indicates an expected call of GetGroupingPolicy.
func (mr *MockpolicyEnforcerMockRecorder) GetGroupingPolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupingPolicy", reflect.TypeOf((*MockpolicyEnforcer)(nil).GetGroupingPolicy))
}

// RemoveRoleForUser mocks base method.
func (m *MockpolicyEnforcer) RemoveRoleForUser(user, role, domain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRoleForUser", user, role, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRoleForUser indicates an expected call of RemoveRoleForUser.
func (mr *MockpolicyEnforcerMockRecorder) RemoveRoleForUser(user, role, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRoleForUser", reflect.TypeOf((*MockpolicyEnforcer)(nil).RemoveRoleForUser), user, role, domain)
}
