// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/auth (interfaces: userLister,userGetter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_user.go -package=auth_mock github.com/sergeyslonimsky/elara/internal/usecase/auth userLister,userGetter
//

// Package auth_mock is a generated GoMock package.
package auth_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockuserLister is a mock of userLister interface.
type MockuserLister struct {
	ctrl     *gomock.Controller
	recorder *MockuserListerMockRecorder
	isgomock struct{}
}

// MockuserListerMockRecorder is the mock recorder for MockuserLister.
type MockuserListerMockRecorder struct {
	mock *MockuserLister
}

// NewMockuserLister creates a new mock instance.
func NewMockuserLister(ctrl *gomock.Controller) *MockuserLister {
	mock := &MockuserLister{ctrl: ctrl}
	mock.recorder = &MockuserListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserLister) EXPECT() *MockuserListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockuserLister) List(ctx context.Context) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockuserListerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockuserLister)(nil).List), ctx)
}

// MockuserGetter is a mock of userGetter interface.
type MockuserGetter struct {
	ctrl     *gomock.Controller
	recorder *MockuserGetterMockRecorder
	isgomock struct{}
}

// MockuserGetterMockRecorder is the mock recorder for MockuserGetter.
type MockuserGetterMockRecorder struct {
	mock *MockuserGetter
}

// NewMockuserGetter creates a new mock instance.
func NewMockuserGetter(ctrl *gomock.Controller) *MockuserGetter {
	mock := &MockuserGetter{ctrl: ctrl}
	mock.recorder = &MockuserGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserGetter) EXPECT() *MockuserGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockuserGetter) Get(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockuserGetterMockRecorder) Get(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockuserGetter)(nil).Get), ctx, email)
}
