// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/group/v1/group_service.proto

package groupv1

import (
	v1 "github.com/sergeyslonimsky/elara/internal/proto/elara/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateGroupRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupResponse) Reset() {
	*x = UpdateGroupResponse{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupResponse) ProtoMessage() {}

func (x *UpdateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateGroupMembersRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Canonical full desired set of member emails. The server diffs against
	// current Casbin g-rules and only operates on the symmetric difference.
	Members       []string `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupMembersRequest) Reset() {
	*x = UpdateGroupMembersRequest{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupMembersRequest) ProtoMessage() {}

func (x *UpdateGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGroupMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateGroupMembersRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type UpdateGroupMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupMembersResponse) Reset() {
	*x = UpdateGroupMembersResponse{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupMembersResponse) ProtoMessage() {}

func (x *UpdateGroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupMembersResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupMembersResponse) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGroupMembersResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateGroupPermissionsRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Canonical full desired set of permissions. The server diffs against
	// current Casbin p-rules and only operates on the symmetric difference.
	Permissions   []*v1.PermissionAssignment `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupPermissionsRequest) Reset() {
	*x = UpdateGroupPermissionsRequest{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupPermissionsRequest) ProtoMessage() {}

func (x *UpdateGroupPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupPermissionsRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGroupPermissionsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateGroupPermissionsRequest) GetPermissions() []*v1.PermissionAssignment {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UpdateGroupPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupPermissionsResponse) Reset() {
	*x = UpdateGroupPermissionsResponse{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupPermissionsResponse) ProtoMessage() {}

func (x *UpdateGroupPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupPermissionsResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateGroupPermissionsResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{11}
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListGroupsRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListGroupsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_elara_group_v1_group_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_group_v1_group_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_elara_group_v1_group_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListGroupsResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_elara_group_v1_group_service_proto protoreflect.FileDescriptor

const file_elara_group_v1_group_service_proto_rawDesc = "" +
	"\n" +
	"\"elara/group/v1/group_service.proto\x12\x0eelara.group.v1\x1a\x1celara/common/v1/common.proto\x1a elara/common/v1/permission.proto\x1a\x1aelara/group/v1/group.proto\"(\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"B\n" +
	"\x13CreateGroupResponse\x12+\n" +
	"\x05group\x18\x01 \x01(\v2\x15.elara.group.v1.GroupR\x05group\"!\n" +
	"\x0fGetGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x10GetGroupResponse\x12+\n" +
	"\x05group\x18\x01 \x01(\v2\x15.elara.group.v1.GroupR\x05group\"t\n" +
	"\x12UpdateGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"B\n" +
	"\x13UpdateGroupResponse\x12+\n" +
	"\x05group\x18\x01 \x01(\v2\x15.elara.group.v1.GroupR\x05group\"P\n" +
	"\x19UpdateGroupMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers\"I\n" +
	"\x1aUpdateGroupMembersResponse\x12+\n" +
	"\x05group\x18\x01 \x01(\v2\x15.elara.group.v1.GroupR\x05group\"\x83\x01\n" +
	"\x1dUpdateGroupPermissionsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12G\n" +
	"\vpermissions\x18\x02 \x03(\v2%.elara.common.v1.PermissionAssignmentR\vpermissions\"M\n" +
	"\x1eUpdateGroupPermissionsResponse\x12+\n" +
	"\x05group\x18\x01 \x01(\v2\x15.elara.group.v1.GroupR\x05group\"$\n" +
	"\x12DeleteGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteGroupResponse\"o\n" +
	"\x11ListGroupsRequest\x12B\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\".elara.common.v1.PaginationRequestR\n" +
	"pagination\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\"\x88\x01\n" +
	"\x12ListGroupsResponse\x12-\n" +
	"\x06groups\x18\x01 \x03(\v2\x15.elara.group.v1.GroupR\x06groups\x12C\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2#.elara.common.v1.PaginationResponseR\n" +
	"pagination2\xa0\x05\n" +
	"\fGroupService\x12V\n" +
	"\vCreateGroup\x12\".elara.group.v1.CreateGroupRequest\x1a#.elara.group.v1.CreateGroupResponse\x12M\n" +
	"\bGetGroup\x12\x1f.elara.group.v1.GetGroupRequest\x1a .elara.group.v1.GetGroupResponse\x12V\n" +
	"\vUpdateGroup\x12\".elara.group.v1.UpdateGroupRequest\x1a#.elara.group.v1.UpdateGroupResponse\x12k\n" +
	"\x12UpdateGroupMembers\x12).elara.group.v1.UpdateGroupMembersRequest\x1a*.elara.group.v1.UpdateGroupMembersResponse\x12w\n" +
	"\x16UpdateGroupPermissions\x12-.elara.group.v1.UpdateGroupPermissionsRequest\x1a..elara.group.v1.UpdateGroupPermissionsResponse\x12V\n" +
	"\vDeleteGroup\x12\".elara.group.v1.DeleteGroupRequest\x1a#.elara.group.v1.DeleteGroupResponse\x12S\n" +
	"\n" +
	"ListGroups\x12!.elara.group.v1.ListGroupsRequest\x1a\".elara.group.v1.ListGroupsResponseB\xc9\x01\n" +
	"\x12com.elara.group.v1B\x11GroupServiceProtoP\x01ZFgithub.com/sergeyslonimsky/elara/internal/proto/elara/group/v1;groupv1\xa2\x02\x03EGX\xaa\x02\x0eElara.Group.V1\xca\x02\x0eElara\\Group\\V1\xe2\x02\x1aElara\\Group\\V1\\GPBMetadata\xea\x02\x10Elara::Group::V1b\x06proto3"

var (
	file_elara_group_v1_group_service_proto_rawDescOnce sync.Once
	file_elara_group_v1_group_service_proto_rawDescData []byte
)

func file_elara_group_v1_group_service_proto_rawDescGZIP() []byte {
	file_elara_group_v1_group_service_proto_rawDescOnce.Do(func() {
		file_elara_group_v1_group_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_group_v1_group_service_proto_rawDesc), len(file_elara_group_v1_group_service_proto_rawDesc)))
	})
	return file_elara_group_v1_group_service_proto_rawDescData
}

var file_elara_group_v1_group_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_elara_group_v1_group_service_proto_goTypes = []any{
	(*CreateGroupRequest)(nil),             // 0: elara.group.v1.CreateGroupRequest
	(*CreateGroupResponse)(nil),            // 1: elara.group.v1.CreateGroupResponse
	(*GetGroupRequest)(nil),                // 2: elara.group.v1.GetGroupRequest
	(*GetGroupResponse)(nil),               // 3: elara.group.v1.GetGroupResponse
	(*UpdateGroupRequest)(nil),             // 4: elara.group.v1.UpdateGroupRequest
	(*UpdateGroupResponse)(nil),            // 5: elara.group.v1.UpdateGroupResponse
	(*UpdateGroupMembersRequest)(nil),      // 6: elara.group.v1.UpdateGroupMembersRequest
	(*UpdateGroupMembersResponse)(nil),     // 7: elara.group.v1.UpdateGroupMembersResponse
	(*UpdateGroupPermissionsRequest)(nil),  // 8: elara.group.v1.UpdateGroupPermissionsRequest
	(*UpdateGroupPermissionsResponse)(nil), // 9: elara.group.v1.UpdateGroupPermissionsResponse
	(*DeleteGroupRequest)(nil),             // 10: elara.group.v1.DeleteGroupRequest
	(*DeleteGroupResponse)(nil),            // 11: elara.group.v1.DeleteGroupResponse
	(*ListGroupsRequest)(nil),              // 12: elara.group.v1.ListGroupsRequest
	(*ListGroupsResponse)(nil),             // 13: elara.group.v1.ListGroupsResponse
	(*Group)(nil),                          // 14: elara.group.v1.Group
	(*v1.PermissionAssignment)(nil),        // 15: elara.common.v1.PermissionAssignment
	(*v1.PaginationRequest)(nil),           // 16: elara.common.v1.PaginationRequest
	(*v1.PaginationResponse)(nil),          // 17: elara.common.v1.PaginationResponse
}
var file_elara_group_v1_group_service_proto_depIdxs = []int32{
	14, // 0: elara.group.v1.CreateGroupResponse.group:type_name -> elara.group.v1.Group
	14, // 1: elara.group.v1.GetGroupResponse.group:type_name -> elara.group.v1.Group
	14, // 2: elara.group.v1.UpdateGroupResponse.group:type_name -> elara.group.v1.Group
	14, // 3: elara.group.v1.UpdateGroupMembersResponse.group:type_name -> elara.group.v1.Group
	15, // 4: elara.group.v1.UpdateGroupPermissionsRequest.permissions:type_name -> elara.common.v1.PermissionAssignment
	14, // 5: elara.group.v1.UpdateGroupPermissionsResponse.group:type_name -> elara.group.v1.Group
	16, // 6: elara.group.v1.ListGroupsRequest.pagination:type_name -> elara.common.v1.PaginationRequest
	14, // 7: elara.group.v1.ListGroupsResponse.groups:type_name -> elara.group.v1.Group
	17, // 8: elara.group.v1.ListGroupsResponse.pagination:type_name -> elara.common.v1.PaginationResponse
	0,  // 9: elara.group.v1.GroupService.CreateGroup:input_type -> elara.group.v1.CreateGroupRequest
	2,  // 10: elara.group.v1.GroupService.GetGroup:input_type -> elara.group.v1.GetGroupRequest
	4,  // 11: elara.group.v1.GroupService.UpdateGroup:input_type -> elara.group.v1.UpdateGroupRequest
	6,  // 12: elara.group.v1.GroupService.UpdateGroupMembers:input_type -> elara.group.v1.UpdateGroupMembersRequest
	8,  // 13: elara.group.v1.GroupService.UpdateGroupPermissions:input_type -> elara.group.v1.UpdateGroupPermissionsRequest
	10, // 14: elara.group.v1.GroupService.DeleteGroup:input_type -> elara.group.v1.DeleteGroupRequest
	12, // 15: elara.group.v1.GroupService.ListGroups:input_type -> elara.group.v1.ListGroupsRequest
	1,  // 16: elara.group.v1.GroupService.CreateGroup:output_type -> elara.group.v1.CreateGroupResponse
	3,  // 17: elara.group.v1.GroupService.GetGroup:output_type -> elara.group.v1.GetGroupResponse
	5,  // 18: elara.group.v1.GroupService.UpdateGroup:output_type -> elara.group.v1.UpdateGroupResponse
	7,  // 19: elara.group.v1.GroupService.UpdateGroupMembers:output_type -> elara.group.v1.UpdateGroupMembersResponse
	9,  // 20: elara.group.v1.GroupService.UpdateGroupPermissions:output_type -> elara.group.v1.UpdateGroupPermissionsResponse
	11, // 21: elara.group.v1.GroupService.DeleteGroup:output_type -> elara.group.v1.DeleteGroupResponse
	13, // 22: elara.group.v1.GroupService.ListGroups:output_type -> elara.group.v1.ListGroupsResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_elara_group_v1_group_service_proto_init() }
func file_elara_group_v1_group_service_proto_init() {
	if File_elara_group_v1_group_service_proto != nil {
		return
	}
	file_elara_group_v1_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_group_v1_group_service_proto_rawDesc), len(file_elara_group_v1_group_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elara_group_v1_group_service_proto_goTypes,
		DependencyIndexes: file_elara_group_v1_group_service_proto_depIdxs,
		MessageInfos:      file_elara_group_v1_group_service_proto_msgTypes,
	}.Build()
	File_elara_group_v1_group_service_proto = out.File
	file_elara_group_v1_group_service_proto_goTypes = nil
	file_elara_group_v1_group_service_proto_depIdxs = nil
}
