// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/transfer (interfaces: exportAllConfigLister,exportAllNSLister)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_export_all.go -package=transfer_mock . exportAllConfigLister,exportAllNSLister
//

// Package transfer_mock is a generated GoMock package.
package transfer_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockexportAllConfigLister is a mock of exportAllConfigLister interface.
type MockexportAllConfigLister struct {
	ctrl     *gomock.Controller
	recorder *MockexportAllConfigListerMockRecorder
	isgomock struct{}
}

// MockexportAllConfigListerMockRecorder is the mock recorder for MockexportAllConfigLister.
type MockexportAllConfigListerMockRecorder struct {
	mock *MockexportAllConfigLister
}

// NewMockexportAllConfigLister creates a new mock instance.
func NewMockexportAllConfigLister(ctrl *gomock.Controller) *MockexportAllConfigLister {
	mock := &MockexportAllConfigLister{ctrl: ctrl}
	mock.recorder = &MockexportAllConfigListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexportAllConfigLister) EXPECT() *MockexportAllConfigListerMockRecorder {
	return m.recorder
}

// ListAllByNamespace mocks base method.
func (m *MockexportAllConfigLister) ListAllByNamespace(ctx context.Context, namespace string) ([]*domain.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllByNamespace", ctx, namespace)
	ret0, _ := ret[0].([]*domain.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllByNamespace indicates an expected call of ListAllByNamespace.
func (mr *MockexportAllConfigListerMockRecorder) ListAllByNamespace(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllByNamespace", reflect.TypeOf((*MockexportAllConfigLister)(nil).ListAllByNamespace), ctx, namespace)
}

// MockexportAllNSLister is a mock of exportAllNSLister interface.
type MockexportAllNSLister struct {
	ctrl     *gomock.Controller
	recorder *MockexportAllNSListerMockRecorder
	isgomock struct{}
}

// MockexportAllNSListerMockRecorder is the mock recorder for MockexportAllNSLister.
type MockexportAllNSListerMockRecorder struct {
	mock *MockexportAllNSLister
}

// NewMockexportAllNSLister creates a new mock instance.
func NewMockexportAllNSLister(ctrl *gomock.Controller) *MockexportAllNSLister {
	mock := &MockexportAllNSLister{ctrl: ctrl}
	mock.recorder = &MockexportAllNSListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexportAllNSLister) EXPECT() *MockexportAllNSListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockexportAllNSLister) List(ctx context.Context) ([]*domain.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockexportAllNSListerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockexportAllNSLister)(nil).List), ctx)
}
