// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mock.go -package=transfer_mock -source=service.go
//

// Package transfer_mock is a generated GoMock package.
package transfer_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// Mockpdp is a mock of pdp interface.
type Mockpdp struct {
	ctrl     *gomock.Controller
	recorder *MockpdpMockRecorder
	isgomock struct{}
}

// MockpdpMockRecorder is the mock recorder for Mockpdp.
type MockpdpMockRecorder struct {
	mock *Mockpdp
}

// NewMockpdp creates a new mock instance.
func NewMockpdp(ctrl *gomock.Controller) *Mockpdp {
	mock := &Mockpdp{ctrl: ctrl}
	mock.recorder = &MockpdpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockpdp) EXPECT() *MockpdpMockRecorder {
	return m.recorder
}

// Has mocks base method.
func (m *Mockpdp) Has(principal string, perm domain.Permission) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", principal, perm)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Has indicates an expected call of Has.
func (mr *MockpdpMockRecorder) Has(principal, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*Mockpdp)(nil).Has), principal, perm)
}

// Mockconfigs is a mock of configs interface.
type Mockconfigs struct {
	ctrl     *gomock.Controller
	recorder *MockconfigsMockRecorder
	isgomock struct{}
}

// MockconfigsMockRecorder is the mock recorder for Mockconfigs.
type MockconfigsMockRecorder struct {
	mock *Mockconfigs
}

// NewMockconfigs creates a new mock instance.
func NewMockconfigs(ctrl *gomock.Controller) *Mockconfigs {
	mock := &Mockconfigs{ctrl: ctrl}
	mock.recorder = &MockconfigsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockconfigs) EXPECT() *MockconfigsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockconfigs) Create(ctx context.Context, cfg *domain.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockconfigsMockRecorder) Create(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockconfigs)(nil).Create), ctx, cfg)
}

// Get mocks base method.
func (m *Mockconfigs) Get(ctx context.Context, path, namespace string) (*domain.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, path, namespace)
	ret0, _ := ret[0].(*domain.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockconfigsMockRecorder) Get(ctx, path, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockconfigs)(nil).Get), ctx, path, namespace)
}

// ListAllByNamespace mocks base method.
func (m *Mockconfigs) ListAllByNamespace(ctx context.Context, namespace string) ([]*domain.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllByNamespace", ctx, namespace)
	ret0, _ := ret[0].([]*domain.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllByNamespace indicates an expected call of ListAllByNamespace.
func (mr *MockconfigsMockRecorder) ListAllByNamespace(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllByNamespace", reflect.TypeOf((*Mockconfigs)(nil).ListAllByNamespace), ctx, namespace)
}

// Update mocks base method.
func (m *Mockconfigs) Update(ctx context.Context, cfg *domain.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockconfigsMockRecorder) Update(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mockconfigs)(nil).Update), ctx, cfg)
}

// Mocknamespaces is a mock of namespaces interface.
type Mocknamespaces struct {
	ctrl     *gomock.Controller
	recorder *MocknamespacesMockRecorder
	isgomock struct{}
}

// MocknamespacesMockRecorder is the mock recorder for Mocknamespaces.
type MocknamespacesMockRecorder struct {
	mock *Mocknamespaces
}

// NewMocknamespaces creates a new mock instance.
func NewMocknamespaces(ctrl *gomock.Controller) *Mocknamespaces {
	mock := &Mocknamespaces{ctrl: ctrl}
	mock.recorder = &MocknamespacesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocknamespaces) EXPECT() *MocknamespacesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mocknamespaces) Create(ctx context.Context, ns *domain.Namespace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ns)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MocknamespacesMockRecorder) Create(ctx, ns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mocknamespaces)(nil).Create), ctx, ns)
}

// Get mocks base method.
func (m *Mocknamespaces) Get(ctx context.Context, name string) (*domain.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(*domain.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MocknamespacesMockRecorder) Get(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mocknamespaces)(nil).Get), ctx, name)
}

// ListAll mocks base method.
func (m *Mocknamespaces) ListAll(ctx context.Context) ([]*domain.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]*domain.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MocknamespacesMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*Mocknamespaces)(nil).ListAll), ctx)
}
