// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mock.go -package=user_mock -source=service.go
//

// Package user_mock is a generated GoMock package.
package user_mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserReader is a mock of UserReader interface.
type MockUserReader struct {
	ctrl     *gomock.Controller
	recorder *MockUserReaderMockRecorder
	isgomock struct{}
}

// MockUserReaderMockRecorder is the mock recorder for MockUserReader.
type MockUserReaderMockRecorder struct {
	mock *MockUserReader
}

// NewMockUserReader creates a new mock instance.
func NewMockUserReader(ctrl *gomock.Controller) *MockUserReader {
	mock := &MockUserReader{ctrl: ctrl}
	mock.recorder = &MockUserReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserReader) EXPECT() *MockUserReaderMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserReader) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserReaderMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserReader)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockUserReader) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserReader)(nil).GetByID), ctx, id)
}

// GetByIdentity mocks base method.
func (m *MockUserReader) GetByIdentity(ctx context.Context, provider, subject string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdentity", ctx, provider, subject)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdentity indicates an expected call of GetByIdentity.
func (mr *MockUserReaderMockRecorder) GetByIdentity(ctx, provider, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdentity", reflect.TypeOf((*MockUserReader)(nil).GetByIdentity), ctx, provider, subject)
}

// List mocks base method.
func (m *MockUserReader) List(ctx context.Context, filter domain.UserFilter, params domain.UserListParams) ([]*domain.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, params)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserReaderMockRecorder) List(ctx, filter, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserReader)(nil).List), ctx, filter, params)
}

// SetMembershipVersion mocks base method.
func (m *MockUserReader) SetMembershipVersion(ctx context.Context, userID uuid.UUID, version int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMembershipVersion", ctx, userID, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMembershipVersion indicates an expected call of SetMembershipVersion.
func (mr *MockUserReaderMockRecorder) SetMembershipVersion(ctx, userID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMembershipVersion", reflect.TypeOf((*MockUserReader)(nil).SetMembershipVersion), ctx, userID, version)
}

// SetPassword mocks base method.
func (m *MockUserReader) SetPassword(ctx context.Context, userID uuid.UUID, hash string, changeRequired bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPassword", ctx, userID, hash, changeRequired)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPassword indicates an expected call of SetPassword.
func (mr *MockUserReaderMockRecorder) SetPassword(ctx, userID, hash, changeRequired any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPassword", reflect.TypeOf((*MockUserReader)(nil).SetPassword), ctx, userID, hash, changeRequired)
}

// MockUserManager is a mock of UserManager interface.
type MockUserManager struct {
	ctrl     *gomock.Controller
	recorder *MockUserManagerMockRecorder
	isgomock struct{}
}

// MockUserManagerMockRecorder is the mock recorder for MockUserManager.
type MockUserManagerMockRecorder struct {
	mock *MockUserManager
}

// NewMockUserManager creates a new mock instance.
func NewMockUserManager(ctrl *gomock.Controller) *MockUserManager {
	mock := &MockUserManager{ctrl: ctrl}
	mock.recorder = &MockUserManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserManager) EXPECT() *MockUserManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserManager) Create(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserManagerMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserManager)(nil).Create), ctx, user)
}

// Deactivate mocks base method.
func (m *MockUserManager) Deactivate(ctx context.Context, userID uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockUserManagerMockRecorder) Deactivate(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockUserManager)(nil).Deactivate), ctx, userID)
}

// Reactivate mocks base method.
func (m *MockUserManager) Reactivate(ctx context.Context, userID uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reactivate", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reactivate indicates an expected call of Reactivate.
func (mr *MockUserManagerMockRecorder) Reactivate(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reactivate", reflect.TypeOf((*MockUserManager)(nil).Reactivate), ctx, userID)
}

// MocksessionsService is a mock of sessionsService interface.
type MocksessionsService struct {
	ctrl     *gomock.Controller
	recorder *MocksessionsServiceMockRecorder
	isgomock struct{}
}

// MocksessionsServiceMockRecorder is the mock recorder for MocksessionsService.
type MocksessionsServiceMockRecorder struct {
	mock *MocksessionsService
}

// NewMocksessionsService creates a new mock instance.
func NewMocksessionsService(ctrl *gomock.Controller) *MocksessionsService {
	mock := &MocksessionsService{ctrl: ctrl}
	mock.recorder = &MocksessionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionsService) EXPECT() *MocksessionsServiceMockRecorder {
	return m.recorder
}

// RevokeAllForUser mocks base method.
func (m *MocksessionsService) RevokeAllForUser(ctx context.Context, userID, revokedBy, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", ctx, userID, revokedBy, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MocksessionsServiceMockRecorder) RevokeAllForUser(ctx, userID, revokedBy, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MocksessionsService)(nil).RevokeAllForUser), ctx, userID, revokedBy, reason)
}
