// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/access/v1/group_service.proto

package accessv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupResponse) Reset() {
	*x = UpdateGroupResponse{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupResponse) ProtoMessage() {}

func (x *UpdateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{7}
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{8}
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{10}
}

func (x *AddMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AddMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{11}
}

func (x *AddMemberResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RemoveMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_elara_access_v1_group_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_group_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_group_service_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveMemberResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

var File_elara_access_v1_group_service_proto protoreflect.FileDescriptor

const file_elara_access_v1_group_service_proto_rawDesc = "" +
	"\n" +
	"#elara/access/v1/group_service.proto\x12\x0felara.access.v1\x1a\x1belara/access/v1/group.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"C\n" +
	"\x13CreateGroupResponse\x12,\n" +
	"\x05group\x18\x01 \x01(\v2\x16.elara.access.v1.GroupR\x05group\"!\n" +
	"\x0fGetGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x10GetGroupResponse\x12,\n" +
	"\x05group\x18\x01 \x01(\v2\x16.elara.access.v1.GroupR\x05group\"8\n" +
	"\x12UpdateGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"C\n" +
	"\x13UpdateGroupResponse\x12,\n" +
	"\x05group\x18\x01 \x01(\v2\x16.elara.access.v1.GroupR\x05group\"$\n" +
	"\x12DeleteGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteGroupResponse\"\x13\n" +
	"\x11ListGroupsRequest\"D\n" +
	"\x12ListGroupsResponse\x12.\n" +
	"\x06groups\x18\x01 \x03(\v2\x16.elara.access.v1.GroupR\x06groups\"C\n" +
	"\x10AddMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"A\n" +
	"\x11AddMemberResponse\x12,\n" +
	"\x05group\x18\x01 \x01(\v2\x16.elara.access.v1.GroupR\x05group\"F\n" +
	"\x13RemoveMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"D\n" +
	"\x14RemoveMemberResponse\x12,\n" +
	"\x05group\x18\x01 \x01(\v2\x16.elara.access.v1.GroupR\x05group2\xf5\x04\n" +
	"\fGroupService\x12X\n" +
	"\vCreateGroup\x12#.elara.access.v1.CreateGroupRequest\x1a$.elara.access.v1.CreateGroupResponse\x12O\n" +
	"\bGetGroup\x12 .elara.access.v1.GetGroupRequest\x1a!.elara.access.v1.GetGroupResponse\x12X\n" +
	"\vUpdateGroup\x12#.elara.access.v1.UpdateGroupRequest\x1a$.elara.access.v1.UpdateGroupResponse\x12X\n" +
	"\vDeleteGroup\x12#.elara.access.v1.DeleteGroupRequest\x1a$.elara.access.v1.DeleteGroupResponse\x12U\n" +
	"\n" +
	"ListGroups\x12\".elara.access.v1.ListGroupsRequest\x1a#.elara.access.v1.ListGroupsResponse\x12R\n" +
	"\tAddMember\x12!.elara.access.v1.AddMemberRequest\x1a\".elara.access.v1.AddMemberResponse\x12[\n" +
	"\fRemoveMember\x12$.elara.access.v1.RemoveMemberRequest\x1a%.elara.access.v1.RemoveMemberResponseB\xd0\x01\n" +
	"\x13com.elara.access.v1B\x11GroupServiceProtoP\x01ZHgithub.com/sergeyslonimsky/elara/internal/proto/elara/access/v1;accessv1\xa2\x02\x03EAX\xaa\x02\x0fElara.Access.V1\xca\x02\x0fElara\\Access\\V1\xe2\x02\x1bElara\\Access\\V1\\GPBMetadata\xea\x02\x11Elara::Access::V1b\x06proto3"

var (
	file_elara_access_v1_group_service_proto_rawDescOnce sync.Once
	file_elara_access_v1_group_service_proto_rawDescData []byte
)

func file_elara_access_v1_group_service_proto_rawDescGZIP() []byte {
	file_elara_access_v1_group_service_proto_rawDescOnce.Do(func() {
		file_elara_access_v1_group_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_access_v1_group_service_proto_rawDesc), len(file_elara_access_v1_group_service_proto_rawDesc)))
	})
	return file_elara_access_v1_group_service_proto_rawDescData
}

var file_elara_access_v1_group_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_elara_access_v1_group_service_proto_goTypes = []any{
	(*CreateGroupRequest)(nil),   // 0: elara.access.v1.CreateGroupRequest
	(*CreateGroupResponse)(nil),  // 1: elara.access.v1.CreateGroupResponse
	(*GetGroupRequest)(nil),      // 2: elara.access.v1.GetGroupRequest
	(*GetGroupResponse)(nil),     // 3: elara.access.v1.GetGroupResponse
	(*UpdateGroupRequest)(nil),   // 4: elara.access.v1.UpdateGroupRequest
	(*UpdateGroupResponse)(nil),  // 5: elara.access.v1.UpdateGroupResponse
	(*DeleteGroupRequest)(nil),   // 6: elara.access.v1.DeleteGroupRequest
	(*DeleteGroupResponse)(nil),  // 7: elara.access.v1.DeleteGroupResponse
	(*ListGroupsRequest)(nil),    // 8: elara.access.v1.ListGroupsRequest
	(*ListGroupsResponse)(nil),   // 9: elara.access.v1.ListGroupsResponse
	(*AddMemberRequest)(nil),     // 10: elara.access.v1.AddMemberRequest
	(*AddMemberResponse)(nil),    // 11: elara.access.v1.AddMemberResponse
	(*RemoveMemberRequest)(nil),  // 12: elara.access.v1.RemoveMemberRequest
	(*RemoveMemberResponse)(nil), // 13: elara.access.v1.RemoveMemberResponse
	(*Group)(nil),                // 14: elara.access.v1.Group
}
var file_elara_access_v1_group_service_proto_depIdxs = []int32{
	14, // 0: elara.access.v1.CreateGroupResponse.group:type_name -> elara.access.v1.Group
	14, // 1: elara.access.v1.GetGroupResponse.group:type_name -> elara.access.v1.Group
	14, // 2: elara.access.v1.UpdateGroupResponse.group:type_name -> elara.access.v1.Group
	14, // 3: elara.access.v1.ListGroupsResponse.groups:type_name -> elara.access.v1.Group
	14, // 4: elara.access.v1.AddMemberResponse.group:type_name -> elara.access.v1.Group
	14, // 5: elara.access.v1.RemoveMemberResponse.group:type_name -> elara.access.v1.Group
	0,  // 6: elara.access.v1.GroupService.CreateGroup:input_type -> elara.access.v1.CreateGroupRequest
	2,  // 7: elara.access.v1.GroupService.GetGroup:input_type -> elara.access.v1.GetGroupRequest
	4,  // 8: elara.access.v1.GroupService.UpdateGroup:input_type -> elara.access.v1.UpdateGroupRequest
	6,  // 9: elara.access.v1.GroupService.DeleteGroup:input_type -> elara.access.v1.DeleteGroupRequest
	8,  // 10: elara.access.v1.GroupService.ListGroups:input_type -> elara.access.v1.ListGroupsRequest
	10, // 11: elara.access.v1.GroupService.AddMember:input_type -> elara.access.v1.AddMemberRequest
	12, // 12: elara.access.v1.GroupService.RemoveMember:input_type -> elara.access.v1.RemoveMemberRequest
	1,  // 13: elara.access.v1.GroupService.CreateGroup:output_type -> elara.access.v1.CreateGroupResponse
	3,  // 14: elara.access.v1.GroupService.GetGroup:output_type -> elara.access.v1.GetGroupResponse
	5,  // 15: elara.access.v1.GroupService.UpdateGroup:output_type -> elara.access.v1.UpdateGroupResponse
	7,  // 16: elara.access.v1.GroupService.DeleteGroup:output_type -> elara.access.v1.DeleteGroupResponse
	9,  // 17: elara.access.v1.GroupService.ListGroups:output_type -> elara.access.v1.ListGroupsResponse
	11, // 18: elara.access.v1.GroupService.AddMember:output_type -> elara.access.v1.AddMemberResponse
	13, // 19: elara.access.v1.GroupService.RemoveMember:output_type -> elara.access.v1.RemoveMemberResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_elara_access_v1_group_service_proto_init() }
func file_elara_access_v1_group_service_proto_init() {
	if File_elara_access_v1_group_service_proto != nil {
		return
	}
	file_elara_access_v1_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_access_v1_group_service_proto_rawDesc), len(file_elara_access_v1_group_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elara_access_v1_group_service_proto_goTypes,
		DependencyIndexes: file_elara_access_v1_group_service_proto_depIdxs,
		MessageInfos:      file_elara_access_v1_group_service_proto_msgTypes,
	}.Build()
	File_elara_access_v1_group_service_proto = out.File
	file_elara_access_v1_group_service_proto_goTypes = nil
	file_elara_access_v1_group_service_proto_depIdxs = nil
}
