// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/access/v1/policy.proto

package accessv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	mi := &file_elara_access_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_elara_access_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_elara_access_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyRule) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PolicyRule) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PolicyRule) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_elara_access_v1_policy_proto protoreflect.FileDescriptor

const file_elara_access_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x1celara/access/v1/policy.proto\x12\x0felara.access.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\n" +
	"PolicyRule\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04roleB\xca\x01\n" +
	"\x13com.elara.access.v1B\vPolicyProtoP\x01ZHgithub.com/sergeyslonimsky/elara/internal/proto/elara/access/v1;accessv1\xa2\x02\x03EAX\xaa\x02\x0fElara.Access.V1\xca\x02\x0fElara\\Access\\V1\xe2\x02\x1bElara\\Access\\V1\\GPBMetadata\xea\x02\x11Elara::Access::V1b\x06proto3"

var (
	file_elara_access_v1_policy_proto_rawDescOnce sync.Once
	file_elara_access_v1_policy_proto_rawDescData []byte
)

func file_elara_access_v1_policy_proto_rawDescGZIP() []byte {
	file_elara_access_v1_policy_proto_rawDescOnce.Do(func() {
		file_elara_access_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_access_v1_policy_proto_rawDesc), len(file_elara_access_v1_policy_proto_rawDesc)))
	})
	return file_elara_access_v1_policy_proto_rawDescData
}

var file_elara_access_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_elara_access_v1_policy_proto_goTypes = []any{
	(*PolicyRule)(nil), // 0: elara.access.v1.PolicyRule
}
var file_elara_access_v1_policy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_elara_access_v1_policy_proto_init() }
func file_elara_access_v1_policy_proto_init() {
	if File_elara_access_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_access_v1_policy_proto_rawDesc), len(file_elara_access_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_elara_access_v1_policy_proto_goTypes,
		DependencyIndexes: file_elara_access_v1_policy_proto_depIdxs,
		MessageInfos:      file_elara_access_v1_policy_proto_msgTypes,
	}.Build()
	File_elara_access_v1_policy_proto = out.File
	file_elara_access_v1_policy_proto_goTypes = nil
	file_elara_access_v1_policy_proto_depIdxs = nil
}
