// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/handler_mock.go -package=user_mock -source=handler.go
//

// Package user_mock is a generated GoMock package.
package user_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	user "github.com/sergeyslonimsky/elara/internal/usecase/user"
)

// Mockusecase is a mock of usecase interface.
type Mockusecase struct {
	ctrl     *gomock.Controller
	recorder *MockusecaseMockRecorder
	isgomock struct{}
}

// MockusecaseMockRecorder is the mock recorder for Mockusecase.
type MockusecaseMockRecorder struct {
	mock *Mockusecase
}

// NewMockusecase creates a new mock instance.
func NewMockusecase(ctrl *gomock.Controller) *Mockusecase {
	mock := &Mockusecase{ctrl: ctrl}
	mock.recorder = &MockusecaseMockRecorder{mock}

	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockusecase) EXPECT() *MockusecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockusecase) Create(
	ctx context.Context,
	actor domain.AuthInfo,
	data user.CreateData,
) (*user.CreateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, actor, data)
	ret0, _ := ret[0].(*user.CreateResult)
	ret1, _ := ret[1].(error)

	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockusecaseMockRecorder) Create(ctx, actor, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"Create",
		reflect.TypeOf((*Mockusecase)(nil).Create),
		ctx,
		actor,
		data,
	)
}

// Delete mocks base method.
func (m *Mockusecase) Delete(ctx context.Context, actor domain.AuthInfo, targetEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, actor, targetEmail)
	ret0, _ := ret[0].(error)

	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockusecaseMockRecorder) Delete(ctx, actor, targetEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"Delete",
		reflect.TypeOf((*Mockusecase)(nil).Delete),
		ctx,
		actor,
		targetEmail,
	)
}

// Get mocks base method.
func (m *Mockusecase) Get(ctx context.Context, actor domain.AuthInfo, email string) (*user.GetResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, actor, email)
	ret0, _ := ret[0].(*user.GetResult)
	ret1, _ := ret[1].(error)

	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockusecaseMockRecorder) Get(ctx, actor, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"Get",
		reflect.TypeOf((*Mockusecase)(nil).Get),
		ctx,
		actor,
		email,
	)
}

// List mocks base method.
func (m *Mockusecase) List(
	ctx context.Context,
	actor domain.AuthInfo,
	params user.ListParams,
) (*user.ListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, actor, params)
	ret0, _ := ret[0].(*user.ListResult)
	ret1, _ := ret[1].(error)

	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockusecaseMockRecorder) List(ctx, actor, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"List",
		reflect.TypeOf((*Mockusecase)(nil).List),
		ctx,
		actor,
		params,
	)
}

// ResetPassword mocks base method.
func (m *Mockusecase) ResetPassword(ctx context.Context, actor domain.AuthInfo, targetEmail, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, actor, targetEmail, newPassword)
	ret0, _ := ret[0].(error)

	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockusecaseMockRecorder) ResetPassword(ctx, actor, targetEmail, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"ResetPassword",
		reflect.TypeOf((*Mockusecase)(nil).ResetPassword),
		ctx,
		actor,
		targetEmail,
		newPassword,
	)
}

// UpdateGroups mocks base method.
func (m *Mockusecase) UpdateGroups(
	ctx context.Context,
	actor domain.AuthInfo,
	data user.UpdateGroupsData,
) (*user.UpdateGroupsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroups", ctx, actor, data)
	ret0, _ := ret[0].(*user.UpdateGroupsResult)
	ret1, _ := ret[1].(error)

	return ret0, ret1
}

// UpdateGroups indicates an expected call of UpdateGroups.
func (mr *MockusecaseMockRecorder) UpdateGroups(ctx, actor, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"UpdateGroups",
		reflect.TypeOf((*Mockusecase)(nil).UpdateGroups),
		ctx,
		actor,
		data,
	)
}
