// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/auth/v1/auth_service.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_auth_service_proto_rawDescGZIP(), []int{0}
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectUrl   string                 `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type CallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackRequest) Reset() {
	*x = CallbackRequest{}
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRequest) ProtoMessage() {}

func (x *CallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRequest.ProtoReflect.Descriptor instead.
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *CallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type CallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackResponse) Reset() {
	*x = CallbackResponse{}
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackResponse) ProtoMessage() {}

func (x *CallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackResponse.ProtoReflect.Descriptor instead.
func (*CallbackResponse) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_auth_service_proto_rawDescGZIP(), []int{3}
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_auth_service_proto_rawDescGZIP(), []int{4}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_auth_service_proto_rawDescGZIP(), []int{5}
}

type MeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeRequest) Reset() {
	*x = MeRequest{}
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeRequest) ProtoMessage() {}

func (x *MeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeRequest.ProtoReflect.Descriptor instead.
func (*MeRequest) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_auth_service_proto_rawDescGZIP(), []int{6}
}

type NamespaceAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CanWrite      bool                   `protobuf:"varint,2,opt,name=can_write,json=canWrite,proto3" json:"can_write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceAccess) Reset() {
	*x = NamespaceAccess{}
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceAccess) ProtoMessage() {}

func (x *NamespaceAccess) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceAccess.ProtoReflect.Descriptor instead.
func (*NamespaceAccess) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_auth_service_proto_rawDescGZIP(), []int{7}
}

func (x *NamespaceAccess) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamespaceAccess) GetCanWrite() bool {
	if x != nil {
		return x.CanWrite
	}
	return false
}

type MeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Email             string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Picture           string                 `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	IsAdmin           bool                   `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Namespaces        []*NamespaceAccess     `protobuf:"bytes,5,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	CanViewWebhooks   bool                   `protobuf:"varint,6,opt,name=can_view_webhooks,json=canViewWebhooks,proto3" json:"can_view_webhooks,omitempty"`
	CanManageWebhooks bool                   `protobuf:"varint,7,opt,name=can_manage_webhooks,json=canManageWebhooks,proto3" json:"can_manage_webhooks,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MeResponse) Reset() {
	*x = MeResponse{}
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeResponse) ProtoMessage() {}

func (x *MeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_auth_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeResponse.ProtoReflect.Descriptor instead.
func (*MeResponse) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_auth_service_proto_rawDescGZIP(), []int{8}
}

func (x *MeResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MeResponse) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *MeResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *MeResponse) GetNamespaces() []*NamespaceAccess {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *MeResponse) GetCanViewWebhooks() bool {
	if x != nil {
		return x.CanViewWebhooks
	}
	return false
}

func (x *MeResponse) GetCanManageWebhooks() bool {
	if x != nil {
		return x.CanManageWebhooks
	}
	return false
}

var File_elara_auth_v1_auth_service_proto protoreflect.FileDescriptor

const file_elara_auth_v1_auth_service_proto_rawDesc = "" +
	"\n" +
	" elara/auth/v1/auth_service.proto\x12\relara.auth.v1\"\x0e\n" +
	"\fLoginRequest\"2\n" +
	"\rLoginResponse\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl\";\n" +
	"\x0fCallbackRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\x12\n" +
	"\x10CallbackResponse\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\"\v\n" +
	"\tMeRequest\"B\n" +
	"\x0fNamespaceAccess\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tcan_write\x18\x02 \x01(\bR\bcanWrite\"\x87\x02\n" +
	"\n" +
	"MeResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\apicture\x18\x03 \x01(\tR\apicture\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdmin\x12>\n" +
	"\n" +
	"namespaces\x18\x05 \x03(\v2\x1e.elara.auth.v1.NamespaceAccessR\n" +
	"namespaces\x12*\n" +
	"\x11can_view_webhooks\x18\x06 \x01(\bR\x0fcanViewWebhooks\x12.\n" +
	"\x13can_manage_webhooks\x18\a \x01(\bR\x11canManageWebhooks2\xa0\x02\n" +
	"\vAuthService\x12B\n" +
	"\x05Login\x12\x1b.elara.auth.v1.LoginRequest\x1a\x1c.elara.auth.v1.LoginResponse\x12K\n" +
	"\bCallback\x12\x1e.elara.auth.v1.CallbackRequest\x1a\x1f.elara.auth.v1.CallbackResponse\x12E\n" +
	"\x06Logout\x12\x1c.elara.auth.v1.LogoutRequest\x1a\x1d.elara.auth.v1.LogoutResponse\x129\n" +
	"\x02Me\x12\x18.elara.auth.v1.MeRequest\x1a\x19.elara.auth.v1.MeResponseB\xc1\x01\n" +
	"\x11com.elara.auth.v1B\x10AuthServiceProtoP\x01ZDgithub.com/sergeyslonimsky/elara/internal/proto/elara/auth/v1;authv1\xa2\x02\x03EAX\xaa\x02\rElara.Auth.V1\xca\x02\rElara\\Auth\\V1\xe2\x02\x19Elara\\Auth\\V1\\GPBMetadata\xea\x02\x0fElara::Auth::V1b\x06proto3"

var (
	file_elara_auth_v1_auth_service_proto_rawDescOnce sync.Once
	file_elara_auth_v1_auth_service_proto_rawDescData []byte
)

func file_elara_auth_v1_auth_service_proto_rawDescGZIP() []byte {
	file_elara_auth_v1_auth_service_proto_rawDescOnce.Do(func() {
		file_elara_auth_v1_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_auth_v1_auth_service_proto_rawDesc), len(file_elara_auth_v1_auth_service_proto_rawDesc)))
	})
	return file_elara_auth_v1_auth_service_proto_rawDescData
}

var file_elara_auth_v1_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_elara_auth_v1_auth_service_proto_goTypes = []any{
	(*LoginRequest)(nil),     // 0: elara.auth.v1.LoginRequest
	(*LoginResponse)(nil),    // 1: elara.auth.v1.LoginResponse
	(*CallbackRequest)(nil),  // 2: elara.auth.v1.CallbackRequest
	(*CallbackResponse)(nil), // 3: elara.auth.v1.CallbackResponse
	(*LogoutRequest)(nil),    // 4: elara.auth.v1.LogoutRequest
	(*LogoutResponse)(nil),   // 5: elara.auth.v1.LogoutResponse
	(*MeRequest)(nil),        // 6: elara.auth.v1.MeRequest
	(*NamespaceAccess)(nil),  // 7: elara.auth.v1.NamespaceAccess
	(*MeResponse)(nil),       // 8: elara.auth.v1.MeResponse
}
var file_elara_auth_v1_auth_service_proto_depIdxs = []int32{
	7, // 0: elara.auth.v1.MeResponse.namespaces:type_name -> elara.auth.v1.NamespaceAccess
	0, // 1: elara.auth.v1.AuthService.Login:input_type -> elara.auth.v1.LoginRequest
	2, // 2: elara.auth.v1.AuthService.Callback:input_type -> elara.auth.v1.CallbackRequest
	4, // 3: elara.auth.v1.AuthService.Logout:input_type -> elara.auth.v1.LogoutRequest
	6, // 4: elara.auth.v1.AuthService.Me:input_type -> elara.auth.v1.MeRequest
	1, // 5: elara.auth.v1.AuthService.Login:output_type -> elara.auth.v1.LoginResponse
	3, // 6: elara.auth.v1.AuthService.Callback:output_type -> elara.auth.v1.CallbackResponse
	5, // 7: elara.auth.v1.AuthService.Logout:output_type -> elara.auth.v1.LogoutResponse
	8, // 8: elara.auth.v1.AuthService.Me:output_type -> elara.auth.v1.MeResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_elara_auth_v1_auth_service_proto_init() }
func file_elara_auth_v1_auth_service_proto_init() {
	if File_elara_auth_v1_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_auth_v1_auth_service_proto_rawDesc), len(file_elara_auth_v1_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elara_auth_v1_auth_service_proto_goTypes,
		DependencyIndexes: file_elara_auth_v1_auth_service_proto_depIdxs,
		MessageInfos:      file_elara_auth_v1_auth_service_proto_msgTypes,
	}.Build()
	File_elara_auth_v1_auth_service_proto = out.File
	file_elara_auth_v1_auth_service_proto_goTypes = nil
	file_elara_auth_v1_auth_service_proto_depIdxs = nil
}
