// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthType int32

const (
	AuthType_AUTH_TYPE_UNSPECIFIED AuthType = 0
	AuthType_AUTH_TYPE_OIDC        AuthType = 1
	AuthType_AUTH_TYPE_BASIC       AuthType = 2
	AuthType_AUTH_TYPE_NONE        AuthType = 3
)

// Enum value maps for AuthType.
var (
	AuthType_name = map[int32]string{
		0: "AUTH_TYPE_UNSPECIFIED",
		1: "AUTH_TYPE_OIDC",
		2: "AUTH_TYPE_BASIC",
		3: "AUTH_TYPE_NONE",
	}
	AuthType_value = map[string]int32{
		"AUTH_TYPE_UNSPECIFIED": 0,
		"AUTH_TYPE_OIDC":        1,
		"AUTH_TYPE_BASIC":       2,
		"AUTH_TYPE_NONE":        3,
	}
)

func (x AuthType) Enum() *AuthType {
	p := new(AuthType)
	*p = x
	return p
}

func (x AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_elara_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (AuthType) Type() protoreflect.EnumType {
	return &file_elara_auth_v1_auth_proto_enumTypes[0]
}

func (x AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthType.Descriptor instead.
func (AuthType) EnumDescriptor() ([]byte, []int) {
	return file_elara_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

var File_elara_auth_v1_auth_proto protoreflect.FileDescriptor

const file_elara_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18elara/auth/v1/auth.proto\x12\relara.auth.v1*b\n" +
	"\bAuthType\x12\x19\n" +
	"\x15AUTH_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eAUTH_TYPE_OIDC\x10\x01\x12\x13\n" +
	"\x0fAUTH_TYPE_BASIC\x10\x02\x12\x12\n" +
	"\x0eAUTH_TYPE_NONE\x10\x03B\xba\x01\n" +
	"\x11com.elara.auth.v1B\tAuthProtoP\x01ZDgithub.com/sergeyslonimsky/elara/internal/proto/elara/auth/v1;authv1\xa2\x02\x03EAX\xaa\x02\rElara.Auth.V1\xca\x02\rElara\\Auth\\V1\xe2\x02\x19Elara\\Auth\\V1\\GPBMetadata\xea\x02\x0fElara::Auth::V1b\x06proto3"

var (
	file_elara_auth_v1_auth_proto_rawDescOnce sync.Once
	file_elara_auth_v1_auth_proto_rawDescData []byte
)

func file_elara_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_elara_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_elara_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_auth_v1_auth_proto_rawDesc), len(file_elara_auth_v1_auth_proto_rawDesc)))
	})
	return file_elara_auth_v1_auth_proto_rawDescData
}

var file_elara_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_elara_auth_v1_auth_proto_goTypes = []any{
	(AuthType)(0), // 0: elara.auth.v1.AuthType
}
var file_elara_auth_v1_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_elara_auth_v1_auth_proto_init() }
func file_elara_auth_v1_auth_proto_init() {
	if File_elara_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_auth_v1_auth_proto_rawDesc), len(file_elara_auth_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_elara_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_elara_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_elara_auth_v1_auth_proto_enumTypes,
	}.Build()
	File_elara_auth_v1_auth_proto = out.File
	file_elara_auth_v1_auth_proto_goTypes = nil
	file_elara_auth_v1_auth_proto_depIdxs = nil
}
