// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/auth/v1/token_service.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PAT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Namespaces    []string               `protobuf:"bytes,4,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	LastUsedIp    string                 `protobuf:"bytes,7,opt,name=last_used_ip,json=lastUsedIp,proto3" json:"last_used_ip,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PAT) Reset() {
	*x = PAT{}
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PAT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAT) ProtoMessage() {}

func (x *PAT) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAT.ProtoReflect.Descriptor instead.
func (*PAT) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_token_service_proto_rawDescGZIP(), []int{0}
}

func (x *PAT) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PAT) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PAT) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *PAT) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *PAT) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *PAT) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *PAT) GetLastUsedIp() string {
	if x != nil {
		return x.LastUsedIp
	}
	return ""
}

func (x *PAT) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespaces    []string               `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_token_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTokenRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *CreateTokenRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *PAT                   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RawToken      string                 `protobuf:"bytes,2,opt,name=raw_token,json=rawToken,proto3" json:"raw_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_token_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTokenResponse) GetToken() *PAT {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CreateTokenResponse) GetRawToken() string {
	if x != nil {
		return x.RawToken
	}
	return ""
}

type ListTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_token_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListTokensRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*PAT                 `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_token_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListTokensResponse) GetTokens() []*PAT {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_token_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *PAT                   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_token_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTokenResponse) GetToken() *PAT {
	if x != nil {
		return x.Token
	}
	return nil
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_token_service_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_auth_v1_token_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_elara_auth_v1_token_service_proto_rawDescGZIP(), []int{8}
}

var File_elara_auth_v1_token_service_proto protoreflect.FileDescriptor

const file_elara_auth_v1_token_service_proto_rawDesc = "" +
	"\n" +
	"!elara/auth/v1/token_service.proto\x12\relara.auth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x02\n" +
	"\x03PAT\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tR\tuserEmail\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x04 \x03(\tR\n" +
	"namespaces\x12>\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01\x12A\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"lastUsedAt\x88\x01\x01\x12 \n" +
	"\flast_used_ip\x18\a \x01(\tR\n" +
	"lastUsedIp\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\r\n" +
	"\v_expires_atB\x0f\n" +
	"\r_last_used_at\"\x97\x01\n" +
	"\x12CreateTokenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\tR\n" +
	"namespaces\x12>\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01B\r\n" +
	"\v_expires_at\"\\\n" +
	"\x13CreateTokenResponse\x12(\n" +
	"\x05token\x18\x01 \x01(\v2\x12.elara.auth.v1.PATR\x05token\x12\x1b\n" +
	"\traw_token\x18\x02 \x01(\tR\brawToken\"2\n" +
	"\x11ListTokensRequest\x12\x1d\n" +
	"\n" +
	"user_email\x18\x01 \x01(\tR\tuserEmail\"@\n" +
	"\x12ListTokensResponse\x12*\n" +
	"\x06tokens\x18\x01 \x03(\v2\x12.elara.auth.v1.PATR\x06tokens\"!\n" +
	"\x0fGetTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x10GetTokenResponse\x12(\n" +
	"\x05token\x18\x01 \x01(\v2\x12.elara.auth.v1.PATR\x05token\"$\n" +
	"\x12RevokeTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13RevokeTokenResponse2\xda\x02\n" +
	"\fTokenService\x12T\n" +
	"\vCreateToken\x12!.elara.auth.v1.CreateTokenRequest\x1a\".elara.auth.v1.CreateTokenResponse\x12Q\n" +
	"\n" +
	"ListTokens\x12 .elara.auth.v1.ListTokensRequest\x1a!.elara.auth.v1.ListTokensResponse\x12K\n" +
	"\bGetToken\x12\x1e.elara.auth.v1.GetTokenRequest\x1a\x1f.elara.auth.v1.GetTokenResponse\x12T\n" +
	"\vRevokeToken\x12!.elara.auth.v1.RevokeTokenRequest\x1a\".elara.auth.v1.RevokeTokenResponseB\xc2\x01\n" +
	"\x11com.elara.auth.v1B\x11TokenServiceProtoP\x01ZDgithub.com/sergeyslonimsky/elara/internal/proto/elara/auth/v1;authv1\xa2\x02\x03EAX\xaa\x02\rElara.Auth.V1\xca\x02\rElara\\Auth\\V1\xe2\x02\x19Elara\\Auth\\V1\\GPBMetadata\xea\x02\x0fElara::Auth::V1b\x06proto3"

var (
	file_elara_auth_v1_token_service_proto_rawDescOnce sync.Once
	file_elara_auth_v1_token_service_proto_rawDescData []byte
)

func file_elara_auth_v1_token_service_proto_rawDescGZIP() []byte {
	file_elara_auth_v1_token_service_proto_rawDescOnce.Do(func() {
		file_elara_auth_v1_token_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_auth_v1_token_service_proto_rawDesc), len(file_elara_auth_v1_token_service_proto_rawDesc)))
	})
	return file_elara_auth_v1_token_service_proto_rawDescData
}

var file_elara_auth_v1_token_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_elara_auth_v1_token_service_proto_goTypes = []any{
	(*PAT)(nil),                   // 0: elara.auth.v1.PAT
	(*CreateTokenRequest)(nil),    // 1: elara.auth.v1.CreateTokenRequest
	(*CreateTokenResponse)(nil),   // 2: elara.auth.v1.CreateTokenResponse
	(*ListTokensRequest)(nil),     // 3: elara.auth.v1.ListTokensRequest
	(*ListTokensResponse)(nil),    // 4: elara.auth.v1.ListTokensResponse
	(*GetTokenRequest)(nil),       // 5: elara.auth.v1.GetTokenRequest
	(*GetTokenResponse)(nil),      // 6: elara.auth.v1.GetTokenResponse
	(*RevokeTokenRequest)(nil),    // 7: elara.auth.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),   // 8: elara.auth.v1.RevokeTokenResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_elara_auth_v1_token_service_proto_depIdxs = []int32{
	9,  // 0: elara.auth.v1.PAT.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 1: elara.auth.v1.PAT.last_used_at:type_name -> google.protobuf.Timestamp
	9,  // 2: elara.auth.v1.PAT.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: elara.auth.v1.CreateTokenRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 4: elara.auth.v1.CreateTokenResponse.token:type_name -> elara.auth.v1.PAT
	0,  // 5: elara.auth.v1.ListTokensResponse.tokens:type_name -> elara.auth.v1.PAT
	0,  // 6: elara.auth.v1.GetTokenResponse.token:type_name -> elara.auth.v1.PAT
	1,  // 7: elara.auth.v1.TokenService.CreateToken:input_type -> elara.auth.v1.CreateTokenRequest
	3,  // 8: elara.auth.v1.TokenService.ListTokens:input_type -> elara.auth.v1.ListTokensRequest
	5,  // 9: elara.auth.v1.TokenService.GetToken:input_type -> elara.auth.v1.GetTokenRequest
	7,  // 10: elara.auth.v1.TokenService.RevokeToken:input_type -> elara.auth.v1.RevokeTokenRequest
	2,  // 11: elara.auth.v1.TokenService.CreateToken:output_type -> elara.auth.v1.CreateTokenResponse
	4,  // 12: elara.auth.v1.TokenService.ListTokens:output_type -> elara.auth.v1.ListTokensResponse
	6,  // 13: elara.auth.v1.TokenService.GetToken:output_type -> elara.auth.v1.GetTokenResponse
	8,  // 14: elara.auth.v1.TokenService.RevokeToken:output_type -> elara.auth.v1.RevokeTokenResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_elara_auth_v1_token_service_proto_init() }
func file_elara_auth_v1_token_service_proto_init() {
	if File_elara_auth_v1_token_service_proto != nil {
		return
	}
	file_elara_auth_v1_token_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_elara_auth_v1_token_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_auth_v1_token_service_proto_rawDesc), len(file_elara_auth_v1_token_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elara_auth_v1_token_service_proto_goTypes,
		DependencyIndexes: file_elara_auth_v1_token_service_proto_depIdxs,
		MessageInfos:      file_elara_auth_v1_token_service_proto_msgTypes,
	}.Build()
	File_elara_auth_v1_token_service_proto = out.File
	file_elara_auth_v1_token_service_proto_goTypes = nil
	file_elara_auth_v1_token_service_proto_depIdxs = nil
}
