// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/config (interfaces: lockEnforcer,LockStore,LockNotifier)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_lock.go -package=config_mock . lockEnforcer,LockStore,LockNotifier
//

// Package config_mock is a generated GoMock package.
package config_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocklockEnforcer is a mock of lockEnforcer interface.
type MocklockEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MocklockEnforcerMockRecorder
	isgomock struct{}
}

// MocklockEnforcerMockRecorder is the mock recorder for MocklockEnforcer.
type MocklockEnforcerMockRecorder struct {
	mock *MocklockEnforcer
}

// NewMocklockEnforcer creates a new mock instance.
func NewMocklockEnforcer(ctrl *gomock.Controller) *MocklockEnforcer {
	mock := &MocklockEnforcer{ctrl: ctrl}
	mock.recorder = &MocklockEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklockEnforcer) EXPECT() *MocklockEnforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MocklockEnforcer) Enforce(subject, arg1, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, arg1, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MocklockEnforcerMockRecorder) Enforce(subject, arg1, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MocklockEnforcer)(nil).Enforce), subject, arg1, object, action)
}

// MockLockStore is a mock of LockStore interface.
type MockLockStore struct {
	ctrl     *gomock.Controller
	recorder *MockLockStoreMockRecorder
	isgomock struct{}
}

// MockLockStoreMockRecorder is the mock recorder for MockLockStore.
type MockLockStoreMockRecorder struct {
	mock *MockLockStore
}

// NewMockLockStore creates a new mock instance.
func NewMockLockStore(ctrl *gomock.Controller) *MockLockStore {
	mock := &MockLockStore{ctrl: ctrl}
	mock.recorder = &MockLockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockStore) EXPECT() *MockLockStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLockStore) Get(ctx context.Context, path, namespace string) (*domain.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, path, namespace)
	ret0, _ := ret[0].(*domain.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLockStoreMockRecorder) Get(ctx, path, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLockStore)(nil).Get), ctx, path, namespace)
}

// LockConfig mocks base method.
func (m *MockLockStore) LockConfig(ctx context.Context, namespace, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockConfig", ctx, namespace, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockConfig indicates an expected call of LockConfig.
func (mr *MockLockStoreMockRecorder) LockConfig(ctx, namespace, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockConfig", reflect.TypeOf((*MockLockStore)(nil).LockConfig), ctx, namespace, path)
}

// MockLockNotifier is a mock of LockNotifier interface.
type MockLockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockLockNotifierMockRecorder
	isgomock struct{}
}

// MockLockNotifierMockRecorder is the mock recorder for MockLockNotifier.
type MockLockNotifierMockRecorder struct {
	mock *MockLockNotifier
}

// NewMockLockNotifier creates a new mock instance.
func NewMockLockNotifier(ctrl *gomock.Controller) *MockLockNotifier {
	mock := &MockLockNotifier{ctrl: ctrl}
	mock.recorder = &MockLockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockNotifier) EXPECT() *MockLockNotifierMockRecorder {
	return m.recorder
}

// NotifyConfigLocked mocks base method.
func (m *MockLockNotifier) NotifyConfigLocked(ctx context.Context, cfg *domain.Config) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyConfigLocked", ctx, cfg)
}

// NotifyConfigLocked indicates an expected call of NotifyConfigLocked.
func (mr *MockLockNotifierMockRecorder) NotifyConfigLocked(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyConfigLocked", reflect.TypeOf((*MockLockNotifier)(nil).NotifyConfigLocked), ctx, cfg)
}
