// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/config (interfaces: historyEnforcer,configHistoryReader)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_history.go -package=config_mock . historyEnforcer,configHistoryReader
//

// Package config_mock is a generated GoMock package.
package config_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockhistoryEnforcer is a mock of historyEnforcer interface.
type MockhistoryEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockhistoryEnforcerMockRecorder
	isgomock struct{}
}

// MockhistoryEnforcerMockRecorder is the mock recorder for MockhistoryEnforcer.
type MockhistoryEnforcerMockRecorder struct {
	mock *MockhistoryEnforcer
}

// NewMockhistoryEnforcer creates a new mock instance.
func NewMockhistoryEnforcer(ctrl *gomock.Controller) *MockhistoryEnforcer {
	mock := &MockhistoryEnforcer{ctrl: ctrl}
	mock.recorder = &MockhistoryEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhistoryEnforcer) EXPECT() *MockhistoryEnforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockhistoryEnforcer) Enforce(subject, arg1, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, arg1, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockhistoryEnforcerMockRecorder) Enforce(subject, arg1, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockhistoryEnforcer)(nil).Enforce), subject, arg1, object, action)
}

// MockconfigHistoryReader is a mock of configHistoryReader interface.
type MockconfigHistoryReader struct {
	ctrl     *gomock.Controller
	recorder *MockconfigHistoryReaderMockRecorder
	isgomock struct{}
}

// MockconfigHistoryReaderMockRecorder is the mock recorder for MockconfigHistoryReader.
type MockconfigHistoryReaderMockRecorder struct {
	mock *MockconfigHistoryReader
}

// NewMockconfigHistoryReader creates a new mock instance.
func NewMockconfigHistoryReader(ctrl *gomock.Controller) *MockconfigHistoryReader {
	mock := &MockconfigHistoryReader{ctrl: ctrl}
	mock.recorder = &MockconfigHistoryReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigHistoryReader) EXPECT() *MockconfigHistoryReaderMockRecorder {
	return m.recorder
}

// GetAtRevision mocks base method.
func (m *MockconfigHistoryReader) GetAtRevision(ctx context.Context, path, namespace string, revision int64) (*domain.HistoryEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAtRevision", ctx, path, namespace, revision)
	ret0, _ := ret[0].(*domain.HistoryEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAtRevision indicates an expected call of GetAtRevision.
func (mr *MockconfigHistoryReaderMockRecorder) GetAtRevision(ctx, path, namespace, revision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAtRevision", reflect.TypeOf((*MockconfigHistoryReader)(nil).GetAtRevision), ctx, path, namespace, revision)
}

// GetConfigHistory mocks base method.
func (m *MockconfigHistoryReader) GetConfigHistory(ctx context.Context, path, namespace string, limit int) ([]*domain.HistoryEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigHistory", ctx, path, namespace, limit)
	ret0, _ := ret[0].([]*domain.HistoryEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigHistory indicates an expected call of GetConfigHistory.
func (mr *MockconfigHistoryReaderMockRecorder) GetConfigHistory(ctx, path, namespace, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigHistory", reflect.TypeOf((*MockconfigHistoryReader)(nil).GetConfigHistory), ctx, path, namespace, limit)
}
