// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/config (interfaces: getEnforcer,configGetter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_get.go -package=config_mock . getEnforcer,configGetter
//

// Package config_mock is a generated GoMock package.
package config_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockgetEnforcer is a mock of getEnforcer interface.
type MockgetEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockgetEnforcerMockRecorder
	isgomock struct{}
}

// MockgetEnforcerMockRecorder is the mock recorder for MockgetEnforcer.
type MockgetEnforcerMockRecorder struct {
	mock *MockgetEnforcer
}

// NewMockgetEnforcer creates a new mock instance.
func NewMockgetEnforcer(ctrl *gomock.Controller) *MockgetEnforcer {
	mock := &MockgetEnforcer{ctrl: ctrl}
	mock.recorder = &MockgetEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgetEnforcer) EXPECT() *MockgetEnforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockgetEnforcer) Enforce(subject, arg1, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, arg1, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockgetEnforcerMockRecorder) Enforce(subject, arg1, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockgetEnforcer)(nil).Enforce), subject, arg1, object, action)
}

// MockconfigGetter is a mock of configGetter interface.
type MockconfigGetter struct {
	ctrl     *gomock.Controller
	recorder *MockconfigGetterMockRecorder
	isgomock struct{}
}

// MockconfigGetterMockRecorder is the mock recorder for MockconfigGetter.
type MockconfigGetterMockRecorder struct {
	mock *MockconfigGetter
}

// NewMockconfigGetter creates a new mock instance.
func NewMockconfigGetter(ctrl *gomock.Controller) *MockconfigGetter {
	mock := &MockconfigGetter{ctrl: ctrl}
	mock.recorder = &MockconfigGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigGetter) EXPECT() *MockconfigGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockconfigGetter) Get(ctx context.Context, path, namespace string) (*domain.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, path, namespace)
	ret0, _ := ret[0].(*domain.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockconfigGetterMockRecorder) Get(ctx, path, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockconfigGetter)(nil).Get), ctx, path, namespace)
}
