// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/config (interfaces: updateEnforcer,configUpdater,updateConfigGetter,updateWatchNotifier,updateNSTimestampUpdater,updateSchemaValidator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_update.go -package=config_mock . updateEnforcer,configUpdater,updateConfigGetter,updateWatchNotifier,updateNSTimestampUpdater,updateSchemaValidator
//

// Package config_mock is a generated GoMock package.
package config_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockupdateEnforcer is a mock of updateEnforcer interface.
type MockupdateEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockupdateEnforcerMockRecorder
	isgomock struct{}
}

// MockupdateEnforcerMockRecorder is the mock recorder for MockupdateEnforcer.
type MockupdateEnforcerMockRecorder struct {
	mock *MockupdateEnforcer
}

// NewMockupdateEnforcer creates a new mock instance.
func NewMockupdateEnforcer(ctrl *gomock.Controller) *MockupdateEnforcer {
	mock := &MockupdateEnforcer{ctrl: ctrl}
	mock.recorder = &MockupdateEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockupdateEnforcer) EXPECT() *MockupdateEnforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockupdateEnforcer) Enforce(subject, arg1, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, arg1, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockupdateEnforcerMockRecorder) Enforce(subject, arg1, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockupdateEnforcer)(nil).Enforce), subject, arg1, object, action)
}

// MockconfigUpdater is a mock of configUpdater interface.
type MockconfigUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockconfigUpdaterMockRecorder
	isgomock struct{}
}

// MockconfigUpdaterMockRecorder is the mock recorder for MockconfigUpdater.
type MockconfigUpdaterMockRecorder struct {
	mock *MockconfigUpdater
}

// NewMockconfigUpdater creates a new mock instance.
func NewMockconfigUpdater(ctrl *gomock.Controller) *MockconfigUpdater {
	mock := &MockconfigUpdater{ctrl: ctrl}
	mock.recorder = &MockconfigUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigUpdater) EXPECT() *MockconfigUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockconfigUpdater) Update(ctx context.Context, cfg *domain.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockconfigUpdaterMockRecorder) Update(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockconfigUpdater)(nil).Update), ctx, cfg)
}

// MockupdateConfigGetter is a mock of updateConfigGetter interface.
type MockupdateConfigGetter struct {
	ctrl     *gomock.Controller
	recorder *MockupdateConfigGetterMockRecorder
	isgomock struct{}
}

// MockupdateConfigGetterMockRecorder is the mock recorder for MockupdateConfigGetter.
type MockupdateConfigGetterMockRecorder struct {
	mock *MockupdateConfigGetter
}

// NewMockupdateConfigGetter creates a new mock instance.
func NewMockupdateConfigGetter(ctrl *gomock.Controller) *MockupdateConfigGetter {
	mock := &MockupdateConfigGetter{ctrl: ctrl}
	mock.recorder = &MockupdateConfigGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockupdateConfigGetter) EXPECT() *MockupdateConfigGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockupdateConfigGetter) Get(ctx context.Context, path, namespace string) (*domain.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, path, namespace)
	ret0, _ := ret[0].(*domain.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockupdateConfigGetterMockRecorder) Get(ctx, path, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockupdateConfigGetter)(nil).Get), ctx, path, namespace)
}

// MockupdateWatchNotifier is a mock of updateWatchNotifier interface.
type MockupdateWatchNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockupdateWatchNotifierMockRecorder
	isgomock struct{}
}

// MockupdateWatchNotifierMockRecorder is the mock recorder for MockupdateWatchNotifier.
type MockupdateWatchNotifierMockRecorder struct {
	mock *MockupdateWatchNotifier
}

// NewMockupdateWatchNotifier creates a new mock instance.
func NewMockupdateWatchNotifier(ctrl *gomock.Controller) *MockupdateWatchNotifier {
	mock := &MockupdateWatchNotifier{ctrl: ctrl}
	mock.recorder = &MockupdateWatchNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockupdateWatchNotifier) EXPECT() *MockupdateWatchNotifierMockRecorder {
	return m.recorder
}

// NotifyUpdated mocks base method.
func (m *MockupdateWatchNotifier) NotifyUpdated(ctx context.Context, cfg *domain.Config) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyUpdated", ctx, cfg)
}

// NotifyUpdated indicates an expected call of NotifyUpdated.
func (mr *MockupdateWatchNotifierMockRecorder) NotifyUpdated(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyUpdated", reflect.TypeOf((*MockupdateWatchNotifier)(nil).NotifyUpdated), ctx, cfg)
}

// MockupdateNSTimestampUpdater is a mock of updateNSTimestampUpdater interface.
type MockupdateNSTimestampUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockupdateNSTimestampUpdaterMockRecorder
	isgomock struct{}
}

// MockupdateNSTimestampUpdaterMockRecorder is the mock recorder for MockupdateNSTimestampUpdater.
type MockupdateNSTimestampUpdaterMockRecorder struct {
	mock *MockupdateNSTimestampUpdater
}

// NewMockupdateNSTimestampUpdater creates a new mock instance.
func NewMockupdateNSTimestampUpdater(ctrl *gomock.Controller) *MockupdateNSTimestampUpdater {
	mock := &MockupdateNSTimestampUpdater{ctrl: ctrl}
	mock.recorder = &MockupdateNSTimestampUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockupdateNSTimestampUpdater) EXPECT() *MockupdateNSTimestampUpdaterMockRecorder {
	return m.recorder
}

// UpdateTimestamp mocks base method.
func (m *MockupdateNSTimestampUpdater) UpdateTimestamp(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTimestamp", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTimestamp indicates an expected call of UpdateTimestamp.
func (mr *MockupdateNSTimestampUpdaterMockRecorder) UpdateTimestamp(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTimestamp", reflect.TypeOf((*MockupdateNSTimestampUpdater)(nil).UpdateTimestamp), ctx, name)
}

// MockupdateSchemaValidator is a mock of updateSchemaValidator interface.
type MockupdateSchemaValidator struct {
	ctrl     *gomock.Controller
	recorder *MockupdateSchemaValidatorMockRecorder
	isgomock struct{}
}

// MockupdateSchemaValidatorMockRecorder is the mock recorder for MockupdateSchemaValidator.
type MockupdateSchemaValidatorMockRecorder struct {
	mock *MockupdateSchemaValidator
}

// NewMockupdateSchemaValidator creates a new mock instance.
func NewMockupdateSchemaValidator(ctrl *gomock.Controller) *MockupdateSchemaValidator {
	mock := &MockupdateSchemaValidator{ctrl: ctrl}
	mock.recorder = &MockupdateSchemaValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockupdateSchemaValidator) EXPECT() *MockupdateSchemaValidatorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockupdateSchemaValidator) Execute(ctx context.Context, namespace, configPath, content string, format domain.Format) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, namespace, configPath, content, format)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockupdateSchemaValidatorMockRecorder) Execute(ctx, namespace, configPath, content, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockupdateSchemaValidator)(nil).Execute), ctx, namespace, configPath, content, format)
}
