// Code generated by MockGen. DO NOT EDIT.
// Source: schema_handler.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/schema_handler_mock.go -package=config_mock -source=schema_handler.go
//

// Package config_mock is a generated GoMock package.
package config_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	schema "github.com/sergeyslonimsky/elara/internal/usecase/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockschemaAuthz is a mock of schemaAuthz interface.
type MockschemaAuthz struct {
	ctrl     *gomock.Controller
	recorder *MockschemaAuthzMockRecorder
	isgomock struct{}
}

// MockschemaAuthzMockRecorder is the mock recorder for MockschemaAuthz.
type MockschemaAuthzMockRecorder struct {
	mock *MockschemaAuthz
}

// NewMockschemaAuthz creates a new mock instance.
func NewMockschemaAuthz(ctrl *gomock.Controller) *MockschemaAuthz {
	mock := &MockschemaAuthz{ctrl: ctrl}
	mock.recorder = &MockschemaAuthzMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockschemaAuthz) EXPECT() *MockschemaAuthzMockRecorder {
	return m.recorder
}

// Require mocks base method.
func (m *MockschemaAuthz) Require(ctx context.Context, object domain.Object, action domain.Action, domainStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Require", ctx, object, action, domainStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Require indicates an expected call of Require.
func (mr *MockschemaAuthzMockRecorder) Require(ctx, object, action, domainStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Require", reflect.TypeOf((*MockschemaAuthz)(nil).Require), ctx, object, action, domainStr)
}

// RequireGroup mocks base method.
func (m *MockschemaAuthz) RequireGroup(ctx context.Context, action domain.Action, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireGroup", ctx, action, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequireGroup indicates an expected call of RequireGroup.
func (mr *MockschemaAuthzMockRecorder) RequireGroup(ctx, action, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireGroup", reflect.TypeOf((*MockschemaAuthz)(nil).RequireGroup), ctx, action, id)
}

// RequireNamespace mocks base method.
func (m *MockschemaAuthz) RequireNamespace(ctx context.Context, action domain.Action, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireNamespace", ctx, action, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequireNamespace indicates an expected call of RequireNamespace.
func (mr *MockschemaAuthzMockRecorder) RequireNamespace(ctx, action, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireNamespace", reflect.TypeOf((*MockschemaAuthz)(nil).RequireNamespace), ctx, action, name)
}

// MockschemaUsecase is a mock of schemaUsecase interface.
type MockschemaUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockschemaUsecaseMockRecorder
	isgomock struct{}
}

// MockschemaUsecaseMockRecorder is the mock recorder for MockschemaUsecase.
type MockschemaUsecaseMockRecorder struct {
	mock *MockschemaUsecase
}

// NewMockschemaUsecase creates a new mock instance.
func NewMockschemaUsecase(ctrl *gomock.Controller) *MockschemaUsecase {
	mock := &MockschemaUsecase{ctrl: ctrl}
	mock.recorder = &MockschemaUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockschemaUsecase) EXPECT() *MockschemaUsecaseMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockschemaUsecase) Attach(ctx context.Context, in schema.AttachInput) (*domain.SchemaAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, in)
	ret0, _ := ret[0].(*domain.SchemaAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attach indicates an expected call of Attach.
func (mr *MockschemaUsecaseMockRecorder) Attach(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockschemaUsecase)(nil).Attach), ctx, in)
}

// Detach mocks base method.
func (m *MockschemaUsecase) Detach(ctx context.Context, namespace, pathPattern string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detach", ctx, namespace, pathPattern)
	ret0, _ := ret[0].(error)
	return ret0
}

// Detach indicates an expected call of Detach.
func (mr *MockschemaUsecaseMockRecorder) Detach(ctx, namespace, pathPattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockschemaUsecase)(nil).Detach), ctx, namespace, pathPattern)
}

// Get mocks base method.
func (m *MockschemaUsecase) Get(ctx context.Context, namespace, pathPattern string) (*domain.SchemaAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, namespace, pathPattern)
	ret0, _ := ret[0].(*domain.SchemaAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockschemaUsecaseMockRecorder) Get(ctx, namespace, pathPattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockschemaUsecase)(nil).Get), ctx, namespace, pathPattern)
}

// GetEffective mocks base method.
func (m *MockschemaUsecase) GetEffective(ctx context.Context, namespace, path string) (*domain.SchemaAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffective", ctx, namespace, path)
	ret0, _ := ret[0].(*domain.SchemaAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEffective indicates an expected call of GetEffective.
func (mr *MockschemaUsecaseMockRecorder) GetEffective(ctx, namespace, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffective", reflect.TypeOf((*MockschemaUsecase)(nil).GetEffective), ctx, namespace, path)
}

// List mocks base method.
func (m *MockschemaUsecase) List(ctx context.Context, namespace string) ([]*domain.SchemaAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, namespace)
	ret0, _ := ret[0].([]*domain.SchemaAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockschemaUsecaseMockRecorder) List(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockschemaUsecase)(nil).List), ctx, namespace)
}
