{{- if and .Values.config.ui.auth.enabled (not .Values.config.ui.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elara.authSecretName" . }}
  labels:
    {{- include "elara.labels" . | nindent 4 }}
type: Opaque
stringData:
  UI_AUTH_SESSION_SECRET: {{ .Values.config.ui.auth.session.secret | quote }}
  {{- if eq .Values.config.ui.auth.type "basic-auth" }}
  UI_AUTH_BASICAUTH_PASSWORD: {{ .Values.config.ui.auth.basicAuth.password | quote }}
  {{- end }}
  {{- if eq .Values.config.ui.auth.type "oidc" }}
  UI_AUTH_OIDC_CLIENTSECRET: {{ .Values.config.ui.auth.oidc.clientSecret | quote }}
  {{- end }}
{{- end }}
