apiVersion: v1
kind: Service
metadata:
  name: {{ include "elara.fullname" . }}
  labels:
    {{- include "elara.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      appProtocol: http2
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      appProtocol: grpc
  selector:
    {{- include "elara.selectorLabels" . | nindent 4 }}
