// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/token/v1/token_service.proto

package tokenv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespaces    []string               `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_elara_token_v1_token_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_token_v1_token_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_elara_token_v1_token_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTokenRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *CreateTokenRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateTokenRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RawToken      string                 `protobuf:"bytes,2,opt,name=raw_token,json=rawToken,proto3" json:"raw_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	mi := &file_elara_token_v1_token_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_token_v1_token_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_elara_token_v1_token_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CreateTokenResponse) GetRawToken() string {
	if x != nil {
		return x.RawToken
	}
	return ""
}

type ListTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuedBy      string                 `protobuf:"bytes,1,opt,name=issued_by,json=issuedBy,proto3" json:"issued_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_elara_token_v1_token_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_token_v1_token_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_elara_token_v1_token_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListTokensRequest) GetIssuedBy() string {
	if x != nil {
		return x.IssuedBy
	}
	return ""
}

type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*Token               `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_elara_token_v1_token_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_token_v1_token_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_elara_token_v1_token_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListTokensResponse) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_elara_token_v1_token_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_token_v1_token_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_elara_token_v1_token_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_elara_token_v1_token_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_token_v1_token_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_elara_token_v1_token_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_elara_token_v1_token_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_token_v1_token_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_elara_token_v1_token_service_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_elara_token_v1_token_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_token_v1_token_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_elara_token_v1_token_service_proto_rawDescGZIP(), []int{7}
}

var File_elara_token_v1_token_service_proto protoreflect.FileDescriptor

const file_elara_token_v1_token_service_proto_rawDesc = "" +
	"\n" +
	"\"elara/token/v1/token_service.proto\x12\x0eelara.token.v1\x1a\x1aelara/token/v1/token.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n" +
	"\x12CreateTokenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\tR\n" +
	"namespaces\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12>\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01B\r\n" +
	"\v_expires_at\"_\n" +
	"\x13CreateTokenResponse\x12+\n" +
	"\x05token\x18\x01 \x01(\v2\x15.elara.token.v1.TokenR\x05token\x12\x1b\n" +
	"\traw_token\x18\x02 \x01(\tR\brawToken\"0\n" +
	"\x11ListTokensRequest\x12\x1b\n" +
	"\tissued_by\x18\x01 \x01(\tR\bissuedBy\"C\n" +
	"\x12ListTokensResponse\x12-\n" +
	"\x06tokens\x18\x01 \x03(\v2\x15.elara.token.v1.TokenR\x06tokens\"!\n" +
	"\x0fGetTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x10GetTokenResponse\x12+\n" +
	"\x05token\x18\x01 \x01(\v2\x15.elara.token.v1.TokenR\x05token\"$\n" +
	"\x12RevokeTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13RevokeTokenResponse2\xe2\x02\n" +
	"\fTokenService\x12V\n" +
	"\vCreateToken\x12\".elara.token.v1.CreateTokenRequest\x1a#.elara.token.v1.CreateTokenResponse\x12S\n" +
	"\n" +
	"ListTokens\x12!.elara.token.v1.ListTokensRequest\x1a\".elara.token.v1.ListTokensResponse\x12M\n" +
	"\bGetToken\x12\x1f.elara.token.v1.GetTokenRequest\x1a .elara.token.v1.GetTokenResponse\x12V\n" +
	"\vRevokeToken\x12\".elara.token.v1.RevokeTokenRequest\x1a#.elara.token.v1.RevokeTokenResponseB\xc9\x01\n" +
	"\x12com.elara.token.v1B\x11TokenServiceProtoP\x01ZFgithub.com/sergeyslonimsky/elara/internal/proto/elara/token/v1;tokenv1\xa2\x02\x03ETX\xaa\x02\x0eElara.Token.V1\xca\x02\x0eElara\\Token\\V1\xe2\x02\x1aElara\\Token\\V1\\GPBMetadata\xea\x02\x10Elara::Token::V1b\x06proto3"

var (
	file_elara_token_v1_token_service_proto_rawDescOnce sync.Once
	file_elara_token_v1_token_service_proto_rawDescData []byte
)

func file_elara_token_v1_token_service_proto_rawDescGZIP() []byte {
	file_elara_token_v1_token_service_proto_rawDescOnce.Do(func() {
		file_elara_token_v1_token_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_token_v1_token_service_proto_rawDesc), len(file_elara_token_v1_token_service_proto_rawDesc)))
	})
	return file_elara_token_v1_token_service_proto_rawDescData
}

var file_elara_token_v1_token_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_elara_token_v1_token_service_proto_goTypes = []any{
	(*CreateTokenRequest)(nil),    // 0: elara.token.v1.CreateTokenRequest
	(*CreateTokenResponse)(nil),   // 1: elara.token.v1.CreateTokenResponse
	(*ListTokensRequest)(nil),     // 2: elara.token.v1.ListTokensRequest
	(*ListTokensResponse)(nil),    // 3: elara.token.v1.ListTokensResponse
	(*GetTokenRequest)(nil),       // 4: elara.token.v1.GetTokenRequest
	(*GetTokenResponse)(nil),      // 5: elara.token.v1.GetTokenResponse
	(*RevokeTokenRequest)(nil),    // 6: elara.token.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),   // 7: elara.token.v1.RevokeTokenResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*Token)(nil),                 // 9: elara.token.v1.Token
}
var file_elara_token_v1_token_service_proto_depIdxs = []int32{
	8, // 0: elara.token.v1.CreateTokenRequest.expires_at:type_name -> google.protobuf.Timestamp
	9, // 1: elara.token.v1.CreateTokenResponse.token:type_name -> elara.token.v1.Token
	9, // 2: elara.token.v1.ListTokensResponse.tokens:type_name -> elara.token.v1.Token
	9, // 3: elara.token.v1.GetTokenResponse.token:type_name -> elara.token.v1.Token
	0, // 4: elara.token.v1.TokenService.CreateToken:input_type -> elara.token.v1.CreateTokenRequest
	2, // 5: elara.token.v1.TokenService.ListTokens:input_type -> elara.token.v1.ListTokensRequest
	4, // 6: elara.token.v1.TokenService.GetToken:input_type -> elara.token.v1.GetTokenRequest
	6, // 7: elara.token.v1.TokenService.RevokeToken:input_type -> elara.token.v1.RevokeTokenRequest
	1, // 8: elara.token.v1.TokenService.CreateToken:output_type -> elara.token.v1.CreateTokenResponse
	3, // 9: elara.token.v1.TokenService.ListTokens:output_type -> elara.token.v1.ListTokensResponse
	5, // 10: elara.token.v1.TokenService.GetToken:output_type -> elara.token.v1.GetTokenResponse
	7, // 11: elara.token.v1.TokenService.RevokeToken:output_type -> elara.token.v1.RevokeTokenResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_elara_token_v1_token_service_proto_init() }
func file_elara_token_v1_token_service_proto_init() {
	if File_elara_token_v1_token_service_proto != nil {
		return
	}
	file_elara_token_v1_token_proto_init()
	file_elara_token_v1_token_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_token_v1_token_service_proto_rawDesc), len(file_elara_token_v1_token_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elara_token_v1_token_service_proto_goTypes,
		DependencyIndexes: file_elara_token_v1_token_service_proto_depIdxs,
		MessageInfos:      file_elara_token_v1_token_service_proto_msgTypes,
	}.Build()
	File_elara_token_v1_token_service_proto = out.File
	file_elara_token_v1_token_service_proto_goTypes = nil
	file_elara_token_v1_token_service_proto_depIdxs = nil
}
