// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/namespace/v1/namespace_service.proto

package namespacev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/sergeyslonimsky/elara/internal/proto/elara/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceRequest) Reset() {
	*x = CreateNamespaceRequest{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceRequest) ProtoMessage() {}

func (x *CreateNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceRequest.ProtoReflect.Descriptor instead.
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNamespaceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceResponse) Reset() {
	*x = CreateNamespaceResponse{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceResponse) ProtoMessage() {}

func (x *CreateNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceResponse.ProtoReflect.Descriptor instead.
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNamespaceResponse) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

type GetNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceRequest) Reset() {
	*x = GetNamespaceRequest{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceRequest) ProtoMessage() {}

func (x *GetNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceRequest.ProtoReflect.Descriptor instead.
func (*GetNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceResponse) Reset() {
	*x = GetNamespaceResponse{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceResponse) ProtoMessage() {}

func (x *GetNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceResponse.ProtoReflect.Descriptor instead.
func (*GetNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetNamespaceResponse) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

type ListNamespacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Sort          *v1.SortRequest        `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"` // optional: filter namespaces by name substring
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesRequest) Reset() {
	*x = ListNamespacesRequest{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesRequest) ProtoMessage() {}

func (x *ListNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListNamespacesRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListNamespacesRequest) GetSort() *v1.SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListNamespacesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ListNamespacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []*Namespace           `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesResponse) Reset() {
	*x = ListNamespacesResponse{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResponse) ProtoMessage() {}

func (x *ListNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResponse.ProtoReflect.Descriptor instead.
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListNamespacesResponse) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *ListNamespacesResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNamespaceRequest) Reset() {
	*x = UpdateNamespaceRequest{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNamespaceRequest) ProtoMessage() {}

func (x *UpdateNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNamespaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateNamespaceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNamespaceResponse) Reset() {
	*x = UpdateNamespaceResponse{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNamespaceResponse) ProtoMessage() {}

func (x *UpdateNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNamespaceResponse.ProtoReflect.Descriptor instead.
func (*UpdateNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNamespaceResponse) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

type DeleteNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNamespaceRequest) Reset() {
	*x = DeleteNamespaceRequest{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceRequest) ProtoMessage() {}

func (x *DeleteNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNamespaceResponse) Reset() {
	*x = DeleteNamespaceResponse{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceResponse) ProtoMessage() {}

func (x *DeleteNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{9}
}

type LockNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockNamespaceRequest) Reset() {
	*x = LockNamespaceRequest{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockNamespaceRequest) ProtoMessage() {}

func (x *LockNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockNamespaceRequest.ProtoReflect.Descriptor instead.
func (*LockNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{10}
}

func (x *LockNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LockNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockNamespaceResponse) Reset() {
	*x = LockNamespaceResponse{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockNamespaceResponse) ProtoMessage() {}

func (x *LockNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockNamespaceResponse.ProtoReflect.Descriptor instead.
func (*LockNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{11}
}

type UnlockNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockNamespaceRequest) Reset() {
	*x = UnlockNamespaceRequest{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockNamespaceRequest) ProtoMessage() {}

func (x *UnlockNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockNamespaceRequest.ProtoReflect.Descriptor instead.
func (*UnlockNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{12}
}

func (x *UnlockNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UnlockNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockNamespaceResponse) Reset() {
	*x = UnlockNamespaceResponse{}
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockNamespaceResponse) ProtoMessage() {}

func (x *UnlockNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_namespace_v1_namespace_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockNamespaceResponse.ProtoReflect.Descriptor instead.
func (*UnlockNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_elara_namespace_v1_namespace_service_proto_rawDescGZIP(), []int{13}
}

var File_elara_namespace_v1_namespace_service_proto protoreflect.FileDescriptor

const file_elara_namespace_v1_namespace_service_proto_rawDesc = "" +
	"\n" +
	"*elara/namespace/v1/namespace_service.proto\x12\x12elara.namespace.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1celara/common/v1/common.proto\x1a\"elara/namespace/v1/namespace.proto\"\x85\x01\n" +
	"\x16CreateNamespaceRequest\x12I\n" +
	"\x04name\x18\x01 \x01(\tB5\xbaH2r0\x10\x01\x18\x80\x012)^[a-zA-Z0-9]([a-zA-Z0-9_-]*[a-zA-Z0-9])?$R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"V\n" +
	"\x17CreateNamespaceResponse\x12;\n" +
	"\tnamespace\x18\x01 \x01(\v2\x1d.elara.namespace.v1.NamespaceR\tnamespace\"1\n" +
	"\x13GetNamespaceRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\"S\n" +
	"\x14GetNamespaceResponse\x12;\n" +
	"\tnamespace\x18\x01 \x01(\v2\x1d.elara.namespace.v1.NamespaceR\tnamespace\"\xa3\x01\n" +
	"\x15ListNamespacesRequest\x12B\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\".elara.common.v1.PaginationRequestR\n" +
	"pagination\x120\n" +
	"\x04sort\x18\x02 \x01(\v2\x1c.elara.common.v1.SortRequestR\x04sort\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\"\x9c\x01\n" +
	"\x16ListNamespacesResponse\x12=\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2\x1d.elara.namespace.v1.NamespaceR\n" +
	"namespaces\x12C\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2#.elara.common.v1.PaginationResponseR\n" +
	"pagination\"V\n" +
	"\x16UpdateNamespaceRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"V\n" +
	"\x17UpdateNamespaceResponse\x12;\n" +
	"\tnamespace\x18\x01 \x01(\v2\x1d.elara.namespace.v1.NamespaceR\tnamespace\"4\n" +
	"\x16DeleteNamespaceRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\"\x19\n" +
	"\x17DeleteNamespaceResponse\"2\n" +
	"\x14LockNamespaceRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\"\x17\n" +
	"\x15LockNamespaceResponse\"4\n" +
	"\x16UnlockNamespaceRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\"\x19\n" +
	"\x17UnlockNamespaceResponse2\xf4\x05\n" +
	"\x10NamespaceService\x12j\n" +
	"\x0fCreateNamespace\x12*.elara.namespace.v1.CreateNamespaceRequest\x1a+.elara.namespace.v1.CreateNamespaceResponse\x12a\n" +
	"\fGetNamespace\x12'.elara.namespace.v1.GetNamespaceRequest\x1a(.elara.namespace.v1.GetNamespaceResponse\x12j\n" +
	"\x0fUpdateNamespace\x12*.elara.namespace.v1.UpdateNamespaceRequest\x1a+.elara.namespace.v1.UpdateNamespaceResponse\x12g\n" +
	"\x0eListNamespaces\x12).elara.namespace.v1.ListNamespacesRequest\x1a*.elara.namespace.v1.ListNamespacesResponse\x12j\n" +
	"\x0fDeleteNamespace\x12*.elara.namespace.v1.DeleteNamespaceRequest\x1a+.elara.namespace.v1.DeleteNamespaceResponse\x12d\n" +
	"\rLockNamespace\x12(.elara.namespace.v1.LockNamespaceRequest\x1a).elara.namespace.v1.LockNamespaceResponse\x12j\n" +
	"\x0fUnlockNamespace\x12*.elara.namespace.v1.UnlockNamespaceRequest\x1a+.elara.namespace.v1.UnlockNamespaceResponseB\xeb\x01\n" +
	"\x16com.elara.namespace.v1B\x15NamespaceServiceProtoP\x01ZNgithub.com/sergeyslonimsky/elara/internal/proto/elara/namespace/v1;namespacev1\xa2\x02\x03ENX\xaa\x02\x12Elara.Namespace.V1\xca\x02\x13Elara\\Namespace_\\V1\xe2\x02\x1fElara\\Namespace_\\V1\\GPBMetadata\xea\x02\x14Elara::Namespace::V1b\x06proto3"

var (
	file_elara_namespace_v1_namespace_service_proto_rawDescOnce sync.Once
	file_elara_namespace_v1_namespace_service_proto_rawDescData []byte
)

func file_elara_namespace_v1_namespace_service_proto_rawDescGZIP() []byte {
	file_elara_namespace_v1_namespace_service_proto_rawDescOnce.Do(func() {
		file_elara_namespace_v1_namespace_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_namespace_v1_namespace_service_proto_rawDesc), len(file_elara_namespace_v1_namespace_service_proto_rawDesc)))
	})
	return file_elara_namespace_v1_namespace_service_proto_rawDescData
}

var file_elara_namespace_v1_namespace_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_elara_namespace_v1_namespace_service_proto_goTypes = []any{
	(*CreateNamespaceRequest)(nil),  // 0: elara.namespace.v1.CreateNamespaceRequest
	(*CreateNamespaceResponse)(nil), // 1: elara.namespace.v1.CreateNamespaceResponse
	(*GetNamespaceRequest)(nil),     // 2: elara.namespace.v1.GetNamespaceRequest
	(*GetNamespaceResponse)(nil),    // 3: elara.namespace.v1.GetNamespaceResponse
	(*ListNamespacesRequest)(nil),   // 4: elara.namespace.v1.ListNamespacesRequest
	(*ListNamespacesResponse)(nil),  // 5: elara.namespace.v1.ListNamespacesResponse
	(*UpdateNamespaceRequest)(nil),  // 6: elara.namespace.v1.UpdateNamespaceRequest
	(*UpdateNamespaceResponse)(nil), // 7: elara.namespace.v1.UpdateNamespaceResponse
	(*DeleteNamespaceRequest)(nil),  // 8: elara.namespace.v1.DeleteNamespaceRequest
	(*DeleteNamespaceResponse)(nil), // 9: elara.namespace.v1.DeleteNamespaceResponse
	(*LockNamespaceRequest)(nil),    // 10: elara.namespace.v1.LockNamespaceRequest
	(*LockNamespaceResponse)(nil),   // 11: elara.namespace.v1.LockNamespaceResponse
	(*UnlockNamespaceRequest)(nil),  // 12: elara.namespace.v1.UnlockNamespaceRequest
	(*UnlockNamespaceResponse)(nil), // 13: elara.namespace.v1.UnlockNamespaceResponse
	(*Namespace)(nil),               // 14: elara.namespace.v1.Namespace
	(*v1.PaginationRequest)(nil),    // 15: elara.common.v1.PaginationRequest
	(*v1.SortRequest)(nil),          // 16: elara.common.v1.SortRequest
	(*v1.PaginationResponse)(nil),   // 17: elara.common.v1.PaginationResponse
}
var file_elara_namespace_v1_namespace_service_proto_depIdxs = []int32{
	14, // 0: elara.namespace.v1.CreateNamespaceResponse.namespace:type_name -> elara.namespace.v1.Namespace
	14, // 1: elara.namespace.v1.GetNamespaceResponse.namespace:type_name -> elara.namespace.v1.Namespace
	15, // 2: elara.namespace.v1.ListNamespacesRequest.pagination:type_name -> elara.common.v1.PaginationRequest
	16, // 3: elara.namespace.v1.ListNamespacesRequest.sort:type_name -> elara.common.v1.SortRequest
	14, // 4: elara.namespace.v1.ListNamespacesResponse.namespaces:type_name -> elara.namespace.v1.Namespace
	17, // 5: elara.namespace.v1.ListNamespacesResponse.pagination:type_name -> elara.common.v1.PaginationResponse
	14, // 6: elara.namespace.v1.UpdateNamespaceResponse.namespace:type_name -> elara.namespace.v1.Namespace
	0,  // 7: elara.namespace.v1.NamespaceService.CreateNamespace:input_type -> elara.namespace.v1.CreateNamespaceRequest
	2,  // 8: elara.namespace.v1.NamespaceService.GetNamespace:input_type -> elara.namespace.v1.GetNamespaceRequest
	6,  // 9: elara.namespace.v1.NamespaceService.UpdateNamespace:input_type -> elara.namespace.v1.UpdateNamespaceRequest
	4,  // 10: elara.namespace.v1.NamespaceService.ListNamespaces:input_type -> elara.namespace.v1.ListNamespacesRequest
	8,  // 11: elara.namespace.v1.NamespaceService.DeleteNamespace:input_type -> elara.namespace.v1.DeleteNamespaceRequest
	10, // 12: elara.namespace.v1.NamespaceService.LockNamespace:input_type -> elara.namespace.v1.LockNamespaceRequest
	12, // 13: elara.namespace.v1.NamespaceService.UnlockNamespace:input_type -> elara.namespace.v1.UnlockNamespaceRequest
	1,  // 14: elara.namespace.v1.NamespaceService.CreateNamespace:output_type -> elara.namespace.v1.CreateNamespaceResponse
	3,  // 15: elara.namespace.v1.NamespaceService.GetNamespace:output_type -> elara.namespace.v1.GetNamespaceResponse
	7,  // 16: elara.namespace.v1.NamespaceService.UpdateNamespace:output_type -> elara.namespace.v1.UpdateNamespaceResponse
	5,  // 17: elara.namespace.v1.NamespaceService.ListNamespaces:output_type -> elara.namespace.v1.ListNamespacesResponse
	9,  // 18: elara.namespace.v1.NamespaceService.DeleteNamespace:output_type -> elara.namespace.v1.DeleteNamespaceResponse
	11, // 19: elara.namespace.v1.NamespaceService.LockNamespace:output_type -> elara.namespace.v1.LockNamespaceResponse
	13, // 20: elara.namespace.v1.NamespaceService.UnlockNamespace:output_type -> elara.namespace.v1.UnlockNamespaceResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_elara_namespace_v1_namespace_service_proto_init() }
func file_elara_namespace_v1_namespace_service_proto_init() {
	if File_elara_namespace_v1_namespace_service_proto != nil {
		return
	}
	file_elara_namespace_v1_namespace_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_namespace_v1_namespace_service_proto_rawDesc), len(file_elara_namespace_v1_namespace_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elara_namespace_v1_namespace_service_proto_goTypes,
		DependencyIndexes: file_elara_namespace_v1_namespace_service_proto_depIdxs,
		MessageInfos:      file_elara_namespace_v1_namespace_service_proto_msgTypes,
	}.Build()
	File_elara_namespace_v1_namespace_service_proto = out.File
	file_elara_namespace_v1_namespace_service_proto_goTypes = nil
	file_elara_namespace_v1_namespace_service_proto_depIdxs = nil
}
