// Code generated by MockGen. DO NOT EDIT.
// Source: pdp.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/pdp_mock.go -package=authz_mock -source=pdp.go
//

// Package authz_mock is a generated GoMock package.
package authz_mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockenforcer is a mock of enforcer interface.
type Mockenforcer struct {
	ctrl     *gomock.Controller
	recorder *MockenforcerMockRecorder
	isgomock struct{}
}

// MockenforcerMockRecorder is the mock recorder for Mockenforcer.
type MockenforcerMockRecorder struct {
	mock *Mockenforcer
}

// NewMockenforcer creates a new mock instance.
func NewMockenforcer(ctrl *gomock.Controller) *Mockenforcer {
	mock := &Mockenforcer{ctrl: ctrl}
	mock.recorder = &MockenforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockenforcer) EXPECT() *MockenforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *Mockenforcer) Enforce(subject, domainStr, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, domainStr, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockenforcerMockRecorder) Enforce(subject, domainStr, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*Mockenforcer)(nil).Enforce), subject, domainStr, object, action)
}

// GetImplicitPermissionsForUser mocks base method.
func (m *Mockenforcer) GetImplicitPermissionsForUser(user string) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImplicitPermissionsForUser", user)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImplicitPermissionsForUser indicates an expected call of GetImplicitPermissionsForUser.
func (mr *MockenforcerMockRecorder) GetImplicitPermissionsForUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImplicitPermissionsForUser", reflect.TypeOf((*Mockenforcer)(nil).GetImplicitPermissionsForUser), user)
}
