// Code generated by MockGen. DO NOT EDIT.
// Source: history.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_history.go -package=mock_monitor -source=history.go
//

// Package mock_monitor is a generated GoMock package.
package mock_monitor

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
)

// MockClientHistoryRepo is a mock of ClientHistoryRepo interface.
type MockClientHistoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockClientHistoryRepoMockRecorder
	isgomock struct{}
}

// MockClientHistoryRepoMockRecorder is the mock recorder for MockClientHistoryRepo.
type MockClientHistoryRepoMockRecorder struct {
	mock *MockClientHistoryRepo
}

// NewMockClientHistoryRepo creates a new mock instance.
func NewMockClientHistoryRepo(ctrl *gomock.Controller) *MockClientHistoryRepo {
	mock := &MockClientHistoryRepo{ctrl: ctrl}
	mock.recorder = &MockClientHistoryRepoMockRecorder{mock}

	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientHistoryRepo) EXPECT() *MockClientHistoryRepoMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockClientHistoryRepo) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)

	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockClientHistoryRepoMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"Count",
		reflect.TypeOf((*MockClientHistoryRepo)(nil).Count),
		ctx,
	)
}

// DeleteOlderThan mocks base method.
func (m *MockClientHistoryRepo) DeleteOlderThan(ctx context.Context, cutoff time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", ctx, cutoff)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)

	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan.
func (mr *MockClientHistoryRepoMockRecorder) DeleteOlderThan(ctx, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"DeleteOlderThan",
		reflect.TypeOf((*MockClientHistoryRepo)(nil).DeleteOlderThan),
		ctx,
		cutoff,
	)
}

// DeleteOldest mocks base method.
func (m *MockClientHistoryRepo) DeleteOldest(ctx context.Context, n int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldest", ctx, n)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)

	return ret0, ret1
}

// DeleteOldest indicates an expected call of DeleteOldest.
func (mr *MockClientHistoryRepoMockRecorder) DeleteOldest(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"DeleteOldest",
		reflect.TypeOf((*MockClientHistoryRepo)(nil).DeleteOldest),
		ctx,
		n,
	)
}

// List mocks base method.
func (m *MockClientHistoryRepo) List(ctx context.Context, limit int) ([]*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit)
	ret0, _ := ret[0].([]*domain.Client)
	ret1, _ := ret[1].(error)

	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClientHistoryRepoMockRecorder) List(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"List",
		reflect.TypeOf((*MockClientHistoryRepo)(nil).List),
		ctx,
		limit,
	)
}

// ListByClient mocks base method.
func (m *MockClientHistoryRepo) ListByClient(
	ctx context.Context,
	clientName, k8sNamespace string,
	limit int,
) ([]*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClient", ctx, clientName, k8sNamespace, limit)
	ret0, _ := ret[0].([]*domain.Client)
	ret1, _ := ret[1].(error)

	return ret0, ret1
}

// ListByClient indicates an expected call of ListByClient.
func (mr *MockClientHistoryRepoMockRecorder) ListByClient(ctx, clientName, k8sNamespace, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"ListByClient",
		reflect.TypeOf((*MockClientHistoryRepo)(nil).ListByClient),
		ctx,
		clientName,
		k8sNamespace,
		limit,
	)
}

// Save mocks base method.
func (m *MockClientHistoryRepo) Save(ctx context.Context, c *domain.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, c)
	ret0, _ := ret[0].(error)

	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockClientHistoryRepoMockRecorder) Save(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"Save",
		reflect.TypeOf((*MockClientHistoryRepo)(nil).Save),
		ctx,
		c,
	)
}
