syntax = "proto3";

package elara.group.v1;

import "elara/common/v1/common.proto";
import "elara/common/v1/permission.proto";
import "elara/group/v1/group.proto";

service GroupService {
  rpc CreateGroup(CreateGroupRequest) returns (CreateGroupResponse);
  rpc GetGroup(GetGroupRequest) returns (GetGroupResponse);
  rpc UpdateGroup(UpdateGroupRequest) returns (UpdateGroupResponse);
  rpc DeleteGroup(DeleteGroupRequest) returns (DeleteGroupResponse);
  rpc ListGroups(ListGroupsRequest) returns (ListGroupsResponse);
}

message CreateGroupRequest {
  string name = 1;
}

message CreateGroupResponse {
  Group group = 1;
}

message GetGroupRequest {
  string id = 1;
}

message GetGroupResponse {
  Group group = 1;
}

message UpdateGroupRequest {
  string id = 1;
  string name = 2;
  string description = 3;
  repeated elara.common.v1.PermissionAssignment permissions = 4;
  repeated string members = 5;
  int64 version = 6;
}

message UpdateGroupResponse {
  Group group = 1;
}

message DeleteGroupRequest {
  string id = 1;
}

message DeleteGroupResponse {}

message ListGroupsRequest {
  elara.common.v1.PaginationRequest pagination = 1;
  string search = 2;
}

message ListGroupsResponse {
  repeated Group groups = 1;
  elara.common.v1.PaginationResponse pagination = 2;
}
