// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/filter/v1/filter.proto

package filterv1

import (
	v1 "github.com/sergeyslonimsky/elara/internal/proto/elara/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_elara_filter_v1_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_elara_filter_v1_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_elara_filter_v1_filter_proto_rawDescGZIP(), []int{0}
}

func (x *Filters) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Actions       []v1.PermissionAction  `protobuf:"varint,3,rep,packed,name=actions,proto3,enum=elara.common.v1.PermissionAction" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_elara_filter_v1_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_elara_filter_v1_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_elara_filter_v1_filter_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Item) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Item) GetActions() []v1.PermissionAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

var File_elara_filter_v1_filter_proto protoreflect.FileDescriptor

const file_elara_filter_v1_filter_proto_rawDesc = "" +
	"\n" +
	"\x1celara/filter/v1/filter.proto\x12\x0felara.filter.v1\x1a elara/common/v1/permission.proto\"\x1f\n" +
	"\aFilters\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"k\n" +
	"\x04Item\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12;\n" +
	"\aactions\x18\x03 \x03(\x0e2!.elara.common.v1.PermissionActionR\aactionsB\xca\x01\n" +
	"\x13com.elara.filter.v1B\vFilterProtoP\x01ZHgithub.com/sergeyslonimsky/elara/internal/proto/elara/filter/v1;filterv1\xa2\x02\x03EFX\xaa\x02\x0fElara.Filter.V1\xca\x02\x0fElara\\Filter\\V1\xe2\x02\x1bElara\\Filter\\V1\\GPBMetadata\xea\x02\x11Elara::Filter::V1b\x06proto3"

var (
	file_elara_filter_v1_filter_proto_rawDescOnce sync.Once
	file_elara_filter_v1_filter_proto_rawDescData []byte
)

func file_elara_filter_v1_filter_proto_rawDescGZIP() []byte {
	file_elara_filter_v1_filter_proto_rawDescOnce.Do(func() {
		file_elara_filter_v1_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_filter_v1_filter_proto_rawDesc), len(file_elara_filter_v1_filter_proto_rawDesc)))
	})
	return file_elara_filter_v1_filter_proto_rawDescData
}

var file_elara_filter_v1_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_elara_filter_v1_filter_proto_goTypes = []any{
	(*Filters)(nil),          // 0: elara.filter.v1.Filters
	(*Item)(nil),             // 1: elara.filter.v1.Item
	(v1.PermissionAction)(0), // 2: elara.common.v1.PermissionAction
}
var file_elara_filter_v1_filter_proto_depIdxs = []int32{
	2, // 0: elara.filter.v1.Item.actions:type_name -> elara.common.v1.PermissionAction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_elara_filter_v1_filter_proto_init() }
func file_elara_filter_v1_filter_proto_init() {
	if File_elara_filter_v1_filter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_filter_v1_filter_proto_rawDesc), len(file_elara_filter_v1_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_elara_filter_v1_filter_proto_goTypes,
		DependencyIndexes: file_elara_filter_v1_filter_proto_depIdxs,
		MessageInfos:      file_elara_filter_v1_filter_proto_msgTypes,
	}.Build()
	File_elara_filter_v1_filter_proto = out.File
	file_elara_filter_v1_filter_proto_goTypes = nil
	file_elara_filter_v1_filter_proto_depIdxs = nil
}
