// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/clients/v1/clients_service.proto

package clientsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchClientsResponse_Kind int32

const (
	WatchClientsResponse_KIND_UNSPECIFIED  WatchClientsResponse_Kind = 0
	WatchClientsResponse_KIND_SNAPSHOT     WatchClientsResponse_Kind = 1
	WatchClientsResponse_KIND_CONNECTED    WatchClientsResponse_Kind = 2
	WatchClientsResponse_KIND_DISCONNECTED WatchClientsResponse_Kind = 3
)

// Enum value maps for WatchClientsResponse_Kind.
var (
	WatchClientsResponse_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_SNAPSHOT",
		2: "KIND_CONNECTED",
		3: "KIND_DISCONNECTED",
	}
	WatchClientsResponse_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":  0,
		"KIND_SNAPSHOT":     1,
		"KIND_CONNECTED":    2,
		"KIND_DISCONNECTED": 3,
	}
)

func (x WatchClientsResponse_Kind) Enum() *WatchClientsResponse_Kind {
	p := new(WatchClientsResponse_Kind)
	*p = x
	return p
}

func (x WatchClientsResponse_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchClientsResponse_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_elara_clients_v1_clients_service_proto_enumTypes[0].Descriptor()
}

func (WatchClientsResponse_Kind) Type() protoreflect.EnumType {
	return &file_elara_clients_v1_clients_service_proto_enumTypes[0]
}

func (x WatchClientsResponse_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchClientsResponse_Kind.Descriptor instead.
func (WatchClientsResponse_Kind) EnumDescriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{7, 0}
}

type WatchClientResponse_Kind int32

const (
	WatchClientResponse_KIND_UNSPECIFIED      WatchClientResponse_Kind = 0
	WatchClientResponse_KIND_SNAPSHOT         WatchClientResponse_Kind = 1
	WatchClientResponse_KIND_REQUEST_RECORDED WatchClientResponse_Kind = 2
	WatchClientResponse_KIND_DISCONNECTED     WatchClientResponse_Kind = 3
)

// Enum value maps for WatchClientResponse_Kind.
var (
	WatchClientResponse_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_SNAPSHOT",
		2: "KIND_REQUEST_RECORDED",
		3: "KIND_DISCONNECTED",
	}
	WatchClientResponse_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":      0,
		"KIND_SNAPSHOT":         1,
		"KIND_REQUEST_RECORDED": 2,
		"KIND_DISCONNECTED":     3,
	}
)

func (x WatchClientResponse_Kind) Enum() *WatchClientResponse_Kind {
	p := new(WatchClientResponse_Kind)
	*p = x
	return p
}

func (x WatchClientResponse_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchClientResponse_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_elara_clients_v1_clients_service_proto_enumTypes[1].Descriptor()
}

func (WatchClientResponse_Kind) Type() protoreflect.EnumType {
	return &file_elara_clients_v1_clients_service_proto_enumTypes[1]
}

func (x WatchClientResponse_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchClientResponse_Kind.Descriptor instead.
func (WatchClientResponse_Kind) EnumDescriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{11, 0}
}

type ListActiveClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveClientsRequest) Reset() {
	*x = ListActiveClientsRequest{}
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveClientsRequest) ProtoMessage() {}

func (x *ListActiveClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveClientsRequest.ProtoReflect.Descriptor instead.
func (*ListActiveClientsRequest) Descriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{0}
}

type ListActiveClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*Client              `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveClientsResponse) Reset() {
	*x = ListActiveClientsResponse{}
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveClientsResponse) ProtoMessage() {}

func (x *ListActiveClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveClientsResponse.ProtoReflect.Descriptor instead.
func (*ListActiveClientsResponse) Descriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListActiveClientsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

type GetClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientRequest) Reset() {
	*x = GetClientRequest{}
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRequest) ProtoMessage() {}

func (x *GetClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRequest.ProtoReflect.Descriptor instead.
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetClientResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Client *Client                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	// Recent in-memory events (oldest first). Capacity is bounded server-side.
	RecentEvents  []*ClientEvent `protobuf:"bytes,2,rep,name=recent_events,json=recentEvents,proto3" json:"recent_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientResponse) Reset() {
	*x = GetClientResponse{}
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientResponse) ProtoMessage() {}

func (x *GetClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientResponse.ProtoReflect.Descriptor instead.
func (*GetClientResponse) Descriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *GetClientResponse) GetRecentEvents() []*ClientEvent {
	if x != nil {
		return x.RecentEvents
	}
	return nil
}

type ListHistoricalConnectionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of records to return; 0 → server default.
	Limit         int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoricalConnectionsRequest) Reset() {
	*x = ListHistoricalConnectionsRequest{}
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoricalConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoricalConnectionsRequest) ProtoMessage() {}

func (x *ListHistoricalConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoricalConnectionsRequest.ProtoReflect.Descriptor instead.
func (*ListHistoricalConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListHistoricalConnectionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListHistoricalConnectionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Newest-first.
	Clients       []*Client `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoricalConnectionsResponse) Reset() {
	*x = ListHistoricalConnectionsResponse{}
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoricalConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoricalConnectionsResponse) ProtoMessage() {}

func (x *ListHistoricalConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoricalConnectionsResponse.ProtoReflect.Descriptor instead.
func (*ListHistoricalConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListHistoricalConnectionsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

type WatchClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchClientsRequest) Reset() {
	*x = WatchClientsRequest{}
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchClientsRequest) ProtoMessage() {}

func (x *WatchClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchClientsRequest.ProtoReflect.Descriptor instead.
func (*WatchClientsRequest) Descriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{6}
}

type WatchClientsResponse struct {
	state protoimpl.MessageState    `protogen:"open.v1"`
	Kind  WatchClientsResponse_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=elara.clients.v1.WatchClientsResponse_Kind" json:"kind,omitempty"`
	// For SNAPSHOT: full active-client list at this moment.
	// For CONNECTED/DISCONNECTED: single-element list with the affected client.
	Clients       []*Client `protobuf:"bytes,2,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchClientsResponse) Reset() {
	*x = WatchClientsResponse{}
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchClientsResponse) ProtoMessage() {}

func (x *WatchClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchClientsResponse.ProtoReflect.Descriptor instead.
func (*WatchClientsResponse) Descriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{7}
}

func (x *WatchClientsResponse) GetKind() WatchClientsResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return WatchClientsResponse_KIND_UNSPECIFIED
}

func (x *WatchClientsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

type ListClientSessionsRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ClientName   string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	K8SNamespace string                 `protobuf:"bytes,2,opt,name=k8s_namespace,json=k8sNamespace,proto3" json:"k8s_namespace,omitempty"`
	// Connection ID to exclude (typically the active session being viewed).
	CurrentId string `protobuf:"bytes,3,opt,name=current_id,json=currentId,proto3" json:"current_id,omitempty"`
	// 0 → server default.
	Limit         int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientSessionsRequest) Reset() {
	*x = ListClientSessionsRequest{}
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientSessionsRequest) ProtoMessage() {}

func (x *ListClientSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListClientSessionsRequest) Descriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListClientSessionsRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ListClientSessionsRequest) GetK8SNamespace() string {
	if x != nil {
		return x.K8SNamespace
	}
	return ""
}

func (x *ListClientSessionsRequest) GetCurrentId() string {
	if x != nil {
		return x.CurrentId
	}
	return ""
}

func (x *ListClientSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListClientSessionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Newest-first.
	Sessions      []*Client `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientSessionsResponse) Reset() {
	*x = ListClientSessionsResponse{}
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientSessionsResponse) ProtoMessage() {}

func (x *ListClientSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListClientSessionsResponse) Descriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListClientSessionsResponse) GetSessions() []*Client {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type WatchClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchClientRequest) Reset() {
	*x = WatchClientRequest{}
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchClientRequest) ProtoMessage() {}

func (x *WatchClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchClientRequest.ProtoReflect.Descriptor instead.
func (*WatchClientRequest) Descriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{10}
}

func (x *WatchClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WatchClientResponse struct {
	state protoimpl.MessageState   `protogen:"open.v1"`
	Kind  WatchClientResponse_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=elara.clients.v1.WatchClientResponse_Kind" json:"kind,omitempty"`
	// For SNAPSHOT and DISCONNECTED: full snapshot of this client.
	Client *Client `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	// For REQUEST_RECORDED: the per-RPC event detail.
	Event         *ClientEvent `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchClientResponse) Reset() {
	*x = WatchClientResponse{}
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchClientResponse) ProtoMessage() {}

func (x *WatchClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_clients_v1_clients_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchClientResponse.ProtoReflect.Descriptor instead.
func (*WatchClientResponse) Descriptor() ([]byte, []int) {
	return file_elara_clients_v1_clients_service_proto_rawDescGZIP(), []int{11}
}

func (x *WatchClientResponse) GetKind() WatchClientResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return WatchClientResponse_KIND_UNSPECIFIED
}

func (x *WatchClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *WatchClientResponse) GetEvent() *ClientEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_elara_clients_v1_clients_service_proto protoreflect.FileDescriptor

const file_elara_clients_v1_clients_service_proto_rawDesc = "" +
	"\n" +
	"&elara/clients/v1/clients_service.proto\x12\x10elara.clients.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1eelara/clients/v1/clients.proto\"\x1a\n" +
	"\x18ListActiveClientsRequest\"O\n" +
	"\x19ListActiveClientsResponse\x122\n" +
	"\aclients\x18\x01 \x03(\v2\x18.elara.clients.v1.ClientR\aclients\"*\n" +
	"\x10GetClientRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\"\x89\x01\n" +
	"\x11GetClientResponse\x120\n" +
	"\x06client\x18\x01 \x01(\v2\x18.elara.clients.v1.ClientR\x06client\x12B\n" +
	"\rrecent_events\x18\x02 \x03(\v2\x1d.elara.clients.v1.ClientEventR\frecentEvents\"8\n" +
	" ListHistoricalConnectionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"W\n" +
	"!ListHistoricalConnectionsResponse\x122\n" +
	"\aclients\x18\x01 \x03(\v2\x18.elara.clients.v1.ClientR\aclients\"\x15\n" +
	"\x13WatchClientsRequest\"\xe7\x01\n" +
	"\x14WatchClientsResponse\x12?\n" +
	"\x04kind\x18\x01 \x01(\x0e2+.elara.clients.v1.WatchClientsResponse.KindR\x04kind\x122\n" +
	"\aclients\x18\x02 \x03(\v2\x18.elara.clients.v1.ClientR\aclients\"Z\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rKIND_SNAPSHOT\x10\x01\x12\x12\n" +
	"\x0eKIND_CONNECTED\x10\x02\x12\x15\n" +
	"\x11KIND_DISCONNECTED\x10\x03\"\x9e\x01\n" +
	"\x19ListClientSessionsRequest\x12'\n" +
	"\vclient_name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"clientName\x12#\n" +
	"\rk8s_namespace\x18\x02 \x01(\tR\fk8sNamespace\x12\x1d\n" +
	"\n" +
	"current_id\x18\x03 \x01(\tR\tcurrentId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"R\n" +
	"\x1aListClientSessionsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.elara.clients.v1.ClientR\bsessions\",\n" +
	"\x12WatchClientRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\"\x9f\x02\n" +
	"\x13WatchClientResponse\x12>\n" +
	"\x04kind\x18\x01 \x01(\x0e2*.elara.clients.v1.WatchClientResponse.KindR\x04kind\x120\n" +
	"\x06client\x18\x02 \x01(\v2\x18.elara.clients.v1.ClientR\x06client\x123\n" +
	"\x05event\x18\x03 \x01(\v2\x1d.elara.clients.v1.ClientEventR\x05event\"a\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rKIND_SNAPSHOT\x10\x01\x12\x19\n" +
	"\x15KIND_REQUEST_RECORDED\x10\x02\x12\x15\n" +
	"\x11KIND_DISCONNECTED\x10\x032\x8b\x05\n" +
	"\x0eClientsService\x12l\n" +
	"\x11ListActiveClients\x12*.elara.clients.v1.ListActiveClientsRequest\x1a+.elara.clients.v1.ListActiveClientsResponse\x12T\n" +
	"\tGetClient\x12\".elara.clients.v1.GetClientRequest\x1a#.elara.clients.v1.GetClientResponse\x12\x84\x01\n" +
	"\x19ListHistoricalConnections\x122.elara.clients.v1.ListHistoricalConnectionsRequest\x1a3.elara.clients.v1.ListHistoricalConnectionsResponse\x12o\n" +
	"\x12ListClientSessions\x12+.elara.clients.v1.ListClientSessionsRequest\x1a,.elara.clients.v1.ListClientSessionsResponse\x12_\n" +
	"\fWatchClients\x12%.elara.clients.v1.WatchClientsRequest\x1a&.elara.clients.v1.WatchClientsResponse0\x01\x12\\\n" +
	"\vWatchClient\x12$.elara.clients.v1.WatchClientRequest\x1a%.elara.clients.v1.WatchClientResponse0\x01B\xd9\x01\n" +
	"\x14com.elara.clients.v1B\x13ClientsServiceProtoP\x01ZJgithub.com/sergeyslonimsky/elara/internal/proto/elara/clients/v1;clientsv1\xa2\x02\x03ECX\xaa\x02\x10Elara.Clients.V1\xca\x02\x10Elara\\Clients\\V1\xe2\x02\x1cElara\\Clients\\V1\\GPBMetadata\xea\x02\x12Elara::Clients::V1b\x06proto3"

var (
	file_elara_clients_v1_clients_service_proto_rawDescOnce sync.Once
	file_elara_clients_v1_clients_service_proto_rawDescData []byte
)

func file_elara_clients_v1_clients_service_proto_rawDescGZIP() []byte {
	file_elara_clients_v1_clients_service_proto_rawDescOnce.Do(func() {
		file_elara_clients_v1_clients_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_clients_v1_clients_service_proto_rawDesc), len(file_elara_clients_v1_clients_service_proto_rawDesc)))
	})
	return file_elara_clients_v1_clients_service_proto_rawDescData
}

var file_elara_clients_v1_clients_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_elara_clients_v1_clients_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_elara_clients_v1_clients_service_proto_goTypes = []any{
	(WatchClientsResponse_Kind)(0),            // 0: elara.clients.v1.WatchClientsResponse.Kind
	(WatchClientResponse_Kind)(0),             // 1: elara.clients.v1.WatchClientResponse.Kind
	(*ListActiveClientsRequest)(nil),          // 2: elara.clients.v1.ListActiveClientsRequest
	(*ListActiveClientsResponse)(nil),         // 3: elara.clients.v1.ListActiveClientsResponse
	(*GetClientRequest)(nil),                  // 4: elara.clients.v1.GetClientRequest
	(*GetClientResponse)(nil),                 // 5: elara.clients.v1.GetClientResponse
	(*ListHistoricalConnectionsRequest)(nil),  // 6: elara.clients.v1.ListHistoricalConnectionsRequest
	(*ListHistoricalConnectionsResponse)(nil), // 7: elara.clients.v1.ListHistoricalConnectionsResponse
	(*WatchClientsRequest)(nil),               // 8: elara.clients.v1.WatchClientsRequest
	(*WatchClientsResponse)(nil),              // 9: elara.clients.v1.WatchClientsResponse
	(*ListClientSessionsRequest)(nil),         // 10: elara.clients.v1.ListClientSessionsRequest
	(*ListClientSessionsResponse)(nil),        // 11: elara.clients.v1.ListClientSessionsResponse
	(*WatchClientRequest)(nil),                // 12: elara.clients.v1.WatchClientRequest
	(*WatchClientResponse)(nil),               // 13: elara.clients.v1.WatchClientResponse
	(*Client)(nil),                            // 14: elara.clients.v1.Client
	(*ClientEvent)(nil),                       // 15: elara.clients.v1.ClientEvent
}
var file_elara_clients_v1_clients_service_proto_depIdxs = []int32{
	14, // 0: elara.clients.v1.ListActiveClientsResponse.clients:type_name -> elara.clients.v1.Client
	14, // 1: elara.clients.v1.GetClientResponse.client:type_name -> elara.clients.v1.Client
	15, // 2: elara.clients.v1.GetClientResponse.recent_events:type_name -> elara.clients.v1.ClientEvent
	14, // 3: elara.clients.v1.ListHistoricalConnectionsResponse.clients:type_name -> elara.clients.v1.Client
	0,  // 4: elara.clients.v1.WatchClientsResponse.kind:type_name -> elara.clients.v1.WatchClientsResponse.Kind
	14, // 5: elara.clients.v1.WatchClientsResponse.clients:type_name -> elara.clients.v1.Client
	14, // 6: elara.clients.v1.ListClientSessionsResponse.sessions:type_name -> elara.clients.v1.Client
	1,  // 7: elara.clients.v1.WatchClientResponse.kind:type_name -> elara.clients.v1.WatchClientResponse.Kind
	14, // 8: elara.clients.v1.WatchClientResponse.client:type_name -> elara.clients.v1.Client
	15, // 9: elara.clients.v1.WatchClientResponse.event:type_name -> elara.clients.v1.ClientEvent
	2,  // 10: elara.clients.v1.ClientsService.ListActiveClients:input_type -> elara.clients.v1.ListActiveClientsRequest
	4,  // 11: elara.clients.v1.ClientsService.GetClient:input_type -> elara.clients.v1.GetClientRequest
	6,  // 12: elara.clients.v1.ClientsService.ListHistoricalConnections:input_type -> elara.clients.v1.ListHistoricalConnectionsRequest
	10, // 13: elara.clients.v1.ClientsService.ListClientSessions:input_type -> elara.clients.v1.ListClientSessionsRequest
	8,  // 14: elara.clients.v1.ClientsService.WatchClients:input_type -> elara.clients.v1.WatchClientsRequest
	12, // 15: elara.clients.v1.ClientsService.WatchClient:input_type -> elara.clients.v1.WatchClientRequest
	3,  // 16: elara.clients.v1.ClientsService.ListActiveClients:output_type -> elara.clients.v1.ListActiveClientsResponse
	5,  // 17: elara.clients.v1.ClientsService.GetClient:output_type -> elara.clients.v1.GetClientResponse
	7,  // 18: elara.clients.v1.ClientsService.ListHistoricalConnections:output_type -> elara.clients.v1.ListHistoricalConnectionsResponse
	11, // 19: elara.clients.v1.ClientsService.ListClientSessions:output_type -> elara.clients.v1.ListClientSessionsResponse
	9,  // 20: elara.clients.v1.ClientsService.WatchClients:output_type -> elara.clients.v1.WatchClientsResponse
	13, // 21: elara.clients.v1.ClientsService.WatchClient:output_type -> elara.clients.v1.WatchClientResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_elara_clients_v1_clients_service_proto_init() }
func file_elara_clients_v1_clients_service_proto_init() {
	if File_elara_clients_v1_clients_service_proto != nil {
		return
	}
	file_elara_clients_v1_clients_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_clients_v1_clients_service_proto_rawDesc), len(file_elara_clients_v1_clients_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elara_clients_v1_clients_service_proto_goTypes,
		DependencyIndexes: file_elara_clients_v1_clients_service_proto_depIdxs,
		EnumInfos:         file_elara_clients_v1_clients_service_proto_enumTypes,
		MessageInfos:      file_elara_clients_v1_clients_service_proto_msgTypes,
	}.Build()
	File_elara_clients_v1_clients_service_proto = out.File
	file_elara_clients_v1_clients_service_proto_goTypes = nil
	file_elara_clients_v1_clients_service_proto_depIdxs = nil
}
