// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/schema (interfaces: attachEnforcer,schemaAttacher,attachNSChecker)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_attach.go -package=schema_mock . attachEnforcer,schemaAttacher,attachNSChecker
//

// Package schema_mock is a generated GoMock package.
package schema_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockattachEnforcer is a mock of attachEnforcer interface.
type MockattachEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockattachEnforcerMockRecorder
	isgomock struct{}
}

// MockattachEnforcerMockRecorder is the mock recorder for MockattachEnforcer.
type MockattachEnforcerMockRecorder struct {
	mock *MockattachEnforcer
}

// NewMockattachEnforcer creates a new mock instance.
func NewMockattachEnforcer(ctrl *gomock.Controller) *MockattachEnforcer {
	mock := &MockattachEnforcer{ctrl: ctrl}
	mock.recorder = &MockattachEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockattachEnforcer) EXPECT() *MockattachEnforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockattachEnforcer) Enforce(subject, arg1, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, arg1, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockattachEnforcerMockRecorder) Enforce(subject, arg1, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockattachEnforcer)(nil).Enforce), subject, arg1, object, action)
}

// MockschemaAttacher is a mock of schemaAttacher interface.
type MockschemaAttacher struct {
	ctrl     *gomock.Controller
	recorder *MockschemaAttacherMockRecorder
	isgomock struct{}
}

// MockschemaAttacherMockRecorder is the mock recorder for MockschemaAttacher.
type MockschemaAttacherMockRecorder struct {
	mock *MockschemaAttacher
}

// NewMockschemaAttacher creates a new mock instance.
func NewMockschemaAttacher(ctrl *gomock.Controller) *MockschemaAttacher {
	mock := &MockschemaAttacher{ctrl: ctrl}
	mock.recorder = &MockschemaAttacherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockschemaAttacher) EXPECT() *MockschemaAttacherMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockschemaAttacher) Attach(ctx context.Context, s *domain.SchemaAttachment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attach indicates an expected call of Attach.
func (mr *MockschemaAttacherMockRecorder) Attach(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockschemaAttacher)(nil).Attach), ctx, s)
}

// MockattachNSChecker is a mock of attachNSChecker interface.
type MockattachNSChecker struct {
	ctrl     *gomock.Controller
	recorder *MockattachNSCheckerMockRecorder
	isgomock struct{}
}

// MockattachNSCheckerMockRecorder is the mock recorder for MockattachNSChecker.
type MockattachNSCheckerMockRecorder struct {
	mock *MockattachNSChecker
}

// NewMockattachNSChecker creates a new mock instance.
func NewMockattachNSChecker(ctrl *gomock.Controller) *MockattachNSChecker {
	mock := &MockattachNSChecker{ctrl: ctrl}
	mock.recorder = &MockattachNSCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockattachNSChecker) EXPECT() *MockattachNSCheckerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockattachNSChecker) Get(ctx context.Context, name string) (*domain.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(*domain.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockattachNSCheckerMockRecorder) Get(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockattachNSChecker)(nil).Get), ctx, name)
}
