// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/schema (interfaces: detachEnforcer,schemaDetacher,detachNSChecker)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_detach.go -package=schema_mock . detachEnforcer,schemaDetacher,detachNSChecker
//

// Package schema_mock is a generated GoMock package.
package schema_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockdetachEnforcer is a mock of detachEnforcer interface.
type MockdetachEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockdetachEnforcerMockRecorder
	isgomock struct{}
}

// MockdetachEnforcerMockRecorder is the mock recorder for MockdetachEnforcer.
type MockdetachEnforcerMockRecorder struct {
	mock *MockdetachEnforcer
}

// NewMockdetachEnforcer creates a new mock instance.
func NewMockdetachEnforcer(ctrl *gomock.Controller) *MockdetachEnforcer {
	mock := &MockdetachEnforcer{ctrl: ctrl}
	mock.recorder = &MockdetachEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdetachEnforcer) EXPECT() *MockdetachEnforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockdetachEnforcer) Enforce(subject, arg1, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, arg1, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockdetachEnforcerMockRecorder) Enforce(subject, arg1, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockdetachEnforcer)(nil).Enforce), subject, arg1, object, action)
}

// MockschemaDetacher is a mock of schemaDetacher interface.
type MockschemaDetacher struct {
	ctrl     *gomock.Controller
	recorder *MockschemaDetacherMockRecorder
	isgomock struct{}
}

// MockschemaDetacherMockRecorder is the mock recorder for MockschemaDetacher.
type MockschemaDetacherMockRecorder struct {
	mock *MockschemaDetacher
}

// NewMockschemaDetacher creates a new mock instance.
func NewMockschemaDetacher(ctrl *gomock.Controller) *MockschemaDetacher {
	mock := &MockschemaDetacher{ctrl: ctrl}
	mock.recorder = &MockschemaDetacherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockschemaDetacher) EXPECT() *MockschemaDetacherMockRecorder {
	return m.recorder
}

// Detach mocks base method.
func (m *MockschemaDetacher) Detach(ctx context.Context, namespace, pathPattern string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detach", ctx, namespace, pathPattern)
	ret0, _ := ret[0].(error)
	return ret0
}

// Detach indicates an expected call of Detach.
func (mr *MockschemaDetacherMockRecorder) Detach(ctx, namespace, pathPattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockschemaDetacher)(nil).Detach), ctx, namespace, pathPattern)
}

// MockdetachNSChecker is a mock of detachNSChecker interface.
type MockdetachNSChecker struct {
	ctrl     *gomock.Controller
	recorder *MockdetachNSCheckerMockRecorder
	isgomock struct{}
}

// MockdetachNSCheckerMockRecorder is the mock recorder for MockdetachNSChecker.
type MockdetachNSCheckerMockRecorder struct {
	mock *MockdetachNSChecker
}

// NewMockdetachNSChecker creates a new mock instance.
func NewMockdetachNSChecker(ctrl *gomock.Controller) *MockdetachNSChecker {
	mock := &MockdetachNSChecker{ctrl: ctrl}
	mock.recorder = &MockdetachNSCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdetachNSChecker) EXPECT() *MockdetachNSCheckerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockdetachNSChecker) Get(ctx context.Context, name string) (*domain.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(*domain.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockdetachNSCheckerMockRecorder) Get(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockdetachNSChecker)(nil).Get), ctx, name)
}
