// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/namespace (interfaces: listEnforcer,nsLister,listConfigCounter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_list.go -package=mock_namespace . listEnforcer,nsLister,listConfigCounter
//

// Package mock_namespace is a generated GoMock package.
package mock_namespace

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocklistEnforcer is a mock of listEnforcer interface.
type MocklistEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MocklistEnforcerMockRecorder
	isgomock struct{}
}

// MocklistEnforcerMockRecorder is the mock recorder for MocklistEnforcer.
type MocklistEnforcerMockRecorder struct {
	mock *MocklistEnforcer
}

// NewMocklistEnforcer creates a new mock instance.
func NewMocklistEnforcer(ctrl *gomock.Controller) *MocklistEnforcer {
	mock := &MocklistEnforcer{ctrl: ctrl}
	mock.recorder = &MocklistEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklistEnforcer) EXPECT() *MocklistEnforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MocklistEnforcer) Enforce(subject, arg1, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, arg1, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MocklistEnforcerMockRecorder) Enforce(subject, arg1, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MocklistEnforcer)(nil).Enforce), subject, arg1, object, action)
}

// MocknsLister is a mock of nsLister interface.
type MocknsLister struct {
	ctrl     *gomock.Controller
	recorder *MocknsListerMockRecorder
	isgomock struct{}
}

// MocknsListerMockRecorder is the mock recorder for MocknsLister.
type MocknsListerMockRecorder struct {
	mock *MocknsLister
}

// NewMocknsLister creates a new mock instance.
func NewMocknsLister(ctrl *gomock.Controller) *MocknsLister {
	mock := &MocknsLister{ctrl: ctrl}
	mock.recorder = &MocknsListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknsLister) EXPECT() *MocknsListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MocknsLister) List(ctx context.Context) ([]*domain.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocknsListerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocknsLister)(nil).List), ctx)
}

// MocklistConfigCounter is a mock of listConfigCounter interface.
type MocklistConfigCounter struct {
	ctrl     *gomock.Controller
	recorder *MocklistConfigCounterMockRecorder
	isgomock struct{}
}

// MocklistConfigCounterMockRecorder is the mock recorder for MocklistConfigCounter.
type MocklistConfigCounterMockRecorder struct {
	mock *MocklistConfigCounter
}

// NewMocklistConfigCounter creates a new mock instance.
func NewMocklistConfigCounter(ctrl *gomock.Controller) *MocklistConfigCounter {
	mock := &MocklistConfigCounter{ctrl: ctrl}
	mock.recorder = &MocklistConfigCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklistConfigCounter) EXPECT() *MocklistConfigCounterMockRecorder {
	return m.recorder
}

// CountConfigs mocks base method.
func (m *MocklistConfigCounter) CountConfigs(ctx context.Context, name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountConfigs", ctx, name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountConfigs indicates an expected call of CountConfigs.
func (mr *MocklistConfigCounterMockRecorder) CountConfigs(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountConfigs", reflect.TypeOf((*MocklistConfigCounter)(nil).CountConfigs), ctx, name)
}
