// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/namespace (interfaces: getEnforcer,nsGetter,getConfigCounter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_get.go -package=mock_namespace . getEnforcer,nsGetter,getConfigCounter
//

// Package mock_namespace is a generated GoMock package.
package mock_namespace

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockgetEnforcer is a mock of getEnforcer interface.
type MockgetEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockgetEnforcerMockRecorder
	isgomock struct{}
}

// MockgetEnforcerMockRecorder is the mock recorder for MockgetEnforcer.
type MockgetEnforcerMockRecorder struct {
	mock *MockgetEnforcer
}

// NewMockgetEnforcer creates a new mock instance.
func NewMockgetEnforcer(ctrl *gomock.Controller) *MockgetEnforcer {
	mock := &MockgetEnforcer{ctrl: ctrl}
	mock.recorder = &MockgetEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgetEnforcer) EXPECT() *MockgetEnforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockgetEnforcer) Enforce(subject, arg1, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, arg1, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockgetEnforcerMockRecorder) Enforce(subject, arg1, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockgetEnforcer)(nil).Enforce), subject, arg1, object, action)
}

// MocknsGetter is a mock of nsGetter interface.
type MocknsGetter struct {
	ctrl     *gomock.Controller
	recorder *MocknsGetterMockRecorder
	isgomock struct{}
}

// MocknsGetterMockRecorder is the mock recorder for MocknsGetter.
type MocknsGetterMockRecorder struct {
	mock *MocknsGetter
}

// NewMocknsGetter creates a new mock instance.
func NewMocknsGetter(ctrl *gomock.Controller) *MocknsGetter {
	mock := &MocknsGetter{ctrl: ctrl}
	mock.recorder = &MocknsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknsGetter) EXPECT() *MocknsGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MocknsGetter) Get(ctx context.Context, name string) (*domain.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(*domain.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MocknsGetterMockRecorder) Get(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocknsGetter)(nil).Get), ctx, name)
}

// MockgetConfigCounter is a mock of getConfigCounter interface.
type MockgetConfigCounter struct {
	ctrl     *gomock.Controller
	recorder *MockgetConfigCounterMockRecorder
	isgomock struct{}
}

// MockgetConfigCounterMockRecorder is the mock recorder for MockgetConfigCounter.
type MockgetConfigCounterMockRecorder struct {
	mock *MockgetConfigCounter
}

// NewMockgetConfigCounter creates a new mock instance.
func NewMockgetConfigCounter(ctrl *gomock.Controller) *MockgetConfigCounter {
	mock := &MockgetConfigCounter{ctrl: ctrl}
	mock.recorder = &MockgetConfigCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgetConfigCounter) EXPECT() *MockgetConfigCounterMockRecorder {
	return m.recorder
}

// CountConfigs mocks base method.
func (m *MockgetConfigCounter) CountConfigs(ctx context.Context, name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountConfigs", ctx, name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountConfigs indicates an expected call of CountConfigs.
func (mr *MockgetConfigCounterMockRecorder) CountConfigs(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountConfigs", reflect.TypeOf((*MockgetConfigCounter)(nil).CountConfigs), ctx, name)
}
