// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/namespace (interfaces: updateEnforcer,nsUpdater,nsGetterForUpdate,updateConfigCounter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_update.go -package=mock_namespace . updateEnforcer,nsUpdater,nsGetterForUpdate,updateConfigCounter
//

// Package mock_namespace is a generated GoMock package.
package mock_namespace

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockupdateEnforcer is a mock of updateEnforcer interface.
type MockupdateEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockupdateEnforcerMockRecorder
	isgomock struct{}
}

// MockupdateEnforcerMockRecorder is the mock recorder for MockupdateEnforcer.
type MockupdateEnforcerMockRecorder struct {
	mock *MockupdateEnforcer
}

// NewMockupdateEnforcer creates a new mock instance.
func NewMockupdateEnforcer(ctrl *gomock.Controller) *MockupdateEnforcer {
	mock := &MockupdateEnforcer{ctrl: ctrl}
	mock.recorder = &MockupdateEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockupdateEnforcer) EXPECT() *MockupdateEnforcerMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockupdateEnforcer) Enforce(subject, arg1, object, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", subject, arg1, object, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockupdateEnforcerMockRecorder) Enforce(subject, arg1, object, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockupdateEnforcer)(nil).Enforce), subject, arg1, object, action)
}

// MocknsUpdater is a mock of nsUpdater interface.
type MocknsUpdater struct {
	ctrl     *gomock.Controller
	recorder *MocknsUpdaterMockRecorder
	isgomock struct{}
}

// MocknsUpdaterMockRecorder is the mock recorder for MocknsUpdater.
type MocknsUpdaterMockRecorder struct {
	mock *MocknsUpdater
}

// NewMocknsUpdater creates a new mock instance.
func NewMocknsUpdater(ctrl *gomock.Controller) *MocknsUpdater {
	mock := &MocknsUpdater{ctrl: ctrl}
	mock.recorder = &MocknsUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknsUpdater) EXPECT() *MocknsUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MocknsUpdater) Update(ctx context.Context, ns *domain.Namespace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ns)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MocknsUpdaterMockRecorder) Update(ctx, ns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MocknsUpdater)(nil).Update), ctx, ns)
}

// MocknsGetterForUpdate is a mock of nsGetterForUpdate interface.
type MocknsGetterForUpdate struct {
	ctrl     *gomock.Controller
	recorder *MocknsGetterForUpdateMockRecorder
	isgomock struct{}
}

// MocknsGetterForUpdateMockRecorder is the mock recorder for MocknsGetterForUpdate.
type MocknsGetterForUpdateMockRecorder struct {
	mock *MocknsGetterForUpdate
}

// NewMocknsGetterForUpdate creates a new mock instance.
func NewMocknsGetterForUpdate(ctrl *gomock.Controller) *MocknsGetterForUpdate {
	mock := &MocknsGetterForUpdate{ctrl: ctrl}
	mock.recorder = &MocknsGetterForUpdateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknsGetterForUpdate) EXPECT() *MocknsGetterForUpdateMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MocknsGetterForUpdate) Get(ctx context.Context, name string) (*domain.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(*domain.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MocknsGetterForUpdateMockRecorder) Get(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocknsGetterForUpdate)(nil).Get), ctx, name)
}

// MockupdateConfigCounter is a mock of updateConfigCounter interface.
type MockupdateConfigCounter struct {
	ctrl     *gomock.Controller
	recorder *MockupdateConfigCounterMockRecorder
	isgomock struct{}
}

// MockupdateConfigCounterMockRecorder is the mock recorder for MockupdateConfigCounter.
type MockupdateConfigCounterMockRecorder struct {
	mock *MockupdateConfigCounter
}

// NewMockupdateConfigCounter creates a new mock instance.
func NewMockupdateConfigCounter(ctrl *gomock.Controller) *MockupdateConfigCounter {
	mock := &MockupdateConfigCounter{ctrl: ctrl}
	mock.recorder = &MockupdateConfigCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockupdateConfigCounter) EXPECT() *MockupdateConfigCounterMockRecorder {
	return m.recorder
}

// CountConfigs mocks base method.
func (m *MockupdateConfigCounter) CountConfigs(ctx context.Context, name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountConfigs", ctx, name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountConfigs indicates an expected call of CountConfigs.
func (mr *MockupdateConfigCounterMockRecorder) CountConfigs(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountConfigs", reflect.TypeOf((*MockupdateConfigCounter)(nil).CountConfigs), ctx, name)
}
