// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: elara/namespace/v1/namespace_service.proto

package namespacev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sergeyslonimsky/elara/internal/proto/elara/namespace/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NamespaceServiceName is the fully-qualified name of the NamespaceService service.
	NamespaceServiceName = "elara.namespace.v1.NamespaceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NamespaceServiceCreateNamespaceProcedure is the fully-qualified name of the NamespaceService's
	// CreateNamespace RPC.
	NamespaceServiceCreateNamespaceProcedure = "/elara.namespace.v1.NamespaceService/CreateNamespace"
	// NamespaceServiceGetNamespaceProcedure is the fully-qualified name of the NamespaceService's
	// GetNamespace RPC.
	NamespaceServiceGetNamespaceProcedure = "/elara.namespace.v1.NamespaceService/GetNamespace"
	// NamespaceServiceUpdateNamespaceProcedure is the fully-qualified name of the NamespaceService's
	// UpdateNamespace RPC.
	NamespaceServiceUpdateNamespaceProcedure = "/elara.namespace.v1.NamespaceService/UpdateNamespace"
	// NamespaceServiceListNamespacesProcedure is the fully-qualified name of the NamespaceService's
	// ListNamespaces RPC.
	NamespaceServiceListNamespacesProcedure = "/elara.namespace.v1.NamespaceService/ListNamespaces"
	// NamespaceServiceDeleteNamespaceProcedure is the fully-qualified name of the NamespaceService's
	// DeleteNamespace RPC.
	NamespaceServiceDeleteNamespaceProcedure = "/elara.namespace.v1.NamespaceService/DeleteNamespace"
	// NamespaceServiceLockNamespaceProcedure is the fully-qualified name of the NamespaceService's
	// LockNamespace RPC.
	NamespaceServiceLockNamespaceProcedure = "/elara.namespace.v1.NamespaceService/LockNamespace"
	// NamespaceServiceUnlockNamespaceProcedure is the fully-qualified name of the NamespaceService's
	// UnlockNamespace RPC.
	NamespaceServiceUnlockNamespaceProcedure = "/elara.namespace.v1.NamespaceService/UnlockNamespace"
)

// NamespaceServiceClient is a client for the elara.namespace.v1.NamespaceService service.
type NamespaceServiceClient interface {
	CreateNamespace(context.Context, *connect.Request[v1.CreateNamespaceRequest]) (*connect.Response[v1.CreateNamespaceResponse], error)
	GetNamespace(context.Context, *connect.Request[v1.GetNamespaceRequest]) (*connect.Response[v1.GetNamespaceResponse], error)
	UpdateNamespace(context.Context, *connect.Request[v1.UpdateNamespaceRequest]) (*connect.Response[v1.UpdateNamespaceResponse], error)
	ListNamespaces(context.Context, *connect.Request[v1.ListNamespacesRequest]) (*connect.Response[v1.ListNamespacesResponse], error)
	DeleteNamespace(context.Context, *connect.Request[v1.DeleteNamespaceRequest]) (*connect.Response[v1.DeleteNamespaceResponse], error)
	LockNamespace(context.Context, *connect.Request[v1.LockNamespaceRequest]) (*connect.Response[v1.LockNamespaceResponse], error)
	UnlockNamespace(context.Context, *connect.Request[v1.UnlockNamespaceRequest]) (*connect.Response[v1.UnlockNamespaceResponse], error)
}

// NewNamespaceServiceClient constructs a client for the elara.namespace.v1.NamespaceService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNamespaceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NamespaceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	namespaceServiceMethods := v1.File_elara_namespace_v1_namespace_service_proto.Services().ByName("NamespaceService").Methods()
	return &namespaceServiceClient{
		createNamespace: connect.NewClient[v1.CreateNamespaceRequest, v1.CreateNamespaceResponse](
			httpClient,
			baseURL+NamespaceServiceCreateNamespaceProcedure,
			connect.WithSchema(namespaceServiceMethods.ByName("CreateNamespace")),
			connect.WithClientOptions(opts...),
		),
		getNamespace: connect.NewClient[v1.GetNamespaceRequest, v1.GetNamespaceResponse](
			httpClient,
			baseURL+NamespaceServiceGetNamespaceProcedure,
			connect.WithSchema(namespaceServiceMethods.ByName("GetNamespace")),
			connect.WithClientOptions(opts...),
		),
		updateNamespace: connect.NewClient[v1.UpdateNamespaceRequest, v1.UpdateNamespaceResponse](
			httpClient,
			baseURL+NamespaceServiceUpdateNamespaceProcedure,
			connect.WithSchema(namespaceServiceMethods.ByName("UpdateNamespace")),
			connect.WithClientOptions(opts...),
		),
		listNamespaces: connect.NewClient[v1.ListNamespacesRequest, v1.ListNamespacesResponse](
			httpClient,
			baseURL+NamespaceServiceListNamespacesProcedure,
			connect.WithSchema(namespaceServiceMethods.ByName("ListNamespaces")),
			connect.WithClientOptions(opts...),
		),
		deleteNamespace: connect.NewClient[v1.DeleteNamespaceRequest, v1.DeleteNamespaceResponse](
			httpClient,
			baseURL+NamespaceServiceDeleteNamespaceProcedure,
			connect.WithSchema(namespaceServiceMethods.ByName("DeleteNamespace")),
			connect.WithClientOptions(opts...),
		),
		lockNamespace: connect.NewClient[v1.LockNamespaceRequest, v1.LockNamespaceResponse](
			httpClient,
			baseURL+NamespaceServiceLockNamespaceProcedure,
			connect.WithSchema(namespaceServiceMethods.ByName("LockNamespace")),
			connect.WithClientOptions(opts...),
		),
		unlockNamespace: connect.NewClient[v1.UnlockNamespaceRequest, v1.UnlockNamespaceResponse](
			httpClient,
			baseURL+NamespaceServiceUnlockNamespaceProcedure,
			connect.WithSchema(namespaceServiceMethods.ByName("UnlockNamespace")),
			connect.WithClientOptions(opts...),
		),
	}
}

// namespaceServiceClient implements NamespaceServiceClient.
type namespaceServiceClient struct {
	createNamespace *connect.Client[v1.CreateNamespaceRequest, v1.CreateNamespaceResponse]
	getNamespace    *connect.Client[v1.GetNamespaceRequest, v1.GetNamespaceResponse]
	updateNamespace *connect.Client[v1.UpdateNamespaceRequest, v1.UpdateNamespaceResponse]
	listNamespaces  *connect.Client[v1.ListNamespacesRequest, v1.ListNamespacesResponse]
	deleteNamespace *connect.Client[v1.DeleteNamespaceRequest, v1.DeleteNamespaceResponse]
	lockNamespace   *connect.Client[v1.LockNamespaceRequest, v1.LockNamespaceResponse]
	unlockNamespace *connect.Client[v1.UnlockNamespaceRequest, v1.UnlockNamespaceResponse]
}

// CreateNamespace calls elara.namespace.v1.NamespaceService.CreateNamespace.
func (c *namespaceServiceClient) CreateNamespace(ctx context.Context, req *connect.Request[v1.CreateNamespaceRequest]) (*connect.Response[v1.CreateNamespaceResponse], error) {
	return c.createNamespace.CallUnary(ctx, req)
}

// GetNamespace calls elara.namespace.v1.NamespaceService.GetNamespace.
func (c *namespaceServiceClient) GetNamespace(ctx context.Context, req *connect.Request[v1.GetNamespaceRequest]) (*connect.Response[v1.GetNamespaceResponse], error) {
	return c.getNamespace.CallUnary(ctx, req)
}

// UpdateNamespace calls elara.namespace.v1.NamespaceService.UpdateNamespace.
func (c *namespaceServiceClient) UpdateNamespace(ctx context.Context, req *connect.Request[v1.UpdateNamespaceRequest]) (*connect.Response[v1.UpdateNamespaceResponse], error) {
	return c.updateNamespace.CallUnary(ctx, req)
}

// ListNamespaces calls elara.namespace.v1.NamespaceService.ListNamespaces.
func (c *namespaceServiceClient) ListNamespaces(ctx context.Context, req *connect.Request[v1.ListNamespacesRequest]) (*connect.Response[v1.ListNamespacesResponse], error) {
	return c.listNamespaces.CallUnary(ctx, req)
}

// DeleteNamespace calls elara.namespace.v1.NamespaceService.DeleteNamespace.
func (c *namespaceServiceClient) DeleteNamespace(ctx context.Context, req *connect.Request[v1.DeleteNamespaceRequest]) (*connect.Response[v1.DeleteNamespaceResponse], error) {
	return c.deleteNamespace.CallUnary(ctx, req)
}

// LockNamespace calls elara.namespace.v1.NamespaceService.LockNamespace.
func (c *namespaceServiceClient) LockNamespace(ctx context.Context, req *connect.Request[v1.LockNamespaceRequest]) (*connect.Response[v1.LockNamespaceResponse], error) {
	return c.lockNamespace.CallUnary(ctx, req)
}

// UnlockNamespace calls elara.namespace.v1.NamespaceService.UnlockNamespace.
func (c *namespaceServiceClient) UnlockNamespace(ctx context.Context, req *connect.Request[v1.UnlockNamespaceRequest]) (*connect.Response[v1.UnlockNamespaceResponse], error) {
	return c.unlockNamespace.CallUnary(ctx, req)
}

// NamespaceServiceHandler is an implementation of the elara.namespace.v1.NamespaceService service.
type NamespaceServiceHandler interface {
	CreateNamespace(context.Context, *connect.Request[v1.CreateNamespaceRequest]) (*connect.Response[v1.CreateNamespaceResponse], error)
	GetNamespace(context.Context, *connect.Request[v1.GetNamespaceRequest]) (*connect.Response[v1.GetNamespaceResponse], error)
	UpdateNamespace(context.Context, *connect.Request[v1.UpdateNamespaceRequest]) (*connect.Response[v1.UpdateNamespaceResponse], error)
	ListNamespaces(context.Context, *connect.Request[v1.ListNamespacesRequest]) (*connect.Response[v1.ListNamespacesResponse], error)
	DeleteNamespace(context.Context, *connect.Request[v1.DeleteNamespaceRequest]) (*connect.Response[v1.DeleteNamespaceResponse], error)
	LockNamespace(context.Context, *connect.Request[v1.LockNamespaceRequest]) (*connect.Response[v1.LockNamespaceResponse], error)
	UnlockNamespace(context.Context, *connect.Request[v1.UnlockNamespaceRequest]) (*connect.Response[v1.UnlockNamespaceResponse], error)
}

// NewNamespaceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNamespaceServiceHandler(svc NamespaceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	namespaceServiceMethods := v1.File_elara_namespace_v1_namespace_service_proto.Services().ByName("NamespaceService").Methods()
	namespaceServiceCreateNamespaceHandler := connect.NewUnaryHandler(
		NamespaceServiceCreateNamespaceProcedure,
		svc.CreateNamespace,
		connect.WithSchema(namespaceServiceMethods.ByName("CreateNamespace")),
		connect.WithHandlerOptions(opts...),
	)
	namespaceServiceGetNamespaceHandler := connect.NewUnaryHandler(
		NamespaceServiceGetNamespaceProcedure,
		svc.GetNamespace,
		connect.WithSchema(namespaceServiceMethods.ByName("GetNamespace")),
		connect.WithHandlerOptions(opts...),
	)
	namespaceServiceUpdateNamespaceHandler := connect.NewUnaryHandler(
		NamespaceServiceUpdateNamespaceProcedure,
		svc.UpdateNamespace,
		connect.WithSchema(namespaceServiceMethods.ByName("UpdateNamespace")),
		connect.WithHandlerOptions(opts...),
	)
	namespaceServiceListNamespacesHandler := connect.NewUnaryHandler(
		NamespaceServiceListNamespacesProcedure,
		svc.ListNamespaces,
		connect.WithSchema(namespaceServiceMethods.ByName("ListNamespaces")),
		connect.WithHandlerOptions(opts...),
	)
	namespaceServiceDeleteNamespaceHandler := connect.NewUnaryHandler(
		NamespaceServiceDeleteNamespaceProcedure,
		svc.DeleteNamespace,
		connect.WithSchema(namespaceServiceMethods.ByName("DeleteNamespace")),
		connect.WithHandlerOptions(opts...),
	)
	namespaceServiceLockNamespaceHandler := connect.NewUnaryHandler(
		NamespaceServiceLockNamespaceProcedure,
		svc.LockNamespace,
		connect.WithSchema(namespaceServiceMethods.ByName("LockNamespace")),
		connect.WithHandlerOptions(opts...),
	)
	namespaceServiceUnlockNamespaceHandler := connect.NewUnaryHandler(
		NamespaceServiceUnlockNamespaceProcedure,
		svc.UnlockNamespace,
		connect.WithSchema(namespaceServiceMethods.ByName("UnlockNamespace")),
		connect.WithHandlerOptions(opts...),
	)
	return "/elara.namespace.v1.NamespaceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NamespaceServiceCreateNamespaceProcedure:
			namespaceServiceCreateNamespaceHandler.ServeHTTP(w, r)
		case NamespaceServiceGetNamespaceProcedure:
			namespaceServiceGetNamespaceHandler.ServeHTTP(w, r)
		case NamespaceServiceUpdateNamespaceProcedure:
			namespaceServiceUpdateNamespaceHandler.ServeHTTP(w, r)
		case NamespaceServiceListNamespacesProcedure:
			namespaceServiceListNamespacesHandler.ServeHTTP(w, r)
		case NamespaceServiceDeleteNamespaceProcedure:
			namespaceServiceDeleteNamespaceHandler.ServeHTTP(w, r)
		case NamespaceServiceLockNamespaceProcedure:
			namespaceServiceLockNamespaceHandler.ServeHTTP(w, r)
		case NamespaceServiceUnlockNamespaceProcedure:
			namespaceServiceUnlockNamespaceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNamespaceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNamespaceServiceHandler struct{}

func (UnimplementedNamespaceServiceHandler) CreateNamespace(context.Context, *connect.Request[v1.CreateNamespaceRequest]) (*connect.Response[v1.CreateNamespaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.namespace.v1.NamespaceService.CreateNamespace is not implemented"))
}

func (UnimplementedNamespaceServiceHandler) GetNamespace(context.Context, *connect.Request[v1.GetNamespaceRequest]) (*connect.Response[v1.GetNamespaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.namespace.v1.NamespaceService.GetNamespace is not implemented"))
}

func (UnimplementedNamespaceServiceHandler) UpdateNamespace(context.Context, *connect.Request[v1.UpdateNamespaceRequest]) (*connect.Response[v1.UpdateNamespaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.namespace.v1.NamespaceService.UpdateNamespace is not implemented"))
}

func (UnimplementedNamespaceServiceHandler) ListNamespaces(context.Context, *connect.Request[v1.ListNamespacesRequest]) (*connect.Response[v1.ListNamespacesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.namespace.v1.NamespaceService.ListNamespaces is not implemented"))
}

func (UnimplementedNamespaceServiceHandler) DeleteNamespace(context.Context, *connect.Request[v1.DeleteNamespaceRequest]) (*connect.Response[v1.DeleteNamespaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.namespace.v1.NamespaceService.DeleteNamespace is not implemented"))
}

func (UnimplementedNamespaceServiceHandler) LockNamespace(context.Context, *connect.Request[v1.LockNamespaceRequest]) (*connect.Response[v1.LockNamespaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.namespace.v1.NamespaceService.LockNamespace is not implemented"))
}

func (UnimplementedNamespaceServiceHandler) UnlockNamespace(context.Context, *connect.Request[v1.UnlockNamespaceRequest]) (*connect.Response[v1.UnlockNamespaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elara.namespace.v1.NamespaceService.UnlockNamespace is not implemented"))
}
