// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mock.go -package=policy_mock -source=service.go
//

// Package policy_mock is a generated GoMock package.
package policy_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockgroupFinder is a mock of groupFinder interface.
type MockgroupFinder struct {
	ctrl     *gomock.Controller
	recorder *MockgroupFinderMockRecorder
	isgomock struct{}
}

// MockgroupFinderMockRecorder is the mock recorder for MockgroupFinder.
type MockgroupFinderMockRecorder struct {
	mock *MockgroupFinder
}

// NewMockgroupFinder creates a new mock instance.
func NewMockgroupFinder(ctrl *gomock.Controller) *MockgroupFinder {
	mock := &MockgroupFinder{ctrl: ctrl}
	mock.recorder = &MockgroupFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgroupFinder) EXPECT() *MockgroupFinderMockRecorder {
	return m.recorder
}

// FindByName mocks base method.
func (m *MockgroupFinder) FindByName(ctx context.Context, name string) (*domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockgroupFinderMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockgroupFinder)(nil).FindByName), ctx, name)
}
