// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/transfer/v1/transfer.proto

package transferv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BundleEncoding int32

const (
	BundleEncoding_BUNDLE_ENCODING_UNSPECIFIED BundleEncoding = 0
	BundleEncoding_BUNDLE_ENCODING_JSON        BundleEncoding = 1
	BundleEncoding_BUNDLE_ENCODING_YAML        BundleEncoding = 2
)

// Enum value maps for BundleEncoding.
var (
	BundleEncoding_name = map[int32]string{
		0: "BUNDLE_ENCODING_UNSPECIFIED",
		1: "BUNDLE_ENCODING_JSON",
		2: "BUNDLE_ENCODING_YAML",
	}
	BundleEncoding_value = map[string]int32{
		"BUNDLE_ENCODING_UNSPECIFIED": 0,
		"BUNDLE_ENCODING_JSON":        1,
		"BUNDLE_ENCODING_YAML":        2,
	}
)

func (x BundleEncoding) Enum() *BundleEncoding {
	p := new(BundleEncoding)
	*p = x
	return p
}

func (x BundleEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BundleEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_elara_transfer_v1_transfer_proto_enumTypes[0].Descriptor()
}

func (BundleEncoding) Type() protoreflect.EnumType {
	return &file_elara_transfer_v1_transfer_proto_enumTypes[0]
}

func (x BundleEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BundleEncoding.Descriptor instead.
func (BundleEncoding) EnumDescriptor() ([]byte, []int) {
	return file_elara_transfer_v1_transfer_proto_rawDescGZIP(), []int{0}
}

type ZipLayout int32

const (
	ZipLayout_ZIP_LAYOUT_UNSPECIFIED   ZipLayout = 0
	ZipLayout_ZIP_LAYOUT_BUNDLE        ZipLayout = 1
	ZipLayout_ZIP_LAYOUT_PER_NAMESPACE ZipLayout = 2
)

// Enum value maps for ZipLayout.
var (
	ZipLayout_name = map[int32]string{
		0: "ZIP_LAYOUT_UNSPECIFIED",
		1: "ZIP_LAYOUT_BUNDLE",
		2: "ZIP_LAYOUT_PER_NAMESPACE",
	}
	ZipLayout_value = map[string]int32{
		"ZIP_LAYOUT_UNSPECIFIED":   0,
		"ZIP_LAYOUT_BUNDLE":        1,
		"ZIP_LAYOUT_PER_NAMESPACE": 2,
	}
)

func (x ZipLayout) Enum() *ZipLayout {
	p := new(ZipLayout)
	*p = x
	return p
}

func (x ZipLayout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZipLayout) Descriptor() protoreflect.EnumDescriptor {
	return file_elara_transfer_v1_transfer_proto_enumTypes[1].Descriptor()
}

func (ZipLayout) Type() protoreflect.EnumType {
	return &file_elara_transfer_v1_transfer_proto_enumTypes[1]
}

func (x ZipLayout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZipLayout.Descriptor instead.
func (ZipLayout) EnumDescriptor() ([]byte, []int) {
	return file_elara_transfer_v1_transfer_proto_rawDescGZIP(), []int{1}
}

type ConflictResolution int32

const (
	ConflictResolution_CONFLICT_RESOLUTION_UNSPECIFIED ConflictResolution = 0
	ConflictResolution_CONFLICT_RESOLUTION_SKIP        ConflictResolution = 1
	ConflictResolution_CONFLICT_RESOLUTION_OVERWRITE   ConflictResolution = 2
	ConflictResolution_CONFLICT_RESOLUTION_FAIL        ConflictResolution = 3
)

// Enum value maps for ConflictResolution.
var (
	ConflictResolution_name = map[int32]string{
		0: "CONFLICT_RESOLUTION_UNSPECIFIED",
		1: "CONFLICT_RESOLUTION_SKIP",
		2: "CONFLICT_RESOLUTION_OVERWRITE",
		3: "CONFLICT_RESOLUTION_FAIL",
	}
	ConflictResolution_value = map[string]int32{
		"CONFLICT_RESOLUTION_UNSPECIFIED": 0,
		"CONFLICT_RESOLUTION_SKIP":        1,
		"CONFLICT_RESOLUTION_OVERWRITE":   2,
		"CONFLICT_RESOLUTION_FAIL":        3,
	}
)

func (x ConflictResolution) Enum() *ConflictResolution {
	p := new(ConflictResolution)
	*p = x
	return p
}

func (x ConflictResolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConflictResolution) Descriptor() protoreflect.EnumDescriptor {
	return file_elara_transfer_v1_transfer_proto_enumTypes[2].Descriptor()
}

func (ConflictResolution) Type() protoreflect.EnumType {
	return &file_elara_transfer_v1_transfer_proto_enumTypes[2]
}

func (x ConflictResolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConflictResolution.Descriptor instead.
func (ConflictResolution) EnumDescriptor() ([]byte, []int) {
	return file_elara_transfer_v1_transfer_proto_rawDescGZIP(), []int{2}
}

type ImportError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportError) Reset() {
	*x = ImportError{}
	mi := &file_elara_transfer_v1_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportError) ProtoMessage() {}

func (x *ImportError) ProtoReflect() protoreflect.Message {
	mi := &file_elara_transfer_v1_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportError.ProtoReflect.Descriptor instead.
func (*ImportError) Descriptor() ([]byte, []int) {
	return file_elara_transfer_v1_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *ImportError) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ImportError) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ImportError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_elara_transfer_v1_transfer_proto protoreflect.FileDescriptor

const file_elara_transfer_v1_transfer_proto_rawDesc = "" +
	"\n" +
	" elara/transfer/v1/transfer.proto\x12\x11elara.transfer.v1\"Y\n" +
	"\vImportError\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*e\n" +
	"\x0eBundleEncoding\x12\x1f\n" +
	"\x1bBUNDLE_ENCODING_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BUNDLE_ENCODING_JSON\x10\x01\x12\x18\n" +
	"\x14BUNDLE_ENCODING_YAML\x10\x02*\\\n" +
	"\tZipLayout\x12\x1a\n" +
	"\x16ZIP_LAYOUT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ZIP_LAYOUT_BUNDLE\x10\x01\x12\x1c\n" +
	"\x18ZIP_LAYOUT_PER_NAMESPACE\x10\x02*\x98\x01\n" +
	"\x12ConflictResolution\x12#\n" +
	"\x1fCONFLICT_RESOLUTION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONFLICT_RESOLUTION_SKIP\x10\x01\x12!\n" +
	"\x1dCONFLICT_RESOLUTION_OVERWRITE\x10\x02\x12\x1c\n" +
	"\x18CONFLICT_RESOLUTION_FAIL\x10\x03B\xda\x01\n" +
	"\x15com.elara.transfer.v1B\rTransferProtoP\x01ZLgithub.com/sergeyslonimsky/elara/internal/proto/elara/transfer/v1;transferv1\xa2\x02\x03ETX\xaa\x02\x11Elara.Transfer.V1\xca\x02\x11Elara\\Transfer\\V1\xe2\x02\x1dElara\\Transfer\\V1\\GPBMetadata\xea\x02\x13Elara::Transfer::V1b\x06proto3"

var (
	file_elara_transfer_v1_transfer_proto_rawDescOnce sync.Once
	file_elara_transfer_v1_transfer_proto_rawDescData []byte
)

func file_elara_transfer_v1_transfer_proto_rawDescGZIP() []byte {
	file_elara_transfer_v1_transfer_proto_rawDescOnce.Do(func() {
		file_elara_transfer_v1_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_transfer_v1_transfer_proto_rawDesc), len(file_elara_transfer_v1_transfer_proto_rawDesc)))
	})
	return file_elara_transfer_v1_transfer_proto_rawDescData
}

var file_elara_transfer_v1_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_elara_transfer_v1_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_elara_transfer_v1_transfer_proto_goTypes = []any{
	(BundleEncoding)(0),     // 0: elara.transfer.v1.BundleEncoding
	(ZipLayout)(0),          // 1: elara.transfer.v1.ZipLayout
	(ConflictResolution)(0), // 2: elara.transfer.v1.ConflictResolution
	(*ImportError)(nil),     // 3: elara.transfer.v1.ImportError
}
var file_elara_transfer_v1_transfer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_elara_transfer_v1_transfer_proto_init() }
func file_elara_transfer_v1_transfer_proto_init() {
	if File_elara_transfer_v1_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_transfer_v1_transfer_proto_rawDesc), len(file_elara_transfer_v1_transfer_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_elara_transfer_v1_transfer_proto_goTypes,
		DependencyIndexes: file_elara_transfer_v1_transfer_proto_depIdxs,
		EnumInfos:         file_elara_transfer_v1_transfer_proto_enumTypes,
		MessageInfos:      file_elara_transfer_v1_transfer_proto_msgTypes,
	}.Build()
	File_elara_transfer_v1_transfer_proto = out.File
	file_elara_transfer_v1_transfer_proto_goTypes = nil
	file_elara_transfer_v1_transfer_proto_depIdxs = nil
}
