// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sergeyslonimsky/elara/internal/usecase/webhook (interfaces: deliveryHistoryProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_history.go -package=webhook_mock . deliveryHistoryProvider
//

// Package webhook_mock is a generated GoMock package.
package webhook_mock

import (
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockdeliveryHistoryProvider is a mock of deliveryHistoryProvider interface.
type MockdeliveryHistoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryHistoryProviderMockRecorder
	isgomock struct{}
}

// MockdeliveryHistoryProviderMockRecorder is the mock recorder for MockdeliveryHistoryProvider.
type MockdeliveryHistoryProviderMockRecorder struct {
	mock *MockdeliveryHistoryProvider
}

// NewMockdeliveryHistoryProvider creates a new mock instance.
func NewMockdeliveryHistoryProvider(ctrl *gomock.Controller) *MockdeliveryHistoryProvider {
	mock := &MockdeliveryHistoryProvider{ctrl: ctrl}
	mock.recorder = &MockdeliveryHistoryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryHistoryProvider) EXPECT() *MockdeliveryHistoryProviderMockRecorder {
	return m.recorder
}

// GetDeliveryHistory mocks base method.
func (m *MockdeliveryHistoryProvider) GetDeliveryHistory(webhookID string) []domain.DeliveryAttempt {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveryHistory", webhookID)
	ret0, _ := ret[0].([]domain.DeliveryAttempt)
	return ret0
}

// GetDeliveryHistory indicates an expected call of GetDeliveryHistory.
func (mr *MockdeliveryHistoryProviderMockRecorder) GetDeliveryHistory(webhookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveryHistory", reflect.TypeOf((*MockdeliveryHistoryProvider)(nil).GetDeliveryHistory), webhookID)
}
