// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/common/v1/permission.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionObject int32

const (
	PermissionObject_PERMISSION_OBJECT_UNSPECIFIED PermissionObject = 0
	PermissionObject_PERMISSION_OBJECT_NAMESPACE   PermissionObject = 1
	PermissionObject_PERMISSION_OBJECT_CONFIG      PermissionObject = 2
	PermissionObject_PERMISSION_OBJECT_USER        PermissionObject = 3
	PermissionObject_PERMISSION_OBJECT_GROUP       PermissionObject = 4
	PermissionObject_PERMISSION_OBJECT_TOKEN       PermissionObject = 5
	PermissionObject_PERMISSION_OBJECT_WEBHOOK     PermissionObject = 6
)

// Enum value maps for PermissionObject.
var (
	PermissionObject_name = map[int32]string{
		0: "PERMISSION_OBJECT_UNSPECIFIED",
		1: "PERMISSION_OBJECT_NAMESPACE",
		2: "PERMISSION_OBJECT_CONFIG",
		3: "PERMISSION_OBJECT_USER",
		4: "PERMISSION_OBJECT_GROUP",
		5: "PERMISSION_OBJECT_TOKEN",
		6: "PERMISSION_OBJECT_WEBHOOK",
	}
	PermissionObject_value = map[string]int32{
		"PERMISSION_OBJECT_UNSPECIFIED": 0,
		"PERMISSION_OBJECT_NAMESPACE":   1,
		"PERMISSION_OBJECT_CONFIG":      2,
		"PERMISSION_OBJECT_USER":        3,
		"PERMISSION_OBJECT_GROUP":       4,
		"PERMISSION_OBJECT_TOKEN":       5,
		"PERMISSION_OBJECT_WEBHOOK":     6,
	}
)

func (x PermissionObject) Enum() *PermissionObject {
	p := new(PermissionObject)
	*p = x
	return p
}

func (x PermissionObject) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionObject) Descriptor() protoreflect.EnumDescriptor {
	return file_elara_common_v1_permission_proto_enumTypes[0].Descriptor()
}

func (PermissionObject) Type() protoreflect.EnumType {
	return &file_elara_common_v1_permission_proto_enumTypes[0]
}

func (x PermissionObject) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionObject.Descriptor instead.
func (PermissionObject) EnumDescriptor() ([]byte, []int) {
	return file_elara_common_v1_permission_proto_rawDescGZIP(), []int{0}
}

type PermissionAction int32

const (
	PermissionAction_PERMISSION_ACTION_UNSPECIFIED PermissionAction = 0
	PermissionAction_PERMISSION_ACTION_READ        PermissionAction = 1
	PermissionAction_PERMISSION_ACTION_WRITE       PermissionAction = 2
)

// Enum value maps for PermissionAction.
var (
	PermissionAction_name = map[int32]string{
		0: "PERMISSION_ACTION_UNSPECIFIED",
		1: "PERMISSION_ACTION_READ",
		2: "PERMISSION_ACTION_WRITE",
	}
	PermissionAction_value = map[string]int32{
		"PERMISSION_ACTION_UNSPECIFIED": 0,
		"PERMISSION_ACTION_READ":        1,
		"PERMISSION_ACTION_WRITE":       2,
	}
)

func (x PermissionAction) Enum() *PermissionAction {
	p := new(PermissionAction)
	*p = x
	return p
}

func (x PermissionAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionAction) Descriptor() protoreflect.EnumDescriptor {
	return file_elara_common_v1_permission_proto_enumTypes[1].Descriptor()
}

func (PermissionAction) Type() protoreflect.EnumType {
	return &file_elara_common_v1_permission_proto_enumTypes[1]
}

func (x PermissionAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionAction.Descriptor instead.
func (PermissionAction) EnumDescriptor() ([]byte, []int) {
	return file_elara_common_v1_permission_proto_rawDescGZIP(), []int{1}
}

type PermissionAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        PermissionObject       `protobuf:"varint,1,opt,name=object,proto3,enum=elara.common.v1.PermissionObject" json:"object,omitempty"`
	Action        PermissionAction       `protobuf:"varint,2,opt,name=action,proto3,enum=elara.common.v1.PermissionAction" json:"action,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionAssignment) Reset() {
	*x = PermissionAssignment{}
	mi := &file_elara_common_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionAssignment) ProtoMessage() {}

func (x *PermissionAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_elara_common_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionAssignment.ProtoReflect.Descriptor instead.
func (*PermissionAssignment) Descriptor() ([]byte, []int) {
	return file_elara_common_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionAssignment) GetObject() PermissionObject {
	if x != nil {
		return x.Object
	}
	return PermissionObject_PERMISSION_OBJECT_UNSPECIFIED
}

func (x *PermissionAssignment) GetAction() PermissionAction {
	if x != nil {
		return x.Action
	}
	return PermissionAction_PERMISSION_ACTION_UNSPECIFIED
}

func (x *PermissionAssignment) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

var File_elara_common_v1_permission_proto protoreflect.FileDescriptor

const file_elara_common_v1_permission_proto_rawDesc = "" +
	"\n" +
	" elara/common/v1/permission.proto\x12\x0felara.common.v1\"\xa4\x01\n" +
	"\x14PermissionAssignment\x129\n" +
	"\x06object\x18\x01 \x01(\x0e2!.elara.common.v1.PermissionObjectR\x06object\x129\n" +
	"\x06action\x18\x02 \x01(\x0e2!.elara.common.v1.PermissionActionR\x06action\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain*\xe9\x01\n" +
	"\x10PermissionObject\x12!\n" +
	"\x1dPERMISSION_OBJECT_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPERMISSION_OBJECT_NAMESPACE\x10\x01\x12\x1c\n" +
	"\x18PERMISSION_OBJECT_CONFIG\x10\x02\x12\x1a\n" +
	"\x16PERMISSION_OBJECT_USER\x10\x03\x12\x1b\n" +
	"\x17PERMISSION_OBJECT_GROUP\x10\x04\x12\x1b\n" +
	"\x17PERMISSION_OBJECT_TOKEN\x10\x05\x12\x1d\n" +
	"\x19PERMISSION_OBJECT_WEBHOOK\x10\x06*n\n" +
	"\x10PermissionAction\x12!\n" +
	"\x1dPERMISSION_ACTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PERMISSION_ACTION_READ\x10\x01\x12\x1b\n" +
	"\x17PERMISSION_ACTION_WRITE\x10\x02B\xce\x01\n" +
	"\x13com.elara.common.v1B\x0fPermissionProtoP\x01ZHgithub.com/sergeyslonimsky/elara/internal/proto/elara/common/v1;commonv1\xa2\x02\x03ECX\xaa\x02\x0fElara.Common.V1\xca\x02\x0fElara\\Common\\V1\xe2\x02\x1bElara\\Common\\V1\\GPBMetadata\xea\x02\x11Elara::Common::V1b\x06proto3"

var (
	file_elara_common_v1_permission_proto_rawDescOnce sync.Once
	file_elara_common_v1_permission_proto_rawDescData []byte
)

func file_elara_common_v1_permission_proto_rawDescGZIP() []byte {
	file_elara_common_v1_permission_proto_rawDescOnce.Do(func() {
		file_elara_common_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_common_v1_permission_proto_rawDesc), len(file_elara_common_v1_permission_proto_rawDesc)))
	})
	return file_elara_common_v1_permission_proto_rawDescData
}

var file_elara_common_v1_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_elara_common_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_elara_common_v1_permission_proto_goTypes = []any{
	(PermissionObject)(0),        // 0: elara.common.v1.PermissionObject
	(PermissionAction)(0),        // 1: elara.common.v1.PermissionAction
	(*PermissionAssignment)(nil), // 2: elara.common.v1.PermissionAssignment
}
var file_elara_common_v1_permission_proto_depIdxs = []int32{
	0, // 0: elara.common.v1.PermissionAssignment.object:type_name -> elara.common.v1.PermissionObject
	1, // 1: elara.common.v1.PermissionAssignment.action:type_name -> elara.common.v1.PermissionAction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_elara_common_v1_permission_proto_init() }
func file_elara_common_v1_permission_proto_init() {
	if File_elara_common_v1_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_common_v1_permission_proto_rawDesc), len(file_elara_common_v1_permission_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_elara_common_v1_permission_proto_goTypes,
		DependencyIndexes: file_elara_common_v1_permission_proto_depIdxs,
		EnumInfos:         file_elara_common_v1_permission_proto_enumTypes,
		MessageInfos:      file_elara_common_v1_permission_proto_msgTypes,
	}.Build()
	File_elara_common_v1_permission_proto = out.File
	file_elara_common_v1_permission_proto_goTypes = nil
	file_elara_common_v1_permission_proto_depIdxs = nil
}
