// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/handler_mock.go -package=access_mock -source=handler.go
//

// Package access_mock is a generated GoMock package.
package access_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	policy "github.com/sergeyslonimsky/elara/internal/usecase/policy"
	gomock "go.uber.org/mock/gomock"
)

// Mockauthz is a mock of authz interface.
type Mockauthz struct {
	ctrl     *gomock.Controller
	recorder *MockauthzMockRecorder
	isgomock struct{}
}

// MockauthzMockRecorder is the mock recorder for Mockauthz.
type MockauthzMockRecorder struct {
	mock *Mockauthz
}

// NewMockauthz creates a new mock instance.
func NewMockauthz(ctrl *gomock.Controller) *Mockauthz {
	mock := &Mockauthz{ctrl: ctrl}
	mock.recorder = &MockauthzMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockauthz) EXPECT() *MockauthzMockRecorder {
	return m.recorder
}

// Require mocks base method.
func (m *Mockauthz) Require(ctx context.Context, object domain.Object, action domain.Action, domainStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Require", ctx, object, action, domainStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Require indicates an expected call of Require.
func (mr *MockauthzMockRecorder) Require(ctx, object, action, domainStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Require", reflect.TypeOf((*Mockauthz)(nil).Require), ctx, object, action, domainStr)
}

// MockaccessUsecase is a mock of accessUsecase interface.
type MockaccessUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockaccessUsecaseMockRecorder
	isgomock struct{}
}

// MockaccessUsecaseMockRecorder is the mock recorder for MockaccessUsecase.
type MockaccessUsecaseMockRecorder struct {
	mock *MockaccessUsecase
}

// NewMockaccessUsecase creates a new mock instance.
func NewMockaccessUsecase(ctrl *gomock.Controller) *MockaccessUsecase {
	mock := &MockaccessUsecase{ctrl: ctrl}
	mock.recorder = &MockaccessUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccessUsecase) EXPECT() *MockaccessUsecaseMockRecorder {
	return m.recorder
}

// AssignRole mocks base method.
func (m *MockaccessUsecase) AssignRole(ctx context.Context, subject, dom string, role domain.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", ctx, subject, dom, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockaccessUsecaseMockRecorder) AssignRole(ctx, subject, dom, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockaccessUsecase)(nil).AssignRole), ctx, subject, dom, role)
}

// List mocks base method.
func (m *MockaccessUsecase) List(ctx context.Context) ([]policy.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]policy.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockaccessUsecaseMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockaccessUsecase)(nil).List), ctx)
}

// RevokeRole mocks base method.
func (m *MockaccessUsecase) RevokeRole(ctx context.Context, subject, dom string, role domain.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRole", ctx, subject, dom, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRole indicates an expected call of RevokeRole.
func (mr *MockaccessUsecaseMockRecorder) RevokeRole(ctx, subject, dom, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRole", reflect.TypeOf((*MockaccessUsecase)(nil).RevokeRole), ctx, subject, dom, role)
}
