syntax = "proto3";

package elara.common.v1;

enum PermissionObject {
  PERMISSION_OBJECT_UNSPECIFIED = 0;
  PERMISSION_OBJECT_NAMESPACE = 1;
  PERMISSION_OBJECT_CONFIG = 2;
  PERMISSION_OBJECT_USER = 3;
  PERMISSION_OBJECT_GROUP = 4;
  PERMISSION_OBJECT_TOKEN = 5;
  PERMISSION_OBJECT_WEBHOOK = 6;
  PERMISSION_OBJECT_ALL = 99;
}

enum PermissionAction {
  PERMISSION_ACTION_UNSPECIFIED = 0;
  PERMISSION_ACTION_READ = 1;
  PERMISSION_ACTION_WRITE = 2;
  PERMISSION_ACTION_ALL = 99;
}

message PermissionAssignment {
  PermissionObject object = 1;
  PermissionAction action = 2;
  string domain = 3;
}
