// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: elara/dashboard/v1/dashboard_service.proto

package dashboardv1

import (
	v1 "github.com/sergeyslonimsky/elara/internal/proto/elara/config/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_elara_dashboard_v1_dashboard_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_dashboard_v1_dashboard_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_elara_dashboard_v1_dashboard_service_proto_rawDescGZIP(), []int{0}
}

type GetStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NamespaceCount    int32                  `protobuf:"varint,1,opt,name=namespace_count,json=namespaceCount,proto3" json:"namespace_count,omitempty"`
	ConfigCount       int32                  `protobuf:"varint,2,opt,name=config_count,json=configCount,proto3" json:"config_count,omitempty"`
	ActiveClientCount int32                  `protobuf:"varint,3,opt,name=active_client_count,json=activeClientCount,proto3" json:"active_client_count,omitempty"`
	GlobalRevision    int64                  `protobuf:"varint,4,opt,name=global_revision,json=globalRevision,proto3" json:"global_revision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_elara_dashboard_v1_dashboard_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_dashboard_v1_dashboard_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_elara_dashboard_v1_dashboard_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsResponse) GetNamespaceCount() int32 {
	if x != nil {
		return x.NamespaceCount
	}
	return 0
}

func (x *GetStatsResponse) GetConfigCount() int32 {
	if x != nil {
		return x.ConfigCount
	}
	return 0
}

func (x *GetStatsResponse) GetActiveClientCount() int32 {
	if x != nil {
		return x.ActiveClientCount
	}
	return 0
}

func (x *GetStatsResponse) GetGlobalRevision() int64 {
	if x != nil {
		return x.GlobalRevision
	}
	return 0
}

type ActivityEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	EventType     v1.EventType           `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=elara.config.v1.EventType" json:"event_type,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityEntry) Reset() {
	*x = ActivityEntry{}
	mi := &file_elara_dashboard_v1_dashboard_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityEntry) ProtoMessage() {}

func (x *ActivityEntry) ProtoReflect() protoreflect.Message {
	mi := &file_elara_dashboard_v1_dashboard_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityEntry.ProtoReflect.Descriptor instead.
func (*ActivityEntry) Descriptor() ([]byte, []int) {
	return file_elara_dashboard_v1_dashboard_service_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityEntry) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ActivityEntry) GetEventType() v1.EventType {
	if x != nil {
		return x.EventType
	}
	return v1.EventType(0)
}

func (x *ActivityEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ActivityEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ActivityEntry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ActivityEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ListActivityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of entries to return. Defaults to 50 if 0.
	Limit         int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivityRequest) Reset() {
	*x = ListActivityRequest{}
	mi := &file_elara_dashboard_v1_dashboard_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityRequest) ProtoMessage() {}

func (x *ListActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elara_dashboard_v1_dashboard_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityRequest.ProtoReflect.Descriptor instead.
func (*ListActivityRequest) Descriptor() ([]byte, []int) {
	return file_elara_dashboard_v1_dashboard_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListActivityRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ActivityEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivityResponse) Reset() {
	*x = ListActivityResponse{}
	mi := &file_elara_dashboard_v1_dashboard_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityResponse) ProtoMessage() {}

func (x *ListActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elara_dashboard_v1_dashboard_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityResponse.ProtoReflect.Descriptor instead.
func (*ListActivityResponse) Descriptor() ([]byte, []int) {
	return file_elara_dashboard_v1_dashboard_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListActivityResponse) GetEntries() []*ActivityEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_elara_dashboard_v1_dashboard_service_proto protoreflect.FileDescriptor

const file_elara_dashboard_v1_dashboard_service_proto_rawDesc = "" +
	"\n" +
	"*elara/dashboard/v1/dashboard_service.proto\x12\x12elara.dashboard.v1\x1a\x1celara/config/v1/config.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x11\n" +
	"\x0fGetStatsRequest\"\xb7\x01\n" +
	"\x10GetStatsResponse\x12'\n" +
	"\x0fnamespace_count\x18\x01 \x01(\x05R\x0enamespaceCount\x12!\n" +
	"\fconfig_count\x18\x02 \x01(\x05R\vconfigCount\x12.\n" +
	"\x13active_client_count\x18\x03 \x01(\x05R\x11activeClientCount\x12'\n" +
	"\x0fglobal_revision\x18\x04 \x01(\x03R\x0eglobalRevision\"\xec\x01\n" +
	"\rActivityEntry\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x129\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x1a.elara.config.v1.EventTypeR\teventType\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"+\n" +
	"\x13ListActivityRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"S\n" +
	"\x14ListActivityResponse\x12;\n" +
	"\aentries\x18\x01 \x03(\v2!.elara.dashboard.v1.ActivityEntryR\aentries2\xcc\x01\n" +
	"\x10DashboardService\x12U\n" +
	"\bGetStats\x12#.elara.dashboard.v1.GetStatsRequest\x1a$.elara.dashboard.v1.GetStatsResponse\x12a\n" +
	"\fListActivity\x12'.elara.dashboard.v1.ListActivityRequest\x1a(.elara.dashboard.v1.ListActivityResponseB\xe9\x01\n" +
	"\x16com.elara.dashboard.v1B\x15DashboardServiceProtoP\x01ZNgithub.com/sergeyslonimsky/elara/internal/proto/elara/dashboard/v1;dashboardv1\xa2\x02\x03EDX\xaa\x02\x12Elara.Dashboard.V1\xca\x02\x12Elara\\Dashboard\\V1\xe2\x02\x1eElara\\Dashboard\\V1\\GPBMetadata\xea\x02\x14Elara::Dashboard::V1b\x06proto3"

var (
	file_elara_dashboard_v1_dashboard_service_proto_rawDescOnce sync.Once
	file_elara_dashboard_v1_dashboard_service_proto_rawDescData []byte
)

func file_elara_dashboard_v1_dashboard_service_proto_rawDescGZIP() []byte {
	file_elara_dashboard_v1_dashboard_service_proto_rawDescOnce.Do(func() {
		file_elara_dashboard_v1_dashboard_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elara_dashboard_v1_dashboard_service_proto_rawDesc), len(file_elara_dashboard_v1_dashboard_service_proto_rawDesc)))
	})
	return file_elara_dashboard_v1_dashboard_service_proto_rawDescData
}

var file_elara_dashboard_v1_dashboard_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_elara_dashboard_v1_dashboard_service_proto_goTypes = []any{
	(*GetStatsRequest)(nil),       // 0: elara.dashboard.v1.GetStatsRequest
	(*GetStatsResponse)(nil),      // 1: elara.dashboard.v1.GetStatsResponse
	(*ActivityEntry)(nil),         // 2: elara.dashboard.v1.ActivityEntry
	(*ListActivityRequest)(nil),   // 3: elara.dashboard.v1.ListActivityRequest
	(*ListActivityResponse)(nil),  // 4: elara.dashboard.v1.ListActivityResponse
	(v1.EventType)(0),             // 5: elara.config.v1.EventType
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_elara_dashboard_v1_dashboard_service_proto_depIdxs = []int32{
	5, // 0: elara.dashboard.v1.ActivityEntry.event_type:type_name -> elara.config.v1.EventType
	6, // 1: elara.dashboard.v1.ActivityEntry.timestamp:type_name -> google.protobuf.Timestamp
	2, // 2: elara.dashboard.v1.ListActivityResponse.entries:type_name -> elara.dashboard.v1.ActivityEntry
	0, // 3: elara.dashboard.v1.DashboardService.GetStats:input_type -> elara.dashboard.v1.GetStatsRequest
	3, // 4: elara.dashboard.v1.DashboardService.ListActivity:input_type -> elara.dashboard.v1.ListActivityRequest
	1, // 5: elara.dashboard.v1.DashboardService.GetStats:output_type -> elara.dashboard.v1.GetStatsResponse
	4, // 6: elara.dashboard.v1.DashboardService.ListActivity:output_type -> elara.dashboard.v1.ListActivityResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_elara_dashboard_v1_dashboard_service_proto_init() }
func file_elara_dashboard_v1_dashboard_service_proto_init() {
	if File_elara_dashboard_v1_dashboard_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elara_dashboard_v1_dashboard_service_proto_rawDesc), len(file_elara_dashboard_v1_dashboard_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elara_dashboard_v1_dashboard_service_proto_goTypes,
		DependencyIndexes: file_elara_dashboard_v1_dashboard_service_proto_depIdxs,
		MessageInfos:      file_elara_dashboard_v1_dashboard_service_proto_msgTypes,
	}.Build()
	File_elara_dashboard_v1_dashboard_service_proto = out.File
	file_elara_dashboard_v1_dashboard_service_proto_goTypes = nil
	file_elara_dashboard_v1_dashboard_service_proto_depIdxs = nil
}
