// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: elara/filter/v1/filter_service.proto

package filterv1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1 "github.com/sergeyslonimsky/elara/internal/proto/elara/filter/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FilterServiceName is the fully-qualified name of the FilterService service.
	FilterServiceName = "elara.filter.v1.FilterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FilterServiceGetNamespacesProcedure is the fully-qualified name of the FilterService's
	// GetNamespaces RPC.
	FilterServiceGetNamespacesProcedure = "/elara.filter.v1.FilterService/GetNamespaces"
	// FilterServiceGetGroupsProcedure is the fully-qualified name of the FilterService's GetGroups RPC.
	FilterServiceGetGroupsProcedure = "/elara.filter.v1.FilterService/GetGroups"
	// FilterServiceGetUsersProcedure is the fully-qualified name of the FilterService's GetUsers RPC.
	FilterServiceGetUsersProcedure = "/elara.filter.v1.FilterService/GetUsers"
)

// FilterServiceClient is a client for the elara.filter.v1.FilterService service.
type FilterServiceClient interface {
	GetNamespaces(
		context.Context,
		*connect.Request[v1.GetNamespacesRequest],
	) (*connect.Response[v1.GetNamespacesResponse], error)
	GetGroups(context.Context, *connect.Request[v1.GetGroupsRequest]) (*connect.Response[v1.GetGroupsResponse], error)
	GetUsers(context.Context, *connect.Request[v1.GetUsersRequest]) (*connect.Response[v1.GetUsersResponse], error)
}

// NewFilterServiceClient constructs a client for the elara.filter.v1.FilterService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFilterServiceClient(
	httpClient connect.HTTPClient,
	baseURL string,
	opts ...connect.ClientOption,
) FilterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	filterServiceMethods := v1.File_elara_filter_v1_filter_service_proto.Services().ByName("FilterService").Methods()

	return &filterServiceClient{
		getNamespaces: connect.NewClient[v1.GetNamespacesRequest, v1.GetNamespacesResponse](
			httpClient,
			baseURL+FilterServiceGetNamespacesProcedure,
			connect.WithSchema(filterServiceMethods.ByName("GetNamespaces")),
			connect.WithClientOptions(opts...),
		),
		getGroups: connect.NewClient[v1.GetGroupsRequest, v1.GetGroupsResponse](
			httpClient,
			baseURL+FilterServiceGetGroupsProcedure,
			connect.WithSchema(filterServiceMethods.ByName("GetGroups")),
			connect.WithClientOptions(opts...),
		),
		getUsers: connect.NewClient[v1.GetUsersRequest, v1.GetUsersResponse](
			httpClient,
			baseURL+FilterServiceGetUsersProcedure,
			connect.WithSchema(filterServiceMethods.ByName("GetUsers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// filterServiceClient implements FilterServiceClient.
type filterServiceClient struct {
	getNamespaces *connect.Client[v1.GetNamespacesRequest, v1.GetNamespacesResponse]
	getGroups     *connect.Client[v1.GetGroupsRequest, v1.GetGroupsResponse]
	getUsers      *connect.Client[v1.GetUsersRequest, v1.GetUsersResponse]
}

// GetNamespaces calls elara.filter.v1.FilterService.GetNamespaces.
func (c *filterServiceClient) GetNamespaces(
	ctx context.Context,
	req *connect.Request[v1.GetNamespacesRequest],
) (*connect.Response[v1.GetNamespacesResponse], error) {
	return c.getNamespaces.CallUnary(ctx, req)
}

// GetGroups calls elara.filter.v1.FilterService.GetGroups.
func (c *filterServiceClient) GetGroups(
	ctx context.Context,
	req *connect.Request[v1.GetGroupsRequest],
) (*connect.Response[v1.GetGroupsResponse], error) {
	return c.getGroups.CallUnary(ctx, req)
}

// GetUsers calls elara.filter.v1.FilterService.GetUsers.
func (c *filterServiceClient) GetUsers(
	ctx context.Context,
	req *connect.Request[v1.GetUsersRequest],
) (*connect.Response[v1.GetUsersResponse], error) {
	return c.getUsers.CallUnary(ctx, req)
}

// FilterServiceHandler is an implementation of the elara.filter.v1.FilterService service.
type FilterServiceHandler interface {
	GetNamespaces(
		context.Context,
		*connect.Request[v1.GetNamespacesRequest],
	) (*connect.Response[v1.GetNamespacesResponse], error)
	GetGroups(context.Context, *connect.Request[v1.GetGroupsRequest]) (*connect.Response[v1.GetGroupsResponse], error)
	GetUsers(context.Context, *connect.Request[v1.GetUsersRequest]) (*connect.Response[v1.GetUsersResponse], error)
}

// NewFilterServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFilterServiceHandler(svc FilterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	filterServiceMethods := v1.File_elara_filter_v1_filter_service_proto.Services().ByName("FilterService").Methods()
	filterServiceGetNamespacesHandler := connect.NewUnaryHandler(
		FilterServiceGetNamespacesProcedure,
		svc.GetNamespaces,
		connect.WithSchema(filterServiceMethods.ByName("GetNamespaces")),
		connect.WithHandlerOptions(opts...),
	)
	filterServiceGetGroupsHandler := connect.NewUnaryHandler(
		FilterServiceGetGroupsProcedure,
		svc.GetGroups,
		connect.WithSchema(filterServiceMethods.ByName("GetGroups")),
		connect.WithHandlerOptions(opts...),
	)
	filterServiceGetUsersHandler := connect.NewUnaryHandler(
		FilterServiceGetUsersProcedure,
		svc.GetUsers,
		connect.WithSchema(filterServiceMethods.ByName("GetUsers")),
		connect.WithHandlerOptions(opts...),
	)

	return "/elara.filter.v1.FilterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FilterServiceGetNamespacesProcedure:
			filterServiceGetNamespacesHandler.ServeHTTP(w, r)
		case FilterServiceGetGroupsProcedure:
			filterServiceGetGroupsHandler.ServeHTTP(w, r)
		case FilterServiceGetUsersProcedure:
			filterServiceGetUsersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFilterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFilterServiceHandler struct{}

func (UnimplementedFilterServiceHandler) GetNamespaces(
	context.Context,
	*connect.Request[v1.GetNamespacesRequest],
) (*connect.Response[v1.GetNamespacesResponse], error) {
	return nil, connect.NewError(
		connect.CodeUnimplemented,
		errors.New("elara.filter.v1.FilterService.GetNamespaces is not implemented"),
	)
}

func (UnimplementedFilterServiceHandler) GetGroups(
	context.Context,
	*connect.Request[v1.GetGroupsRequest],
) (*connect.Response[v1.GetGroupsResponse], error) {
	return nil, connect.NewError(
		connect.CodeUnimplemented,
		errors.New("elara.filter.v1.FilterService.GetGroups is not implemented"),
	)
}

func (UnimplementedFilterServiceHandler) GetUsers(
	context.Context,
	*connect.Request[v1.GetUsersRequest],
) (*connect.Response[v1.GetUsersResponse], error) {
	return nil, connect.NewError(
		connect.CodeUnimplemented,
		errors.New("elara.filter.v1.FilterService.GetUsers is not implemented"),
	)
}
