// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mock.go -package=dashboard_mock -source=service.go
//

// Package dashboard_mock is a generated GoMock package.
package dashboard_mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/sergeyslonimsky/elara/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// Mockpdp is a mock of pdp interface.
type Mockpdp struct {
	ctrl     *gomock.Controller
	recorder *MockpdpMockRecorder
	isgomock struct{}
}

// MockpdpMockRecorder is the mock recorder for Mockpdp.
type MockpdpMockRecorder struct {
	mock *Mockpdp
}

// NewMockpdp creates a new mock instance.
func NewMockpdp(ctrl *gomock.Controller) *Mockpdp {
	mock := &Mockpdp{ctrl: ctrl}
	mock.recorder = &MockpdpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockpdp) EXPECT() *MockpdpMockRecorder {
	return m.recorder
}

// Has mocks base method.
func (m *Mockpdp) Has(principal string, perm domain.Permission) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", principal, perm)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Has indicates an expected call of Has.
func (mr *MockpdpMockRecorder) Has(principal, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*Mockpdp)(nil).Has), principal, perm)
}

// MocknsLister is a mock of nsLister interface.
type MocknsLister struct {
	ctrl     *gomock.Controller
	recorder *MocknsListerMockRecorder
	isgomock struct{}
}

// MocknsListerMockRecorder is the mock recorder for MocknsLister.
type MocknsListerMockRecorder struct {
	mock *MocknsLister
}

// NewMocknsLister creates a new mock instance.
func NewMocknsLister(ctrl *gomock.Controller) *MocknsLister {
	mock := &MocknsLister{ctrl: ctrl}
	mock.recorder = &MocknsListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknsLister) EXPECT() *MocknsListerMockRecorder {
	return m.recorder
}

// ListAll mocks base method.
func (m *MocknsLister) ListAll(ctx context.Context) ([]*domain.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]*domain.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MocknsListerMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MocknsLister)(nil).ListAll), ctx)
}

// MockconfigCounter is a mock of configCounter interface.
type MockconfigCounter struct {
	ctrl     *gomock.Controller
	recorder *MockconfigCounterMockRecorder
	isgomock struct{}
}

// MockconfigCounterMockRecorder is the mock recorder for MockconfigCounter.
type MockconfigCounterMockRecorder struct {
	mock *MockconfigCounter
}

// NewMockconfigCounter creates a new mock instance.
func NewMockconfigCounter(ctrl *gomock.Controller) *MockconfigCounter {
	mock := &MockconfigCounter{ctrl: ctrl}
	mock.recorder = &MockconfigCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfigCounter) EXPECT() *MockconfigCounterMockRecorder {
	return m.recorder
}

// CountByNamespace mocks base method.
func (m *MockconfigCounter) CountByNamespace(ctx context.Context, namespace string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByNamespace", ctx, namespace)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByNamespace indicates an expected call of CountByNamespace.
func (mr *MockconfigCounterMockRecorder) CountByNamespace(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByNamespace", reflect.TypeOf((*MockconfigCounter)(nil).CountByNamespace), ctx, namespace)
}

// CurrentRevision mocks base method.
func (m *MockconfigCounter) CurrentRevision(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentRevision", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentRevision indicates an expected call of CurrentRevision.
func (mr *MockconfigCounterMockRecorder) CurrentRevision(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentRevision", reflect.TypeOf((*MockconfigCounter)(nil).CurrentRevision), ctx)
}

// MockactivitySource is a mock of activitySource interface.
type MockactivitySource struct {
	ctrl     *gomock.Controller
	recorder *MockactivitySourceMockRecorder
	isgomock struct{}
}

// MockactivitySourceMockRecorder is the mock recorder for MockactivitySource.
type MockactivitySourceMockRecorder struct {
	mock *MockactivitySource
}

// NewMockactivitySource creates a new mock instance.
func NewMockactivitySource(ctrl *gomock.Controller) *MockactivitySource {
	mock := &MockactivitySource{ctrl: ctrl}
	mock.recorder = &MockactivitySourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockactivitySource) EXPECT() *MockactivitySourceMockRecorder {
	return m.recorder
}

// ListRecentChanges mocks base method.
func (m *MockactivitySource) ListRecentChanges(ctx context.Context, limit int) ([]*domain.ChangelogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentChanges", ctx, limit)
	ret0, _ := ret[0].([]*domain.ChangelogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentChanges indicates an expected call of ListRecentChanges.
func (mr *MockactivitySourceMockRecorder) ListRecentChanges(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentChanges", reflect.TypeOf((*MockactivitySource)(nil).ListRecentChanges), ctx, limit)
}

// MockactiveClientsSource is a mock of activeClientsSource interface.
type MockactiveClientsSource struct {
	ctrl     *gomock.Controller
	recorder *MockactiveClientsSourceMockRecorder
	isgomock struct{}
}

// MockactiveClientsSourceMockRecorder is the mock recorder for MockactiveClientsSource.
type MockactiveClientsSourceMockRecorder struct {
	mock *MockactiveClientsSource
}

// NewMockactiveClientsSource creates a new mock instance.
func NewMockactiveClientsSource(ctrl *gomock.Controller) *MockactiveClientsSource {
	mock := &MockactiveClientsSource{ctrl: ctrl}
	mock.recorder = &MockactiveClientsSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockactiveClientsSource) EXPECT() *MockactiveClientsSourceMockRecorder {
	return m.recorder
}

// ListActive mocks base method.
func (m *MockactiveClientsSource) ListActive() []*domain.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive")
	ret0, _ := ret[0].([]*domain.Client)
	return ret0
}

// ListActive indicates an expected call of ListActive.
func (mr *MockactiveClientsSourceMockRecorder) ListActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockactiveClientsSource)(nil).ListActive))
}
